### PR TITLE
fix: Update syntax for Terraform 0.15

### PR DESCRIPTION
**Pull request by antonbabenko**

### CODE REVIEW

**Comment by antonbabenko** [comment]
@barryib I have added a couple of fixes related to Terraform 0.15 syntax while making these kinds of changes in other repositories, and wonder if you also want to use the same flow with GH Actions developed by @bryantbiggs ? We are using it since last week on most of others repositories (for example, https://github.com/terraform-aws-modules/terraform-aws-lambda/blob/master/.github/workflows/pre-commit.yml).

It would be very nice for us to use the same process across all repos in this organization. Bryant's solution allows to have multiple versions for examples, modules, root dir and `terraform_validate` will be executed for the lowest supported version, while the complete set of pre-commit hooks is executed with the maximum supported version of Terraform.

**Comment by TjeuKayim** [comment]
This seems to be a partial duplicate of my pull request #1165 that replaces the use of deprecated functions `list()` and `map()` with the new syntax.

**Comment by antonbabenko** [comment]
@TjeuKayim I see it now, I will be able to rebase this one after yours is merged.

**Comment by mbevc1** [comment]
0.15 was released today :partying_face:
Could we get those PRs merged?

**Comment by antonbabenko** [comment]
For the Terraform 0.15 users [v15.1.0](https://github.com/terraform-aws-modules/terraform-aws-eks/releases/v15.1.0) has been just released.

**Comment by mbevc1** [comment]
Cheers @antonbabenko :tada:

**Comment by antonbabenko** [comment]
Very good question! I was not entirely sure about the release process for this module. We will have to ask @barryib to make a release the way he does it normally.

**Pull request closed without merging**
