### PR TITLE
feat: Add customizable Auto Scaling Group health check type

### PR DESCRIPTION
**Pull request by svaranasi-traderev**
# PR o'clock

## Description

Adding the ability to define health-check type for autoscaling groups. I [saw this issue](https://github.com/terraform-aws-modules/terraform-aws-eks/issues/1009) without a PR, so this is that. 

### Checklist

- [x] CI tests are passing
- [x] README.md has been updated after any changes to variables and outputs. See https://github.com/terraform-aws-modules/terraform-aws-eks/#doc-generation

### CODE REVIEW

**Comment by svaranasi-traderev** [comment]
Hello there! Just wondering if there's anything else that you need from me before you review this PR, or if it's just a wait and watch thingy.

**Comment by svaranasi-traderev** [comment]
I'd love if someone could take a quick look at this PR. Please let me know if you need any further information to help this get merged. Thanks!

**Comment by svaranasi-traderev** [comment]
Anybody?

**Review by barryib — APPROVED** [review]
Thanks @svaranasi-traderev

**Pull request merged**
