### PR TITLE
feat: Override cluster and workers egress CIDRs

### LINKED ISSUE #1236: Add ability to override CIDR blocks on egress security rules
# I have issues

## I'm submitting a...

* [ ] bug report
* [x] feature request
* [ ] support request - read the [FAQ](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/docs/faq.md) first!
* [ ] kudos, thank you, warm fuzzy

## What is the current behavior?

We use entirely private VPC's that don't have direct internet access, although access through an internal proxy is possible. As such we generally don't like any security group rule that contains 0.0.0.0/0 and prefer to list our internal ranges instead.

The `aws_security_group_rule.cluster_egress_internet` and `aws_security_group_rule.workers_egress_internet` resources are both currently hardcoded to use 0.0.0.0/0 as the destination CIDR block(s). In order to not have those rules present I end up having to manage the security groups myself and then have to duplicate every rule in your EKS module.

## What's the expected behavior?

Expose two new variables for the cluster and worker egress CIDR blocks that both default to `["0.0.0.0/0"]`. I can then override both and then take advantage of your module managing the security groups for me.

## Are you able to fix this problem and submit a PR? Link here if you have already.

PR incoming shortly.

## Environment details

* Affected module version: 14.0
* OS:
* Terraform version: 0.14.x

### PR DESCRIPTION
**Pull request by bodgit**
# PR o'clock

## Description

Add two new variables to allow the destination CIDR blocks used in egress rules to be overridden. Default values match the previously hardcoded values.

Fixes #1236

### Checklist

- [x] CI tests are passing
- [x] README.md has been updated after any changes to variables and outputs. See https://github.com/terraform-aws-modules/terraform-aws-eks/#doc-generation

### CODE REVIEW

**Comment by bodgit** [comment]
I don't believe the Lint / Docs failure is due to anything I've changed.

**Comment by wmene** [comment]
Any idea when this will get merged?

**Comment by barryib** [comment]
@bodgit Can you please update your branch and resolve conflict.

**Comment by bodgit** [comment]
@barryib Done

**Review by barryib — APPROVED** [review]

**Pull request merged**
