### PR TITLE
fix: use aws eks get-token for kubectl auth

### LINKED ISSUE #957: Use "aws eks get-token" instead of "aws-iam-authenticator"
## Use `aws eks get-token` instead of `aws-iam-authenticator`
Since AWS CLI version 1.16.156, `aws-iam-authenticator` is no longer needed to obtain an auth token for the EKS cluster. This can be performed using `awscli` directly with `aws eks get-token`. [(reference)](https://docs.aws.amazon.com/eks/latest/userguide/install-aws-iam-authenticator.html)

I propose changing the default value of `kubeconfig_aws_authenticator_command` and `kubeconfig_aws_authenticator_command_args` to:
```hcl
  kubeconfig_aws_authenticator_command = "aws"
  kubeconfig_aws_authenticator_command_args = [
    "--region", 
    data.aws_region.this.name,
    "eks",
    "get-token",
    "--cluster-name",
    local.cluster_name
  ]
}
```

## I'm submitting a...

* [ ] bug report
* [x] feature request
* [ ] support request - read the [FAQ](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/docs/faq.md) first!
* [ ] kudos, thank you, warm fuzzy

## What is the current behavior?
External dependency on `aws-iam-authenticator` tool causes `terraform apply` to fail when not installed.
This dependency is not clearly indicated in the readme.

## If this is a bug, how to reproduce? Please include a code sample if relevant.
Using this module without having installed `aws-iam-authenticator` will throw an error while provisioning the cluster.

## What's the expected behavior?
No external dependency on `aws-iam-authenticator`.

## Are you able to fix this problem and submit a PR? Link here if you have already.
Yes

## Environment details

* Affected module version: **v10.0.0**
* OS: **Mac OS Catalina 10.15.4**
* Terraform version: **v0.12.26**

## Any other relevant info
I'm not sure which tool is more common for this purpose, but our team uses `awscli` whenever possible. Since this functionality is now present in `awscli >= 1.16.156` (we are using `v2.0.19`), it might be worthwhile to use it instead of `aws-iam-authenticator`.

In any case, whether depending on `awscli` or `aws-iam-authenticator`, it might be a good idea to clearly indicate external dependencies in the module readme.

### PR DESCRIPTION
**Pull request by schollii**
# PR o'clock

## Description

Fixes #957 

Use aws eks get-token instead of aws iam authenticator

### Checklist

- [n/a ] README.md has been updated after any changes to variables and outputs. See https://github.com/terraform-aws-modules/terraform-aws-eks/#doc-generation

### CODE REVIEW

**Comment by schollii** [comment]
> @schollii could you post `terraform plan` output, please...

@lisfo4ka, in what folder should I run this?

**Review by timblaktu — APPROVED** [review]
Changes look good to me. This will be a big improvement. All external examples of first steps configuring kubectl to auth/connect to an EKS cluster use the `aws eks update-kubeconfig` approach, which uses the `get-token` approach, so aligning this Terraform module will prevent new users from being confused why they're so different (and prevent them from having to install `aws-iam-authenticator`.)

**Comment by bryantbiggs** [comment]
I think we should include this in a breaking change and drop all support for the legacy iam-authenticator approach - thoughts @daroga0002 ?

**Comment by daroga0002** [comment]
I tried to search what are benefits of using aws-iam-authenticator and I dont see any, maybe somebody from community will be able to put some arguments here.


From my side I think we can:
1. drop totally support for aws-iam-authenticator and remove any customization in our code
2.  provide in outputs (I believ most or all are arleady done) values which can be used to build any form of Kube config (so thne if somebody will have own requirements can pass a template and fill them by outputs)

**Comment by schollii** [comment]
It's a good idea but I think it's taking this ticket beyond original scope, a separate ticket would be better so we can close this asap.

**Comment by Yasumoto** [comment]
Getting this over the finish line would be rad. When I was first getting started, trying to find this extra tool (and figure out if `aws-iam-authenticator` was actively recommended) was a bit of a road bump.

**Comment by daroga0002** [comment]
> It's a good idea but I think it's taking this ticket beyond original scope, a separate ticket would be better so we can close this asap.

@schollii  can you adjust comments https://github.com/terraform-aws-modules/terraform-aws-eks/pull/1590#discussion_r736768353 and then we will merge it to v17.* version

Work about redesign we will cover in other PR for v18* milestone

**Comment by schollii** [comment]
@daroga0002 not sure what you mean, clicking that link in your post just gets me to the top of the PR

**Comment by antonbabenko** [comment]
@daroga0002 I think we should have this one merged (after outstanding code changes got merged) and release a minor release in `v17`.

I am not knowledgeable enough to suggest dropping part of the functionality since it already works. I think we can reevaluate it as a part of the breaking changes we are going to have in v18 but not in this PR.

**Comment by daroga0002** [comment]
> I am not knowledgeable enough to suggest dropping part of the functionality since it already works. I think we can reevaluate it as a part of the breaking changes we are going to have in v18 but not in this PR.

Yes this is what I am suggesting, now we simply extend to allow feature in v17 and in v18 we will drop legacy approach (as that will be bigger breaking change  release so migration will be not so fast probably).

I will duplicate this PR and make fixes on my branch, test and open PR as I cannot edit this.

**Comment by lisfo4ka** [comment]
Folks, I'd really like to deliver this change to the v17, so I've created a new PR with proper testing. Please, take a look at #1699

**Comment by antonbabenko** [comment]
This issue has been resolved in version 18.0.0 :tada:

**Pull request closed without merging**
