### PR TITLE
improvement: Support substitution in windows template user_data -KubeletExtraArgs by using Double Quotes

### PR DESCRIPTION
**Pull request by sebas-w**
# PR o'clock

## Description

I modified the windows user_data template to utilize double quotes instead of single quotes so we can pass in arguments like: 

```bash
node.kubernetes.io/lifecycle=$(Invoke-WebRequest -Uri http://169.254.169.254/latest/meta-data/instance-life-cycle | Select-Object -ExpandProperty Content)
```

This has worked in testing and production usage, but I want to get new features related to node groups. Unfortunately windows is still not supported yet for node_groups so I need to retain this functionality, but would like to merge this to the public module so I can stop maintaining a forked repo.

### Checklist

- [x] README.md has been updated after any changes to variables and outputs. See https://github.com/terraform-aws-modules/terraform-aws-eks/#doc-generation

### CODE REVIEW

**Comment by sebas-w** [comment]
@daroga0002 , How can I get this reviewed?

**Comment by sebas-w** [comment]
@barryib, How can I get this reviewed?

**Comment by daroga0002** [comment]
> @daroga0002 , How can I get this reviewed?

I am not a maintainer of this repo, so dont have rights to merge it. 

We must wait for @barryib

**Comment by sebas-w** [comment]
@barryib Can I get a review please, thanks!

**Comment by daroga0002** [comment]
Basing on https://www.tutorialspoint.com/difference-between-single-quote-and-double-quote-in-powershell and comments from @sebas-w it will help users which using Windows node groups.

**Review by daroga0002 — APPROVED** [review]

**Comment by daroga0002** [comment]
this is also duplicating https://github.com/terraform-aws-modules/terraform-aws-eks/pull/1082

**Comment by antonbabenko** [comment]
Fixed by #1082

**Comment by antonbabenko** [comment]
This has been fixed and released in [v17.8.0](https://github.com/terraform-aws-modules/terraform-aws-eks/releases/v17.8.0).

**Pull request closed without merging**
