### PR TITLE
Make plan more consistent and avoid unnecessary "(known after apply)"

### PR DESCRIPTION
**Pull request by barryib**
# PR o'clock

## Description

By using explicitly `local.default_iam_role_id` interpolation in `aws_iam_instance_profile` resources, we can avoid `(known after apply)` messages in plan. This will produce a more readable plan and avoid showing attributes which are defined. This is because, Terraform will take the whole `local.workers_group_defaults_defaults` map as unknown because `local.default_iam_role_id` will exist only after an apply, because only an apply will create the `aws_iam_role.workers.*.id` resource.

More info in https://github.com/terraform-aws-modules/terraform-aws-eks/issues/481#issuecomment-524817067

Should resolve https://github.com/terraform-aws-modules/terraform-aws-eks/issues/481

cc @dpiddockcmp @max-rocket-internet 

#### Plan made without this PR

```hcl
+ resource "aws_autoscaling_group" "workers_launch_template_mixed" {
      + arn                       = (known after apply)
      + availability_zones        = (known after apply)
      + default_cooldown          = (known after apply)
      + desired_capacity          = 3
      + enabled_metrics           = (known after apply)
      + force_delete              = (known after apply)
      + health_check_grace_period = 300
      + health_check_type         = (known after apply)
      + id                        = (known after apply)
      + load_balancers            = (known after apply)
      + max_size                  = 5
      + metrics_granularity       = "1Minute"
      + min_size                  = 3
      + name                      = (known after apply)
      + name_prefix               = (known after apply)
      + placement_group           = (known after apply)
      + protect_from_scale_in     = (known after apply)
      + service_linked_role_arn   = (known after apply)
      + suspended_processes       = (known after apply)
      + tags                      = (known after apply)
      + target_group_arns         = (known after apply)
      + termination_policies      = (known after apply)
      + vpc_zone_identifier       = (known after apply)
      + wait_for_capacity_timeout = "10m"

      + initial_lifecycle_hook {
          + default_result          = (known after apply)
          + heartbeat_timeout       = (known after apply)
          + lifecycle_transition    = (known after apply)
          + name                    = (known after apply)
          + notification_metadata   = (known after apply)
          + notification_target_arn = (known after apply)
          + role_arn                = (known after apply)
        }

      + mixed_instances_policy {
          + instances_distribution {
              + on_demand_allocation_strategy            = (known after apply)
              + on_demand_base_capacity                  = (known after apply)
              + on_demand_percentage_above_base_capacity = (known after apply)
              + spot_allocation_strategy                 = (known after apply)
              + spot_instance_pools                      = 4
              + spot_max_price                           = (known after apply)
            }

          + launch_template {
              + launch_template_specification {
                  + launch_template_id   = (known after apply)
                  + launch_template_name = (known after apply)
                  + version              = (known after apply)
                }

              + override {
                  + instance_type = (known after apply)
                }
            }
        }
    }
```

#### Plan made with this PR

```hcl
+ resource "aws_autoscaling_group" "workers_launch_template_mixed" {
      + arn                       = (known after apply)
      + availability_zones        = (known after apply)
      + default_cooldown          = (known after apply)
      + desired_capacity          = 3
      + enabled_metrics           = []
      + force_delete              = false
      + health_check_grace_period = 300
      + health_check_type         = (known after apply)
      + id                        = (known after apply)
      + load_balancers            = (known after apply)
      + max_size                  = 5
      + metrics_granularity       = "1Minute"
      + min_size                  = 3
      + name                      = (known after apply)
      + name_prefix               = "test-tba-ehp-eks-worker"
      + protect_from_scale_in     = false
      + service_linked_role_arn   = (known after apply)
      + suspended_processes       = [
          + "AZRebalance",
        ]
      + tags                      = [
          + {
              + "key"                 = "Name"
              + "propagate_at_launch" = "true"
              + "value"               = "test-tba-ehp-eks-worker-eks_asg"
            },
          + {
              + "key"                 = "kubernetes.io/cluster/test-tba-ehp"
              + "propagate_at_launch" = "true"
              + "value"               = "owned"
            },
          + {
              + "key"                 = "k8s.io/cluster-autoscaler/enabled"
              + "propagate_at_launch" = "false"
              + "value"               = "true"
            },
          + {
              + "key"                 = "k8s.io/cluster-autoscaler/test-tba-ehp"
              + "propagate_at_launch" = "false"
              + "value"               = "test-tba-ehp"
            },
          + {
              + "key"                 = "k8s.io/cluster-autoscaler/node-template/resources/ephemeral-storage"
              + "propagate_at_launch" = "false"
              + "value"               = "20Gi"
            }
        ]
      + target_group_arns         = []
      + termination_policies      = []
      + vpc_zone_identifier       = [
          + "subnet-xxxx",
          + "subnet-xxxx",
          + "subnet-xxxx",
        ]
      + wait_for_capacity_timeout = "10m"

      + mixed_instances_policy {
          + instances_distribution {
              + on_demand_allocation_strategy            = "prioritized"
              + on_demand_base_capacity                  = 0
              + on_demand_percentage_above_base_capacity = 100
              + spot_allocation_strategy                 = "lowest-price"
              + spot_instance_pools                      = 4
            }

          + launch_template {
              + launch_template_specification {
                  + launch_template_id   = (known after apply)
                  + launch_template_name = (known after apply)
                  + version              = "$Latest"
                }

              + override {
                  + instance_type = "m5.large"
                }
              + override {
                  + instance_type = "m5a.large"
                }
              + override {
                  + instance_type = "m5d.large"
                }
              + override {
                  + instance_type = "m5ad.large"
                }
            }
        }
    }
```

As you notice, there are a lot values already known with the first plan but was tagged incorrectly by terraform as `known after apply`.

### Checklist

- [x] `terraform fmt` and `terraform validate` both work from the root and `examples/*` directories
- [x] CI tests are passing
- [x] I've added my change to CHANGELOG.md and highlighted any breaking changes
- [ ] README.md has been updated after any changes to variables and outputs. See https://github.com/terraform-aws-modules/terraform-aws-eks/#doc-generation

### CODE REVIEW

**Comment by max-rocket-internet** [comment]
Does it resolve your issue, @vranystepan?

**Comment by barryib** [comment]
@max-rocket-internet please hold this PR for now. See https://github.com/terraform-aws-modules/terraform-aws-eks/issues/481#issuecomment-529396737 for more info.

**Comment by barryib** [comment]
@max-rocket-internet sounds like the new release of terraform doesn't help https://github.com/terraform-aws-modules/terraform-aws-eks/issues/481#issuecomment-529453395

@apolegoshko confirm that this PR fixed his issue.

**Comment by barryib** [comment]
@max-rocket-internet how we can move on this PR ?

**Pull request merged**
