### PR TITLE
fix: Invoke `aws_iam_session_context` data source only when required

### PR DESCRIPTION
**Pull request by krlydm**
## Description
Terraform fails to read `aws_iam_session_context` data resource when you are running your Terraform code inside a private VPC in AWS as IAM has no service endpoint to attach: 
https://docs.aws.amazon.com/vpc/latest/privatelink/aws-services-privatelink-support.html

## Motivation and Context
Since KMS key creation and cluster admin permissions where this data resource referenced are conditional, we can use the same condition for `aws_iam_session_context` data resource.

## Breaking Changes
Not a breaking change.

## How Has This Been Tested?
- [x] I have updated at least one of the `examples/*` to demonstrate and validate my change(s)
- [x] I have tested and validated these changes using one or more of the provided `examples/*` projects
- [x] I have executed `pre-commit run -a` on my pull request

### CODE REVIEW

**Review by bryantbiggs — APPROVED** [review]
thank you!

**Comment by antonbabenko** [comment]
This PR is included in version 20.17.1 :tada:

**Comment by jessebye** [comment]
This seems to break our EKS use:

```
╷
│ Error: Invalid index
│
│   on .terraform/modules/eks/main.tf line 151, in locals:
│  151:       principal_arn = data.aws_iam_session_context.current[0].issuer_arn
│     ├────────────────
│     │ data.aws_iam_session_context.current is empty tuple
│
│ The given key does not identify an element in this collection value: the collection has no elements.
╵
╷
│ Error: Invalid index
│
│   on .terraform/modules/eks/main.tf line 240, in module "kms":
│  240:   key_administrators        = coalescelist(var.kms_key_administrators, [data.aws_iam_session_context.current[0].issuer_arn])
│     ├────────────────
│     │ data.aws_iam_session_context.current is empty tuple
│
│ The given key does not identify an element in this collection value: the collection has no elements.
╵
error: Recipe `apply` failed on line 29 with exit code 1
```

**Comment by zacharyfleck** [comment]
> I confirmed pinning the module to `20.16.0` resolves the issue.

Confirming the same. Felt a wave of panic briefly when I got the random error. 🤣 Thanks for the quick resolution though!

**Comment by bryantbiggs** [comment]
My apologies - we have reverted the commit

**Comment by zacharyfleck** [comment]
Thanks @bryantbiggs! Can also confirm all is good again with 20.17.2.

**Pull request merged**
