### PR TITLE
feat: Enable ebs_optimized setting for node_groups

### LINKED ISSUE #1489: Enable ebs optimized for node group
There is an outstanding PR for this functionality (https://github.com/terraform-aws-modules/terraform-aws-eks/pull/1459), as I need it implemented. Any idea when this PR can be merged in and a new release pushed?

### PR DESCRIPTION
**Pull request by alzabo**
# PR o'clock

## Description

Add logic to selectively enable ebs_optimized in node group LT

- Setting ebs_optimized on an individual node_group to a boolean value
  will set the launch template to true or false
- Likewise, setting ebs_optimized on node_groups_defaults to a boolean
  will set it in the LT
- ebs_optimized in the node_group is null, instance_types are checked
  against var.workers_group_defaults. If any instance type does not
  support EBS optimization, the property will be set to false in the LT,
  otherwise it will be set to true

### Checklist

- [x] README.md has been updated after any changes to variables and outputs. See https://github.com/terraform-aws-modules/terraform-aws-eks/#doc-generation

Fixes #1489

### CODE REVIEW

**Comment by nodesocket** [comment]
Is this supported? I could not find a way to enable EBS optimzed for my node group.

```
node_groups = {
    general = {
      desired_capacity       = 3
      max_capacity           = 3
      min_capacity           = 3
      instance_types         = ["m5.xlarge"]
      disk_size              = 250
      public_ip              = false
      capacity_type          = "ON_DEMAND"
      ami_release_version    = "1.20.4-20210628"
      create_launch_template = true
      enable_monitoring      = true

      k8s_labels = {
        Env = var.environment
      }

      tags = {
        Env          = var.environment
        AutoSnapshot = "true"
      }
    }
  }
  ```

**Comment by nodesocket** [comment]
@alzabo I manually edited the launch template in AWS console and flipped on EBS optimized, however now Terraform is wanting to undo that change every time I apply. Can we get this merged in? I need to have EBS optimized instances in my node group. Thanks.

```
  # module.stage.module.node_groups.aws_eks_node_group.workers["general"] will be updated in-place
  ~ resource "aws_eks_node_group" "workers" {
        id                     = "acme-stage:acme-stage-general20210713190011077200000002"
        tags                   = {
            "AutoSnapshot" = "true"
            "Env"          = "stage"
        }
        # (16 unchanged attributes hidden)

      ~ launch_template {
            id      = "lt-0b296712f77a5062f"
            name    = "acme-stage-general20210713172835067400000004"
          ~ version = "3" -> "$Latest"
        }

        # (1 unchanged block hidden)
    }

  # module.stage.module.node_groups.aws_launch_template.workers["general"] will be updated in-place
  ~ resource "aws_launch_template" "workers" {
      ~ default_version         = 3 -> (known after apply)
      + description             = "EKS Managed Node Group custom LT for acme-stage-general"
      - ebs_optimized           = "true" -> null
        id                      = "lt-0b296712f77a5062f"
      ~ latest_version          = 3 -> (known after apply)
        name                    = "acme-stage-general20210713172835067400000004"
        tags                    = {
            "AutoSnapshot" = "true"
            "Env"          = "stage"
        }
        # (8 unchanged attributes hidden)

      ~ block_device_mappings {
            # (1 unchanged attribute hidden)

          ~ ebs {
              - encrypted             = "true" -> null
                # (5 unchanged attributes hidden)
            }
        }



        # (4 unchanged blocks hidden)
    }
```

**Comment by alzabo** [comment]
@nodesocket yeah. I think you'd have to supply your own launch template with the current released versions of this module without this patch or similar.

**Comment by nodesocket** [comment]
@alzabo is there anyway to get EBS support natively pushed and deployed? I'd be willing to sponsor this work. Need to deploy a handful more of clusters, and the one I already deployed is complaining because I manually modified the launch template in AWS web console. Terraform wants to undo those changes when I `plan` and `apply`.

**Comment by nodesocket** [comment]
WIlling to sweeten the pot. How's a bounty of $50 @alzabo @ antonbabenko to get this merged and deployed?

**Comment by LukaszRacon** [comment]
Define launch template outside of this module to have full control:
https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/examples/launch_templates_with_managed_node_groups/launchtemplate.tf

**Comment by nodesocket** [comment]
@LukaszRacon I'd really prefer not to do that just to flip EBS optimized on. Everything else is fine as is.

**Comment by nodesocket** [comment]
@antonbabenko @barryib or @max-rocket-internet any takers on the bounty I am offering to get this tested, merged, and deployed?

**Comment by antonbabenko** [comment]
@nodesocket I will be able to do it if @barryib can't do it by Monday 23rd of August. I short-list this issue on my todo list.

**Comment by nodesocket** [comment]
@antonbabenko fantastic. Where should I send the $50? Is this right? https://www.paypal.me/antonbabenko

**Comment by antonbabenko** [comment]
Here we go! 🎉 

[v17.2.0](https://github.com/terraform-aws-modules/terraform-aws-eks/releases/v17.2.0) has been just released.

**Pull request merged**
