### PR TITLE
New Release v6.0.0

### PR DESCRIPTION
**Pull request by max-rocket-internet**
⚠ A couple of significant breaking changes in this release ⚠

https://github.com/terraform-aws-modules/terraform-aws-eks/pull/468
https://github.com/terraform-aws-modules/terraform-aws-eks/pull/424

Resolves https://github.com/terraform-aws-modules/terraform-aws-eks/issues/512

### CODE REVIEW

**Comment by jjshanks** [comment]
I get this error when running plan against my EKS

```
Terraform v0.12.7
+ provider.aws v2.22.0
+ provider.kubernetes v1.8.1
```

```
Error: Unsupported attribute

  on .terraform/modules/eks/outputs.tf line 48, in output "cluster_oidc_issuer_url":
  48:   value       = aws_eks_cluster.this.identity.0.oidc.0.issuer

This object has no argument, nested block, or exported attribute named
"identity".
```

**Comment by jjshanks** [comment]
map_users also breaks but that seems expected given https://github.com/terraform-aws-modules/terraform-aws-eks/pull/424

**Comment by max-rocket-internet** [comment]
> map_users also breaks but that seems expected

Yep. You need to adjust a variable.

> I get this error when running plan against my EKS

Thanks! I've added requirement for the latest AWS provider that includes the `oidc` output.

Can you retest? `source = "git::https://github.com/max-rocket-internet/terraform-aws-eks.git//?ref=f4762acafcef994f7ad8d36ecfbaa8547ff61fae"`

**Comment by jjshanks** [comment]
Updated my map_users to the new way and used that version. Plan output was

* Added k8s.io/cluster/<name> to ASG
* Added tag Environment = <name> to IAM worker role
* Worker launch config updated
* config_map_aws_auth updated so all values in quotes
* module.eks.random_pet.workers

**Comment by 2tim** [comment]
> I get this error when running plan against my EKS
> 
> ```
> Terraform v0.12.7
> + provider.aws v2.22.0
> + provider.kubernetes v1.8.1
> ```
> 
> ```
> Error: Unsupported attribute
> 
>   on .terraform/modules/eks/outputs.tf line 48, in output "cluster_oidc_issuer_url":
>   48:   value       = aws_eks_cluster.this.identity.0.oidc.0.issuer
> 
> This object has no argument, nested block, or exported attribute named
> "identity".
> ```

Same here trying to upgrade existing cluster using latest module commit above from version 5.1.0

**Comment by barryib** [comment]
FWI the EKS identity attribute has been added in the AWS provider v2.28.0 https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md#2280-september-12-2019

**Comment by 2tim** [comment]
Thanks, just stumbled on that.

**Comment by max-rocket-internet** [comment]
Thanks for the effort @jjshanks! I think that all looks good and as expected.

**Comment by Vlaaaaaaad** [comment]
I am trying to update a 1.12 cluster to 1.13 using this module: 
- bumped the module from `v5.0.0` to `v6.0.0` 
- bumped the EKS version from 1.12 to 1.13

I created a cluster with the old `v5.0.0` version using Kubernetes 1.12 and I am trying to upgrade to the `v6.0.0` version and to 1.13 by doing a `tf apply` -- that's where I get an error regarding the `cluster_oidc_issuer_url`:
```
Error: Invalid index

  on .terraform/modules/k8s.eks/outputs.tf line 48, in output "cluster_oidc_issuer_url":
  48:   value       = aws_eks_cluster.this.identity.0.oidc.0.issuer
    |----------------
    | aws_eks_cluster.this.identity is empty list of object

The given key does not identify an element in this collection value.
```

I seem to be using the latest version of the AWS provider:
```
tf version          
Terraform v0.12.9
+ provider.archive v1.2.2
+ provider.aws v2.28.1
+ provider.kubernetes v1.9.0
+ provider.local v1.3.0
+ provider.null v2.1.2
+ provider.random v2.2.0
+ provider.template v2.1.2
```

I think that since this is an EKS 1.12 cluster there's no `identity` so things get weird. There is a note about this output not being available: [_Only available on Kubernetes version 1.13 and 1.14 clusters created or upgraded on or after September 3, 2019._](https://github.com/terraform-providers/terraform-provider-aws/pull/10006/files#diff-532b4f3d2aaf4ffb0454cf88a8023872R28)

Any ideas? I guess I could upgrade to 1.13 first and then bump the module version.
Should I create an issue for this?

**Comment by Vlaaaaaaad** [comment]
I can confirm the 2-step upgrade works:
- using the module at `v5.0.0` upgrade cluster from 1.12 to 1.13
- upgrade module from `v5.0.0` to `v6.0.0`

**Comment by max-rocket-internet** [comment]
Hmmm strange. So not all clusters have this attribute yet.

> I can confirm the 2-step upgrade works

OK makes sense, thanks for testing! Will be annoying for some users though...

**Comment by bmcstdio** [comment]
@max-rocket-internet @Vlaaaaaaad I have an 1.13 cluster (created before that date, though), and I am facing the same issue. I am going to attempt the upgrade to 1.14 before bumping to 6.0.0 and report back.

**Comment by Vlaaaaaaad** [comment]
The 1.12 cluster I tested on was created today for this specific test so looks like this will affect:
- all 1.12 clusters
- 1.13 clusters created before September 3, 2019 -- I guess AWS may be doing a rolling update of those maybe?

**Comment by barryib** [comment]
The provider return an empty map identity (`aws_eks_cluster.this.identity is  {}`) when the EKS cluster doesn't have one https://github.com/terraform-providers/terraform-provider-aws/blob/master/aws/resource_aws_eks_cluster.go#L460. So `aws_eks_cluster.this.identity.0.oidc.0.issuer` won't exists.

We should test `aws_eks_cluster.this.identity` is not empty.

One of these (or all) this should works:

```hcl
output "cluster_oidc_issuer_url" {
  description = "The URL on the EKS cluster OIDC Issuer"
  value       = concat(aws_eks_cluster.this.identity.*.oidc.0.issuer, [""])[0]
}

# Or

output "cluster_oidc_issuer_url" {
  description = "The URL on the EKS cluster OIDC Issuer"
  value       = join(aws_eks_cluster.this.identity.*.oidc.*.issuer, "")
}

# Or

output "cluster_oidc_issuer_url" {
  description = "The URL on the EKS cluster OIDC Issuer"
  value       = length(aws_eks_cluster.this.identity) > 0 ? aws_eks_cluster.this.identity.0.oidc.0.issuer : ""
}
```

I'll send a small PR for this.

@bmcstdio @Vlaaaaaaad Can you please test this ?

**Comment by Vlaaaaaaad** [comment]
@barryib: sure. Gimme a branch name when it's done and I can test it.

**Comment by Vlaaaaaaad** [comment]
For the middle proposal( which looked the best in my opinion) Terraform fails with:
```
Error: Nested splat expression not allowed

On .terraform/modules/eks/outputs.tf line 48: A splat expression (*) cannot be
used inside another attribute-only splat expression.
```

---

The last option which I put in [Vlaaaaaaad/terraform-aws-eks@test-barryib-oidc-12](https://github.com/Vlaaaaaaad/terraform-aws-eks/tree/test-barryib-oidc-12) works on the test case I reported above! 🎉 

@barryib looking forward to your PR!

**Comment by barryib** [comment]
Here is the PR. @Vlaaaaaaad @bmcstdio https://github.com/terraform-aws-modules/terraform-aws-eks/pull/516 can you have a look please ?

**Comment by barryib** [comment]
@anuragkapur This fix is included in https://github.com/terraform-aws-modules/terraform-aws-eks/releases/tag/v6.0.1

**Comment by abdennour** [comment]
Thank you @barryib  . I am now upgrading from 5.1.0 to 6.0.1 .

I see now: 

`Plan: 4 to add, 3 to change, 3 to destroy.`

**Pull request merged**
