### PR TITLE
Add ability to specify a list of additional security groups to attach to

### PR DESCRIPTION
**Pull request by hobbsh**
# PR o'clock

## Description

This addresses #47 - I have been using this in a local fork and noticed there was an open issue for it. Basically, this allows the user to specify a list of additional existing security groups which will merge with `worker_security_group_id` if specified. This might make `worker_security_group_id` unnecessary, although it's assumed that the additional security groups are unaffiliated with the EKS cluster and more for VPC transit to other areas.

Please let me know what you think. 

### Checklist

- [x] `terraform fmt` and `terraform validate` both work from the root and `examples/eks_test_fixture` directories (look in CI for an example)
- [ ] Tests for the changes have been added and passing (for bug fixes/features)
- [ ] Test results are pasted in this PR (in lieu of CI)
- [x] Docs have been updated using `terraform-docs` per `README.md` instructions
- [x] I've added my change to CHANGELOG.md
- [x] Any breaking changes are highlighted above

### CODE REVIEW

**Comment by max-rocket-internet** [comment]
Hey @hobbsh! Thanks for the PR and sorry for the late reply. Can you resolve your conflict? Then I think we can merge.

**Comment by max-rocket-internet** [comment]
I'll defer to @brandoconnor. I think it would be good to have a per worker group SG list and also a list that applies to all work groups (which you have here in this PR). We don't need to tick both things in the same PR though 🙂

**Comment by mr-joshua** [comment]
I believe this would be a valuable feature as implemented to start with.  I currently need this feature for my company.  Anything I can do to help?  My apologies to the team for creating a duplicate issue #110 and nearly duplicate PR #111 related to this same feature. 

Adding the per worker group proved tricky in my PR due to the way that TF currently handles interpolations.

**Comment by hobbsh** [comment]
@mr-joshua How is that different from this PR? I see no functional differences. You basically pulled in the code here into that PR with added tests.

**Comment by mr-joshua** [comment]
@hobbsh the PR I submitted covers both use cases of Issue #47.  #112 in workers.tf line 27 attaches cluster-wide security groups (which is also covered in this PR as you point out).  Extending this pr and also on line 27 is the logic to attach security groups to specific worker group configs via
```
"${compact(split(",",lookup(var.worker_groups[count.index],"additional_security_group_ids","")))
```

**Comment by hobbsh** [comment]
@mr-joshua Ok, I see it now - thanks. I just didn't see a default for that in variables.tf which is probably worth adding.

**Comment by max-rocket-internet** [comment]
I merged the other PR since @mr-joshua was pretty quick at rebasing and also hassling me 🙃

Sorry about how this one eventuated @hobbsh, I don't have much free time but should have noticed there was 2 similar PRs and sorted it immediately.

**Comment by mr-joshua** [comment]
@hobbsh and @max-rocket-internet my apologies

**Comment by hobbsh** [comment]
No problem at all @mr-joshua @max-rocket-internet - I'm a bit bummed but glad it got into master. I also didn't stay on top of this as well as I could have.

**Pull request closed without merging**
