### PR TITLE
docs: Update UPGRADE-18.0.md and provide a diff between before (v17.x) and after (v18.x), making it easier to see differences.

### PR DESCRIPTION
**Pull request by huguesalary**
Provide a diff of before and after, making it easier to see differences.

## Description
Adding a diff visually showing the differences between v17 and v18

## Motivation and Context
Adding a visual diff helps a lot seeing what changed between v17 and v18.

## Breaking Changes
None

## How Has This Been Tested?
This is a text file change, no tests needed

### CODE REVIEW

**Comment by bryantbiggs** [comment]
if you can fix up the PR title we can merge this

**Comment by huguesalary** [comment]
Sure thing, will do now

**Comment by huguesalary** [comment]
@bryantbiggs I believe you meant fixing up my 2nd commit into the first one? If so, all set now.

**Comment by bryantbiggs** [comment]
no no, the actual pull request title - it should be something like `docs: Update UPGRADE-18.0.md to include diff between v17 and v18' `

**Review by bryantbiggs — APPROVED** [review]
@antonbabenko 👍🏽

**Comment by antonbabenko** [comment]
This PR is included in version 18.20.3 :tada:

**Pull request merged**
