### PR TITLE
Re-generate docs with terraform-docs 0.7.0 and bump pre-commit-terraform version

### PR DESCRIPTION
**Pull request by barryib**
1. Re-geneate docs with the latest version of terraform-docs [0.7.0](https://github.com/segmentio/terraform-docs/releases/tag/v0.7.0) to escape underscores (`variable\_with\_underscore`).
Should resolves docs generation issues for https://github.com/terraform-aws-modules/terraform-aws-eks/pull/667 and https://github.com/terraform-aws-modules/terraform-aws-eks/pull/666

1. Update pre-commit-terraform version

### CODE REVIEW

**Comment by dpiddockcmp** [comment]
They've really buggered this up. If you have backticks in the description then the newly added \ get rendered directly.

Input: ``description = "Valid if: `var.a_thing = false`"``

Old output: Valid if: `var.a_thing = false`

New output: Valid if: `var.a\_thing = false`

Module's variables and outputs documentation is inconsistent in formatting anyway. Remove backticks in descriptions? Use quotes instead?

**Comment by barryib** [comment]
Ohh nice catch. I didn't try to render the generated markdown page. I'll try to fixe this.

**Comment by dpiddockcmp** [comment]
There's a `--no-escape` option to the `markdown` subcommand. Not sure if that would make things better or worse. Not that it matters as pre-commit doesn't support passing options to the subcommand.

**Comment by barryib** [comment]
Yes. I was testing that option manually. If it works, I'll send a PR to pre-commit-terraform.

**Comment by barryib** [comment]
I would prefer to use backticks if needed because itThe `--no-escape` seems to work (at least on github). But I don't know if the right choice. There is a discussion about escaping underscores in markdown https://github.com/segmentio/terraform-docs/issues/111.

Opening PR on pre-commit-terraform to add the `--no-escape` option.

**Comment by barryib** [comment]
I opened the following PR https://github.com/antonbabenko/pre-commit-terraform/pull/83 to add (or let us add) `--no-escape` option.

**Comment by barryib** [comment]
@max-rocket-internet @dpiddockcmp could you review please ?

**Pull request merged**
