### PR TITLE
feat: Support additional cluster DNS IPs with Bottlerocket based AMIs

### PR DESCRIPTION
**Pull request by ramseymcgrathfd**
## Description
Adding support for providing multiple cluster ips into the bottlerocket template.
This resolves https://github.com/terraform-aws-modules/terraform-aws-eks/issues/3050

## Motivation and Context
Utilities like node local dns may require multiple cluster-dns-ip values to run properly on bottlerocket. Support in bottle rocket has been available since 1.18 https://github.com/bottlerocket-os/bottlerocket/releases/tag/v1.8.0

## Breaking Changes
No

## How Has This Been Tested?
- [ x] I have updated at least one of the `examples/*` to demonstrate and validate my change(s)
- [ x] I have tested and validated these changes using one or more of the provided `examples/*` projects
- [ x] I have executed `pre-commit run -a` on my pull request
- This has been replicated on existing community-based module in-house

### CODE REVIEW

**Comment by bryantbiggs** [comment]
I don't know that we will be accepting this change:
1. The EKS CoreDNS addon now supports autoscaling so is node local DNS still needed?
2. I believe you can already pass this value yourself through user data which means we don't have to bake this weird/funky logic into the module:

```hcl
  bootstrap_extra_args = <<-EOT
      [settings.host-containers.admin]
      "cluster-dns-ip" = ["172.21.0.10", "169.254.20.10"]
   EOT
 ```

**Comment by bryantbiggs** [comment]
eh, scratch that. we set the IP here in this module. one sec

**Comment by ramseymcgrathfd** [comment]
> eh, scratch that. we set the IP here in this module. one sec
yeah its hard-coded to a single ip. Pulling that out completely would also work, users can generate it themselves as an extra arg for the template

**Comment by ramseymcgrathfd** [comment]
> I don't know that we will be accepting this change:
> 
>     1. The EKS CoreDNS addon now supports autoscaling so is node local DNS still needed?
> 
>     2. I believe you can already pass this value yourself through user data which means we don't have to bake this weird/funky logic into the module:
> 
> 
> ```terraform
>   bootstrap_extra_args = <<-EOT
>       [settings.kubernetes]
>       "cluster-dns-ip" = ["172.21.0.10", "169.254.20.10"]
>    EOT
> ```

**Comment by ramseymcgrathfd** [comment]
Sorry, closed by accident

**Review by ramseymcgrathfd — COMMENTED** [review]
:+1:  :+1:

**Review by bryantbiggs — APPROVED** [review]

**Comment by antonbabenko** [comment]
This PR is included in version 20.12.0 :tada:

**Pull request merged**
