### PR TITLE
improvement: Make the `cpu_credits` optional for workers launch template

### PR DESCRIPTION
**Pull request by gillg**
# PR o'clock

## Description

If you choose non bustable families in your template (c5 for example...) and you no remove `credit_specification` section, ASG can't start any instance.
Now you can set module `cpu_credits` option to null to made it fonctionnal.

### Checklist

- [x] CI tests are passing

### CODE REVIEW

**Comment by barryib** [comment]
Thanks @gillg for opening this PR. I was wondering if setting the `cpu_credit` to null doesn't work without your change ?

**Comment by gillg** [comment]
Hi @barryib I tried it but it's an invalid value for aws provider API.
So the solution is to remove it

**Review by barryib — CHANGES_REQUESTED** [review]

**Comment by barryib** [comment]
> Hi @barryib I tried it but it's an invalid value for aws provider API.
> So the solution is to remove it

Ok. Good to know. I just added one comment for the coding style. Just resolves that and we're good to go ^^.

**Comment by barryib** [comment]
Please rebase your branch to fix the CI.

**Comment by gillg** [comment]
Everything is ok !

**Review by barryib — APPROVED** [review]
Thanks @gillg for your contribution.

**Pull request merged**
