### PR TITLE
feat: Add kubernetes standard labels to avoid manual mistakes on the managed `aws-auth` configmap

### PR DESCRIPTION
**Pull request by gillg**
## Description

Add labels to avoid manual mistakes on managed configmap. It adds 2 labels :

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/managed-by: Terraform
    terraform.io/module: terraform-aws-modules.eks.aws
  name: aws-auth
  namespace: kube-system
data:
  mapAccounts: |
    []
  mapRoles: |
    ........
  mapUsers: |
    []
```

By this way and "standard" managed-by label, we know this file is provided and enforced by terraform. You should not edit it manualy.

### Checklist

- [X] CI tests are passing
- [NC] README.md has been updated after any changes to variables and outputs. See https://github.com/terraform-aws-modules/terraform-aws-eks/#doc-generation

### CODE REVIEW

**Comment by daroga0002** [comment]
@gillg  CI is failing as you must change PR titlle as per https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/.github/CONTRIBUTING.md#semantic-pull-requests

I belive this will be `improvment:` so add this on beginning of tittle.

**Review by barryib — APPROVED** [review]

**Review by barryib — CHANGES_REQUESTED** [review]
@gillg can you please rebase your branch from master and re-generate the terraform docs to fix the CI.

**Comment by gillg** [comment]
Everything is OK

**Review by barryib — APPROVED** [review]
Thanks @gillg for your contribution.

**Pull request merged**
