### PR TITLE
docs: Include ref to addon naming and config documentation 

### LINKED ISSUE #3008: Doc improvement for cluster_addons
## Is your request related to a new offering from AWS?
Is this functionality available in the [AWS provider for Terraform](https://registry.terraform.io/providers/hashicorp/aws/latest/docs)? See [CHANGELOG.md](https://github.com/hashicorp/terraform-provider-aws/blob/main/CHANGELOG.md), too.
  - No 🛑: please wait to file a request until the functionality is avaialble in the AWS provider
  - Yes ✅: please list the AWS provider version which introduced this functionality

## Is your request related to a problem? Please describe.
I have been working on a project to provision EKS with Add-ons using the module.
While configuring `cluster_addons`, I found it is not easy to find the accepted plugin names list, I did some searching and testing and finally understand it is the Add-ons name defined in this [AWS Doc](https://docs.aws.amazon.com/eks/latest/userguide/eks-add-ons.html)

## Describe the solution you'd like.
I think it would be great to add reference to this doc, so that others can know where to find the plugin name and supply to the `cluster_addons`

## Describe alternatives you've considered.
NA

## Additional context
NA

### PR DESCRIPTION
**Pull request by gillcaleb**
## Description
Includes a reference to AWS documentation for EKS Cluster addon names and configuration details. 

I'm happy to write a more in-depth description with examples but I wasn't sure of the best place to do so, so I went with the simplest solution. Feel free to let me know if there's a more reasonable place for this to live. 

## Motivation and Context
Assists operators in more easily discerning the precise addon names to include in their modules. 
Closes #3008 

## Breaking Changes
No

## How Has This Been Tested?
- [ ] I have updated at least one of the `examples/*` to demonstrate and validate my change(s)
- [ ] I have tested and validated these changes using one or more of the provided `examples/*` projects

- [x] I have executed `pre-commit run -a` on my pull request

### CODE REVIEW

**Comment by bryantbiggs** [comment]
I'm curious to know more about why you think this will be helpful to users - specifically, is a doc comment within the source code is providing the necessary value? Conversely, as a user - how am I thinking about finding this information - am I doing a google search or ?

**Comment by stavvy-cgill** [comment]
Great question. The ultimate aim in my view is to provide the precise names of the addons to be included in the map. In my experience, when first starting to fiddle with addons it's not immediately apparent what the specific map key should be (e.g. `Mountpoint for Amazon S3 CSI Driver` -> `aws-mountpoint-s3-csi-driver`)

The line comment on the resource itself was the simplest way I could think to inject the relevant doc into the code base. The challenge with that particular doc is that the actual information (the names of the addons) is embedded in a dropdown menus for each addon, so it takes a bit of extra digging to get to the salient info. It's also not apparent from reading that doc that the AWS name mentioned there will be the exact same name that the Terraform ingests (it takes some cross referencing of the existing examples). Granted, this is all of relatively minor concern but including a ref might be a helpful reassurance that the information is contained in the page and translates to the name they should use. 

That being said, I'm also more than happy to put in some more robust documentation or examples that obviate the need to seek out external resources to begin with. I'm thinking a brief explanation with an example body along the lines of:

```
cluster_addons = {
    amazon-cloudwatch-observability = {
      most_recent = true
    }
    aws-ebs-csi-driver = {
      most_recent = true
    }
    aws-efs-csi-driver = {
      most_recent = true
    }
    aws-mountpoint-s3-csi-driver  = {
      most_recent = true
    }
   coredns = {
      most_recent = true
    }
   eks-pod-identity-agent =  = {
      most_recent = true
    }
   kube-proxy = {
      most_recent = true
    }
   snapshot-controller = {
      most_recent = true
    }
   vpc-cni = {
      most_recent = true
    }
  }
```
If that's of interest to the community I could put together an `addons.md` in the docs section.

**Comment by bryantbiggs** [comment]
I think for these things, the best source of truth is the API - `aws eks describe-addon-versions --query 'addons[*].addonName'`

```
[
    "vpc-cni",
    "upwind-security_upwind-operator",
    "upbound_universal-crossplane",
    "tetrate-io_istio-distro",
    "teleport_teleport",
    "stormforge_optimize-live",
    "splunk_splunk-otel-collector-chart",
    "solo-io_istio-distro",
    "solo-io_gloo-mesh-starter-pack",
    "solarwinds_swo-k8s-collector-addon",
    "snapshot-controller",
    "rafay-systems_rafay-operator",
    "new-relic_kubernetes-operator",
    "netapp_trident-operator",
    "leaksignal_leakagent",
    "kubecost_kubecost",
    "kube-proxy",
    "kong_konnect-ri",
    "kasten_k10",
    "haproxy-technologies_kubernetes-ingress-ee",
    "groundcover_agent",
    "grafana-labs_kubernetes-monitoring",
    "factorhouse_kpow",
    "eks-pod-identity-agent",
    "dynatrace_dynatrace-operator",
    "datree_engine-pro",
    "datadog_operator",
    "cribl_cribledge",
    "coredns",
    "cisco_cisco-cloud-observability-operators",
    "cisco_cisco-cloud-observability-collectors",
    "calyptia_fluent-bit",
    "aws-mountpoint-s3-csi-driver",
    "aws-guardduty-agent",
    "aws-efs-csi-driver",
    "aws-ebs-csi-driver",
    "amazon-cloudwatch-observability",
    "akuity_agent",
    "adot",
    "accuknox_kubearmor"
]
```

**Comment by gillcaleb** [comment]
Makes sense. I've refactored it to add this info as a an entry to the FAQ. Personally I feel like this would have been helpful info when I was first getting started but if it is deemed to be redundant or of limited value then feel free to close out this PR. 

I also removed a reference to deploying Windows nodes in the FAQ which as far as I could tell did not have a corresponding entry.

**Review by bryantbiggs — APPROVED** [review]

**Comment by antonbabenko** [comment]
This PR is included in version 20.12.0 :tada:

**Comment by FernandoMiguel** [comment]
is `snapshot-controller` something that is recommended to install now?

**Pull request merged**
