### PR TITLE
chore: "Desirec" misspelling fix

### PR DESCRIPTION
**Pull request by okgolove**
# PR o'clock

## Description

Just a simple misspelling fix

### Checklist

- [x] README.md has been updated after any changes to variables and outputs. See https://github.com/terraform-aws-modules/terraform-aws-eks/#doc-generation

### CODE REVIEW

**Review by daroga0002 — APPROVED** [review]

**Comment by okgolove** [comment]
Hooray, the most valuable contribution in my life 😂

**Comment by daroga0002** [comment]
@barryib  can you merge it?

**Review by bryantbiggs — APPROVED** [review]
@antonbabenko / @barryib 👍🏼

**Comment by antonbabenko** [comment]
@okgolove Your contributions are awesome! This one is not an exception :)

**Pull request merged**
