### PR TITLE
fix: Possible fix for issue #2006

### PR DESCRIPTION
**Pull request by pcheung-sfdc**
## Description
see issue #2006 

## Motivation and Context
see issue #2006 

## Breaking Changes
no breaking changes

## How Has This Been Tested?
- [x ] I have tested and validated these changes using one or more of the provided `examples/*` projects
- Also tested on my own module using this eks module

### CODE REVIEW

**Comment by bryantbiggs** [comment]
hi @pcheung-sfdc - I think there was a little misunderstanding. What I was suggesting in the issue was to use `cluster_tags` to solve your issue. So if you are setting a global name tag like:

```hcl
module "eks" {
  name = var.cluster_name
	
  tags = {
    Name = "foo"
  }
}
```

You should be able to resolve your issue with:
```hcl
module "eks" {
  name = var.cluster_name
	
  tags = {
    Name = "foo"
  }
  
  cluster_tags = {
    Name = var.cluster_name
  }
}
```

**Comment by pcheung-sfdc** [comment]
@bryantbiggs but the name tag is not just the cluster name, it's the security group name. If `var.cluster_tags` is only to be used by the security group then what you propose would make sense, but if `cluster_tags` is used for any other resource, having `Name` be a security group name wouldn't make sense for resources that are not security groups

**Comment by pcheung-sfdc** [comment]
it's not the same name as the cluster name. It's the `cluster-name` and some prefix automatically generated (eks-cluster-sg), as well as a suffix (maybe a timestamp). So if we do what you propose, it would make a generic tag `Name` to represent only a very specific resource, also we have no way of determining what the suffix would be beforehand.

**Comment by bryantbiggs** [comment]
ah, not sure why I thought I saw the name as the cluster name earlier but you are correct. one sec I think I know how to fix/avoid this 
image

**Pull request closed without merging**
