### PR TITLE
feat: Add metadata_options for node_groups

### PR DESCRIPTION
**Pull request by maxbrunet**
# PR o'clock

## Description

Add `metadata_options` in custom `launch_template` for managed node groups.

Useful for: https://docs.aws.amazon.com/eks/latest/userguide/best-practices-security.html

### Checklist

- [x] README.md has been updated after any changes to variables and outputs. See https://github.com/terraform-aws-modules/terraform-aws-eks/#doc-generation

### CODE REVIEW

**Comment by xr0n1ck** [comment]
@maxbrunet are you planning to rebase again?

**Comment by antonbabenko** [comment]
@maxbrunet Please rebase and I will merge it right away.

Sorry that this one take so long, too.

**Comment by maxbrunet** [comment]
Rebased. Thank you @antonbabenko!

**Comment by antonbabenko** [comment]
Here it is! Thanks, @maxbrunet and @xr0n1ck for the work and lengthy discussion.

[v17.18.0](https://github.com/terraform-aws-modules/terraform-aws-eks/releases/v17.18.0) has been just released.

🚀

**Pull request merged**
