### PR TITLE
fix: Correct 'iam_role_user_name_prefix' variable type 'string' -> 'bool'

### PR DESCRIPTION
**Pull request by krrrr38**
Signed-off-by: krrrr38 <k.kaizu38@gmail.com>

## Description
fix iam_role_user_name_prefix type as bool

## Motivation and Context
iam_role_user_name_prefix should be bool

## Breaking Changes
N/A

## How Has This Been Tested?
- [ ] ~~I have updated at least one of the `examples/*` to demonstrate and validate my change(s)~~
- [ ] ~~I have tested and validated these changes using one or more of the provided `examples/*` projects~~

- [x] I have executed `pre-commit run -a` on my pull request

### CODE REVIEW

**Comment by bryantbiggs** [comment]
good catch @krrrr38 ! could you update your PR title to something like `fix: Correct 'iam_role_user_name_prefix' variable type 'string' -> 'bool'`

**Comment by krrrr38** [comment]
@bryantbiggs thanks, updated the title 🙆‍♀️

**Review by bryantbiggs — APPROVED** [review]
thank you @krrrr38 - good to go @antonbabenko 👍🏽

**Comment by antonbabenko** [comment]
This PR is included in version 18.20.1 :tada:

**Pull request merged**
