### PR TITLE
Add ability to pass computed values to cluster_security_group_id and worker_security_group_id

### PR DESCRIPTION
**Pull request by rmakram-ims**
# PR o'clock

## Description

Since we cannot pass computed values to cluster_security_group_id or worker_security_group_id, I specified a cluster_create_security_group and worker_create_security_group.

### Checklist

- [X] `terraform fmt` and `terraform validate` both work from the root and `examples/eks_test_fixture` directories (look in CI for an example)
- [x] Tests for the changes have been added and passing (for bug fixes/features)
- [x] Test results are pasted in this PR (in lieu of CI)
- [X] Docs have been updated using `terraform-docs` per `README.md` instructions
- [X] I've added my change to CHANGELOG.md
- [x] Any breaking changes are highlighted above

### CODE REVIEW

**Comment by max-rocket-internet** [comment]
Hi @rmakram-ims 
Is this to solve the common TF error `value of 'count' cannot be computed`?

**Comment by rmakram-ims** [comment]
Hi @max-rocket-internet,
Yeah, this is to solve the common TF error.

**Comment by rmakram-ims** [comment]
Any update on the status of the review? The build failure is unrelated to the code.

**Comment by max-rocket-internet** [comment]
The reason for the hesitation is that the error `value of 'count' cannot be computed` is super common. You see issues about it in most TF module repos. And many many issues in the main terraform repo.

I think it's already improved in terraform but not released yet but not 100% sure. Here's some relevant issues:
https://github.com/hashicorp/terraform/issues/4149
https://github.com/cloudposse/docs/issues/131

So that leaves us with 2 options:

1. Show how to work around the error. e.g. [here](https://github.com/terraform-aws-modules/terraform-aws-eks/issues/178#issuecomment-432596783). Or for this PR the workaround is just to ensure your security groups are created in terraform before any resources in this module: `terraform apply -target=aws_security_group.xxx && terraform apply`

2. Add workarounds like this PR and https://github.com/terraform-aws-modules/terraform-aws-eks/pull/75 but these make the code very messy and harder to use.

**Comment by rmakram-ims** [comment]
Agreed that option 2 makes the code messy, but option 1 makes the apply phase difficult to generalize and potentially messy as well if there are more than one type of resource you would want to workaround.

**Comment by max-rocket-internet** [comment]
Sorry for the delay. Can you rebase and then we'll merge? Thanks for your patience @rmakram-ims ♥️

**Comment by rmakram-ims** [comment]
no problem. Thanks for the reply.

**Comment by max-rocket-internet** [comment]
Hey sorry @rmakram-ims but you still have a conflict. I'm waiting to merge this PR before making a new release 🙂

**Comment by rmakram-ims** [comment]
@max-rocket-internet thanks for waiting for this PR. I resolved the conflict.

**Pull request merged**
