### PR TITLE
feat: Add `kubernetes.io/cluster/<cluster_name>="owned"` tag to the cluster security group

### PR DESCRIPTION
**Pull request by IvanDechovsky**
…t with worker group

# PR o'clock

## Description

https://github.com/terraform-aws-modules/terraform-aws-eks/issues/1416

### Checklist

- [ ] README.md has been updated after any changes to variables and outputs. See https://github.com/terraform-aws-modules/terraform-aws-eks/#doc-generation

### CODE REVIEW

**Comment by barryib** [comment]
After digging a bit in AWS docs, I found this:

image

It mention "_**One, and only one**, of the security groups associated to your nodes should have the following tag applied._". I don't know if we're not breaking something here.

**Comment by marcelobartsch** [comment]
Issue #1441

**Comment by daroga0002** [comment]
basing on [docs](https://docs.aws.amazon.com/eks/latest/userguide/sec-group-reqs.html) and issue #1441 I think this PR should be closed. I checked and this security group `aws_security_group.cluster` is not assigned directly to workers (only API control plane), but this that never-less we shouldn`t follow practice which is against docs.

@antonbabenko what you think?

**Comment by antonbabenko** [comment]
@daroga0002 I don't have enough understanding of the implications (docs are too long) so I would close this one.

**Comment by daroga0002** [comment]
Closing as proposed approach doesn't follow AWS documentation and EKS requirements.

**Pull request closed without merging**
