### PR TITLE
add ec2:DescribeLaunchTemplateVersions action to worker node iam role

### PR DESCRIPTION
**Pull request by skang0601**
# PR o'clock

## Description

Adds ec2:DescribeLaunchTemplateVersions to worker node IAM role to address scaling up from 0 for launch templates as noted here: https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/cloudprovider/aws/README.md

### Checklist

- [ /] `terraform fmt` and `terraform validate` both work from the root and `examples/eks_test_fixture` directories (look in CI for an example)
- [ ] Tests for the changes have been added and passing (for bug fixes/features)
- [ ] Test results are pasted in this PR (in lieu of CI)
- [ ] I've added my change to CHANGELOG.md
- [ ] Any breaking changes are highlighted above

### CODE REVIEW

**Comment by stefansedich** [comment]
@skang0601 does autoscaler scaling-up from 0 not work without it for you? I am scaling some worker groups up from 0 without having to add this, the docs state that it needs either `autoscaling:DescribeLaunchConfigurations` OR `ec2:DescribeLaunchTemplateVersions` and the former is already applied.

**Comment by brandoconnor** [comment]
Hey @skang0601 -

Small and useful change: I'm 100% on board. Can you resolve the merge conflict? With that I'm happy to merge this in ASAP.

**Comment by skang0601** [comment]
This should be good to go now

**Comment by brandoconnor** [comment]
Thanks again @skang0601 ! Merging in.

**Pull request merged**
