### PR TITLE
fix: Added Deny for CreateLogGroup action in EKS cluster role

### PR DESCRIPTION
**Pull request by haarchri**
Signed-off-by: Christopher Haar <chhaar30@googlemail.com>

# PR o'clock

## Description

cloudwatch log group now gets auto destroyed with new iam policy deny for create log group in eks cluster role

Fixes: #920 

### Checklist

- [x] README.md has been updated after any changes to variables and outputs. See https://github.com/terraform-aws-modules/terraform-aws-eks/#doc-generation

### CODE REVIEW

**Comment by daroga0002** [comment]
@haarchri  please correct tittle of PR to `fix: added deny log group in eks cluster role` as CI will fail.

Also seems you using different version of `terraform-docs` which made some changes in lines 137-147, if possible revert those lines to original.

**Comment by haarchri** [comment]
@daroga0002  rebased and changed readme

**Review by daroga0002 — APPROVED** [review]
@haarchri thank your for your contribution 🎉

**Comment by daroga0002** [comment]
@antonbabenko  lets merge this (I will let you know when we can make release as I still looking into few other PRs)

**Comment by antonbabenko** [comment]
This PR is included in version 17.24.0 :tada:

**Comment by JoelOtter** [comment]
To anyone landing on this confused like I was about whether this breaks compatibility with Fluent Bit: the IAM role you want to attach the CloudWatch policy to is the node role, not the cluster role.

**Pull request merged**
