### PR TITLE
fix: Add missing IMDSv2 metadata restrictions for aws launch config

### PR DESCRIPTION
**Pull request by alialperak**
# Add Metadata Options for Launch Configuration

## Description

This PR resolves issue https://github.com/terraform-aws-modules/terraform-aws-eks/issues/1113

Currently metadata options `metadata_http_endpoint`, `metadata_http_tokens` and `metadata_http_put_response_hop_limit` are supported for `aws_launch_templates` with https://github.com/terraform-aws-modules/terraform-aws-eks/pull/938 but not for `aws_launch_configuration` as it has arrived later to AWS provider on https://github.com/hashicorp/terraform-provider-aws/pull/14637. This PR adds settings for IDMS v2 restrictions to aws_launch_configuration.

### Checklist

- [ ] CI tests are passing
- [x] README.md has been updated after any changes to variables and outputs. See https://github.com/terraform-aws-modules/terraform-aws-eks/#doc-generation

### CODE REVIEW

**Comment by alialperak** [comment]
what happened here? @barryib @wise-Kaas
https://github.com/terraform-aws-modules/terraform-aws-eks/pull/1301

**Comment by wise-Kaas** [comment]
@alialperak looks like I missed this PR and issue, wasn't attentive enough😬 Mine was duplicate of yours and looks like now it has been merged, but isn't part of release yet.

**Comment by barryib** [comment]
Sounds like your change has been merged already. Can we close this PR ?

**Comment by barryib** [comment]
Closing this PR because the requested changes are already merged. Feel free to re-open it if needed.

**Pull request closed without merging**
