### PR TITLE
fix: Default `root_volume_type` must be `gp2`

### PR DESCRIPTION
**Pull request by barryib**
# PR o'clock

## Description

Please explain the changes you made here and link to any relevant issues.

### Checklist

- [ ] README.md has been updated after any changes to variables and outputs. See https://github.com/terraform-aws-modules/terraform-aws-eks/#doc-generation

### CODE REVIEW

**Comment by nauxliu** [comment]
Just curious, why the default must be gp2?

**Comment by barryib** [comment]
> Just curious, why the default must be gp2?

If I remember, it's because it doest support for launch configuration. I'll with gp3 when we'll drop LC support (soon).

**Comment by nauxliu** [comment]
> > Just curious, why the default must be gp2?
> 
> 
> 
> If I remember, it's because launch configuration doesn’t support it. I'll with gp3 when we'll drop LC support (soon).

Thanks for the explanation

**Comment by yalimpop** [comment]
On a global scale this commit causes AWS billing to increase for everyone using this module :)

**Comment by ivandir** [comment]
@barryib Is there plan to support Launch Template instead? See https://forums.aws.amazon.com/thread.jspa?messageID=969349

**Comment by ivandir** [comment]
I agree with @yalimpop this module will become undesirable in the future with only GP2 support.

**Comment by bryantbiggs** [comment]
@ivandir this issue is quite old and the latest version of the module provides support for any EBS type desired

**Pull request merged**
