### PR TITLE
fix: Correct DNS suffix for OIDC provider

### PR DESCRIPTION
**Pull request by xchan**
## Description

This is a supplement fix for
https://github.com/terraform-aws-modules/terraform-aws-eks/issues/1904

## Motivation and Context

This MR is a combined fix for succefully launching Karpenter 0.8.2 on AWS EKS on China Region (cn-northwest-1)

## Breaking Changes

N/A

## How Has This Been Tested?
- [*] I have updated at least one of the `examples/*` to demonstrate and validate my change(s)
- [ ] I have tested and validated these changes using one or more of the provided `examples/*` projects

- [ ] I have executed `pre-commit run -a` on my pull request

AWS EKS version 1.22 + Karpenter 0.8.2 launched succefully with this fix with node scaling test done.

### CODE REVIEW

**Comment by bryantbiggs** [comment]
thank you @xchan - can you update your PR title to something like `fix: Correct DNS suffix for OIDC provider`

**Review by bryantbiggs — APPROVED** [review]
thank you!

**Comment by antonbabenko** [comment]
This PR is included in version 18.20.4 :tada:

**Comment by DmitriyStoyanov** [comment]
I try to migrate cluster from v17.24.0 to v18.29.0 and faced with deployment to AWS China, that error appears:
```
Error: error updating IAM Role (XXXXXXX) assume role policy: MalformedPolicyDocument: Invalid principal in policy: "SERVICE":"eks.amazonaws.com.cn"
│       status code: 400, request id: XXXXXXXX
```

Fixed by adding variable 
cluster_iam_role_dns_suffix = "amazonaws.com"

so looks like in China we have the same principal - "eks.amazonaws.com", but not "eks.amazonaws.com.cn" as currently module tried to create

**Pull request merged**
