### PR TITLE
feat: Updated aws_eks_addon_version

### PR DESCRIPTION
**Pull request by satyamuralidhar**
using output.tf file updated value details to get output of eks addon version

### CODE REVIEW

**Comment by bryantbiggs** [comment]
Hi - why is this output necessary?

**Comment by satyamuralidhar** [comment]
We can identify the add-on version id

**Comment by bryantbiggs** [comment]
right, but for what reason - what is it used for?

**Comment by bryantbiggs** [comment]
closing for now since there is an output already provided where this information can be extracted https://github.com/terraform-aws-modules/terraform-aws-eks/blob/674ab7b7f2aa5163b3d9dbdafb7cb1ec910cd9de/outputs.tf#L144

**Pull request closed without merging**
