### PR TITLE
fix terraform pre-commit args for terraform-docs

### PR DESCRIPTION
**Pull request by barryib**

### CODE REVIEW

**Comment by barryib** [comment]
@max-rocket-internet which escapements ? Are you talking about backticks ? If yes, so it sounds like terraform-docs 0.8.x solves it.

**Comment by barryib** [comment]
@max-rocket-internet Can I merge this ?

**Comment by max-rocket-internet** [comment]
> Are you talking about backticks ?

I mean the `cluster\_log\_retention\_in\_days` instead of `cluster_log_retention_in_days`

> Can I merge this ?

Sure.

**Comment by barryib** [comment]
> > Are you talking about backticks ?
> 
> I mean the `cluster\_log\_retention\_in\_days` instead of `cluster_log_retention_in_days`

It's ok to have backslashes to escape words. But in terraform-docs 0.8.x, you don't have backslashes for `backticked` words anymore.

**Pull request merged**
