### PR TITLE
docs: Clarify about the `cluster_endpoint_private_access_cidrs` usage

### PR DESCRIPTION
**Pull request by jerryaldrichiii**
# PR o'clock

## Description

This clarifies that `cluster_create_endpoint_private_access_sg_rule` needs to be set to `true` to use `cluster_endpoint_private_access_cidrs`

See: https://github.com/terraform-aws-modules/terraform-aws-eks/blob/65777d0a37791dd1200d478e3bacc4c9a75f24c8/cluster.tf#L52

### Checklist

- [X] CI tests are passing
- [X] README.md has been updated after any changes to variables and outputs. See https://github.com/terraform-aws-modules/terraform-aws-eks/#doc-generation

### CODE REVIEW

**Comment by jerryaldrichiii** [comment]
I'm not sure why `Lint / Docs` is failing...but I feel like it's not related to this change.

Let me know if I need to fix anything.

**Comment by barryib** [comment]
The docs in the readme is autogenerated. So you just need to modify the variable description and run `pre-commit run -a terraform_docs`. See https://github.com/terraform-aws-modules/terraform-aws-eks#doc-generation

**Comment by jerryaldrichiii** [comment]
All better. Bit too much to jump through as an external contributor so I just added it manually.

Some day I may make a `pre-commit` Docker container. Thanks for responding so quickly.

**Comment by barryib** [comment]
@jerryaldrichiii can you please update your branch and resolve conflict on readme ?

**Comment by barryib** [comment]
closing in favor of https://github.com/terraform-aws-modules/terraform-aws-eks/pull/1400

**Pull request closed without merging**
