### PR TITLE
Update LICENSE

### PR DESCRIPTION
**Pull request by pg83**
## Description

After https://github.com/terraform-aws-modules/terraform-aws-eks/commit/fad350d5bf36a7e39aa3840926b4c9968e9f594c
this project can not be considered as Apache 2.0 licenced.

Also we shoul ask https://opensource.org/ if this license now open source license at all.

## Breaking Changes

This project possibly can not be used in other open source software

## How Has This Been Tested?
- [ ] I have tested and validated these changes using one or more of the provided `examples/*` projects

### CODE REVIEW

**Comment by jeremychauvet** [comment]
Hello @pg83 :) 
Could you explain with this project can not be considered as Apache 2.0 licenced anymore ?

I have the same preocupations than you, but cleary not the same skills in licencing 👍🏼

**Comment by gerasiov** [comment]
>Could you explain with this project can not be considered as Apache 2.0 licenced anymore ?

Apache 2.0 license has exact text and meaning. If you add some more requirement to any aspect of software usage (including copying, modification, redistribution) you should not call this Apache 2.0 license to not mislead others.

For example Apache 2.0 licensed software considered free (in terms of FSF/OSI) by the community, but terraform-aws-eks is not free anymore (at least by DFSG or OSI requirements) and could not be included into free distributions.

I should also mention, that the requirement in subject is some sort of virus (as in copyleft licenses, but other way) and this could bring some licensing issues to derived products.

**Comment by pg83** [comment]
> > > Could you explain with this project can not be considered as Apache 2.0 licenced anymore ?
> > 
> > 
> > Apache 2.0 license has exact text and meaning. If you add some more requirement to any aspect of software usage (including copying, modification, redistribution) you should not call this Apache 2.0 license to not mislead others.
> > For example Apache 2.0 licensed software considered free (in terms of FSF/OSI) by the community, but terraform-aws-eks is not free anymore (at least by DFSG or OSI requirements) and could not be included into free distributions.
> > I should also mention, that the requirement in subject is some sort of virus (as in copyleft licenses, but other way) and this could bring some licensing issues to derived products.
> 
> Could you elaborate on why you believe its no longer free?

New terms of this license effectively ban usage of this product by Russian programmers, cause it is illegal in Russia to accept this terms.

And, by 5 and 6 clause of https://opensource.org/osd, this can not be considered as open source license.

**Comment by bryantbiggs** [comment]
> > > > Could you explain with this project can not be considered as Apache 2.0 licenced anymore ?
> > > 
> > > 
> > > Apache 2.0 license has exact text and meaning. If you add some more requirement to any aspect of software usage (including copying, modification, redistribution) you should not call this Apache 2.0 license to not mislead others.
> > > For example Apache 2.0 licensed software considered free (in terms of FSF/OSI) by the community, but terraform-aws-eks is not free anymore (at least by DFSG or OSI requirements) and could not be included into free distributions.
> > > I should also mention, that the requirement in subject is some sort of virus (as in copyleft licenses, but other way) and this could bring some licensing issues to derived products.
> > 
> > 
> > Could you elaborate on why you believe its no longer free?
> 
> New terms of this license effectively ban usage of this product by Russian programmers, cause it is illegal in Russia to accept this terms.
> 
> And, by 5 and 6 clause of [opensource.org/osd](https://opensource.org/osd), this can not be considered as open source license.

I think you are still referring to the terms/wording of the license which I did not refer to - my question was - why is this project still not free for people to use? there are no monetary requirements for consumption, its published in the public domain - so why is this viewed as not "free" anymore?

**Comment by pg83** [comment]
> I think you are still referring to the terms/wording of the license which I did not refer to

Because "free" and "open source" have precise meaning, and new license terms do not comply with them.

**Comment by antonbabenko** [comment]
Let me make it clear.

Russia invaded Ukraine (my homeland, if it is still important) but before there was Crimea, DNR, LNR. If you want to use the source code of this project as well as other `terraform-aws-modules`, you must agree with all the points I have specified in the [additional note for users from Russia and Belarus](https://github.com/terraform-aws-modules/terraform-aws-eks#additional-terms-of-use-for-users-from-russia-and-belarus).

If you are "outside of politics" or any other BS, I recommend you to follow after the Russian Warship that knows the way. 

End of discussion!

Glory to Ukraine! 🇺🇦

**Pull request closed without merging**
