### PR TITLE
feat: Add nitro enclave support for EKS

### PR DESCRIPTION
**Pull request by spkane**
# PR o'clock

## Description

Make it possible to enable nitro enclave support in EKS.

Should resolve (after testing in complete):
Resolves https://github.com/terraform-aws-modules/terraform-aws-eks/issues/1181
Resolves https://github.com/terraform-aws-modules/terraform-aws-eks/issues/1182

### Checklist

- [x] CI tests are passing
- [x] README.md has been updated after any changes to variables and outputs. See https://github.com/terraform-aws-modules/terraform-aws-eks/#doc-generation

### CODE REVIEW

**Comment by spkane** [comment]
This appears to be usable as is. There might be some improvements that can be made but this makes it possible to enable this in a launch template and get nodes with full support for Nitro enclaves.

**Comment by spkane** [comment]
@barryib Who is the right person to review and merge this?

**Review by barryib — APPROVED** [review]

**Comment by barryib** [comment]
Thanks @spkane for your contribution.

**Comment by spkane** [comment]
> Thanks @spkane for your contribution.

And thank you @barryib , for pushing it through. Much appreciated!

**Pull request merged**
