### PR TITLE
fix: Remove wrong `instance_attributes` property  in complete self_managed_node_group example

### PR DESCRIPTION
**Pull request by vkaylee**
## Description

Some properties are put in `instance_attributes` object block. This attribute does not exist
Move the content out
```terraform
instance_attributes = {}
```
## Motivation and Context

It's totally put in the wrong place. Some inside objects can not be recognized.
```terraform
instance_attributes = {
  name = "instance-attributes"

  min_size     = 1
  max_size     = 2
  desired_size = 1

  bootstrap_extra_args = "--kubelet-extra-args '--node-labels=node.kubernetes.io/lifecycle=spot'"

  instance_type = null

  # launch template configuration
  instance_requirements = {
    cpu_manufacturers                           = ["intel"]
    instance_generations                        = ["current", "previous"]
    spot_max_price_percentage_over_lowest_price = 100

    vcpu_count = {
      min = 1
    }

    allowed_instance_types = ["t*", "m*"]
  }

  use_mixed_instances_policy = true
  mixed_instances_policy = {
    instances_distribution = {
      on_demand_base_capacity                  = 0
      on_demand_percentage_above_base_capacity = 0
      on_demand_allocation_strategy            = "lowest-price"
      spot_allocation_strategy                 = "price-capacity-optimized"
    }

    # ASG configuration
    override = [
      {
        instance_requirements = {
          cpu_manufacturers                           = ["intel"]
          instance_generations                        = ["current", "previous"]
          spot_max_price_percentage_over_lowest_price = 100

          vcpu_count = {
            min = 1
          }

          allowed_instance_types = ["t*", "m*"]
        }
      }
    ]
  }
}
```
## Breaking Changes

None
## How Has This Been Tested?
- [x] I have updated at least one of the `examples/*` to demonstrate and validate my change(s)
- [x] I have tested and validated these changes using one or more of the provided `examples/*` projects

- [x] I have executed `pre-commit run -a` on my pull request

### CODE REVIEW

**Comment by bryantbiggs** [comment]
cc @JeremieCharest  ref https://github.com/terraform-aws-modules/terraform-aws-eks/pull/2757

**Comment by JeremieCharest** [comment]
hi @vkaylee, unless I'm mistaking `instance_attributes` is the name of the node group and not a property on the module itself. It's like the other groups in the self_managed_node_group example: efa, complete, mixed. The new node group was to isole the attribute-based scaling configuration from the other ones. I think there's an extra indentation that could have made it harder to read.

Could you run the original example and print the TF output so that I can help to fix the example?

**Comment by JeremieCharest** [comment]
I see the error now: in the original example there's a missing `}` to close the `complete` block. Sorry for that copy-pasta mistake. That and the correct indentation for the instance_attributes block should fix the issue.

**Comment by vkaylee** [comment]
We should have another pull request to fix this issue and close this pull request because it has not been necessary.

**Pull request closed without merging**
