### PR TITLE
Aws auth not being applied to the cluster during the first terraform apply

### PR DESCRIPTION
**Pull request by stijndehaes**
# PR o'clock

## Description

I changed the name of the workers.tf to be 0_workers.tf file. Because of some dependency issues the aws auth configmap was not deployed the first time you executed terraform apply.
The following issue could point to the same behaviour: https://github.com/terraform-aws-modules/terraform-aws-eks/issues/202

### Checklist

- [x] `terraform fmt` and `terraform validate` both work from the root and `examples/eks_test_fixture` directories (look in CI for an example)
- [ ] Tests for the changes have been added and passing (for bug fixes/features)
- [ ] Test results are pasted in this PR (in lieu of CI)
- [x] I've added my change to CHANGELOG.md
- [x] Any breaking changes are highlighted above

### CODE REVIEW

**Comment by max-rocket-internet** [comment]
I don't think this makes any sense. AFAIK Terraform doesn't care what the file names are?

**Comment by stijndehaes** [comment]
Well I have had some problems with the first time that the configmap wasn't applied. I will look into it further. But terraform loads the files alphabetically so if dependencies haven't correctly been calculated this can fix issues.

**Comment by max-rocket-internet** [comment]
OK, let us know how it goes!

Also similar to this issue: https://github.com/terraform-aws-modules/terraform-aws-eks/issues/199

**Comment by marcelloromani** [comment]
FWIW I don't think renaming a tf file is the correct way to ensure a resource is created before others.
Proper dependencies via `depends_on` should be established.

@stijndehaes you say
> Well I have had some problems with the first time that the configmap wasn't applied
this is exactly the same issue I've been having for a few days.
I believe I found the culprit as per #238 

As a quick test I think you could try setting `interpreter` to `/bin/zsh`

**Comment by stijndehaes** [comment]
Well had the same issue today. The configmap wasn't applied, but this time rerunning it didn't apply the configmap. Meaning that the file was generated correctly but not applied, maybe changing the interpreter could fix that. It's kind of hard to debug though as it doesn't happen always. 
Does anybody know why this resource is using a `local-exec` instead of the `terraform-provider-kubernetes` ?

**Comment by marcelloromani** [comment]
@stijndehaes That is exactly the behaviour I noticed while trying to debug this issue.
The reason (as far as I could understand) is that TF doesn't check whether the config map has actually been applied to the cluster (i.e. there's no check of the k8s resource itself). Therefore if the `kubectl apply -f <aws_auth_config_map>` is not executed (as reported in quite a few issues), there's no way TF will ever re-run that `null_resource` on its own.

**Comment by max-rocket-internet** [comment]
I just merged a PR to fix the shell interpreter issue. Also another PR to add another trigger to the configmap update.

Can you retest? As I don't think renaming a file is a normal solution 😅

**Comment by stijndehaes** [comment]
Just had the same error happen with the latest 2.1.0. However it's very hard to debug. But indeed this renaming is not the solution. Will close this PR and try to find a consistent way to reproduce it first.

**Comment by renperez** [comment]
any update on this? just ran into the same issue with the latest eks module. i had to apply the configmap manually in order for my workers to join the cluster

**Comment by max-rocket-internet** [comment]
Please follow in https://github.com/terraform-aws-modules/terraform-aws-eks/issues/420#issuecomment-507470797

**Pull request closed without merging**
