### PR TITLE
feat: Use `gp3` as default as it saves 20% and is more performant

### PR DESCRIPTION
**Pull request by jayzalowitz**
# PR o'clock
Provider has caught up https://github.com/hashicorp/terraform-provider-aws/pull/16652, thanks @ewbankkit 

## Description
AWS now has a cheaper and more performant drive type:
https://aws.amazon.com/about-aws/whats-new/2020/12/introducing-new-amazon-ebs-general-purpose-volumes-gp3/
Re: https://github.com/terraform-aws-modules/terraform-aws-eks/issues/1130
### Checklist

- [] CI tests are passing
- [x] README.md has been updated after any changes to variables and outputs. See https://github.com/terraform-aws-modules/terraform-aws-eks/#doc-generation

### CODE REVIEW

**Comment by jayzalowitz** [comment]
@antonbabenko Any suggestion on getting that pull request linter working?

**Comment by barryib** [comment]
This is a breking change. I will include this in the next major release (It's on his way ^^).

**Review by barryib — APPROVED** [review]

**Comment by barryib** [comment]
I'm going to revert this change, since it breaks launch configuration usage. See https://github.com/terraform-aws-modules/terraform-aws-eks/issues/1205 for more info.

**Comment by marcusramberg** [comment]
Just hit this bug, any chance of a new release with that revert?

**Pull request merged**
