### PR TITLE
feat: Add variable for disabling dynamic outputs

### PR DESCRIPTION
**Pull request by ajax-ryzhyi-r**
## Description

Add `disable_dynamic_outputs` variable for disabling outputs that can cause drifts

## Motivation and Context

We use this module directly from terragrunt, and occasionally, configuration drift occurs due to changes in the `cluster_platform_version` and `cluster_addons` outputs. Since these changes are made on the AWS side, these drifts are false positives. It would be beneficial to have an option to disable them.

363097684-5a6b5e8c-b734-4a35-b473-221a08c8e44b
Screenshot 2024-11-14 at 08 58 50
Screenshot 2024-11-18 at 09 36 43

## Breaking Changes

All changes are backward compatible
## How Has This Been Tested?
- [ ] I have updated at least one of the `examples/*` to demonstrate and validate my change(s)
- [x] I have tested and validated these changes using one or more of the provided `examples/*` projects

- [x] I have executed `pre-commit run -a` on my pull request

### CODE REVIEW

**Comment by bryantbiggs** [comment]
This is not valid - these are computed values and expected to change. Most likely this is a user configuration error

**Comment by ajax-ryzhyi-r** [comment]
> This is not valid - these are computed values and expected to change. Most likely this is a user configuration error

I understand that these values are expected to change, which is why we want to ignore them. As mentioned in the PR description, we're using this module directly from terragrunt, so changes in these outputs cause false-positive drifts.

Any chance of getting this merged?)

**Comment by bryantbiggs** [comment]
> Any chance of getting this merged?)

No - I don't see why this would cause any conflicts. if you don't use these outputs in your implementation, then don't specify them.

**Comment by ajax-ryzhyi-r** [comment]
> > Any chance of getting this merged?)
> 
> No - I don't see why this would cause any conflicts. if you don't use these outputs in your implementation, then don't specify them.

We don't use these outputs but we can't disable them without modifying this module because we're using it directly from terragrunt, which turns this module into the root module

**Comment by bryantbiggs** [comment]
I'm not a terragrunt user but that sounds like a terragrunt issue - @antonbabenko are you familiar with this behavior in terragrunt?

**Comment by antonbabenko** [comment]
I agree that this is not a Terragrunt issue but rather the expected behavior of Terraform (it shows what has changed).

**Pull request closed without merging**
