### PR TITLE
Don't create ingress rule if worker security group exists

### PR DESCRIPTION
**Pull request by andjelx**
Don't create ingress rule if worker security group exists

# PR o'clock

## Description

Disable creation of ingress rule on worker security group if exists

### Checklist

- [x] Change added to CHANGELOG.md. All changes must be added and breaking changes and highlighted
- [ ] CI tests are passing
- [ ] README.md has been updated after any changes to variables and outputs. See https://github.com/terraform-aws-modules/terraform-aws-eks/#doc-generation

### CODE REVIEW

**Comment by andjelx** [comment]
@max-rocket-internet thanks for quick review.
Can u please share the estimated date when next release of the module is planned ?

**Comment by max-rocket-internet** [comment]
@andjelx very soon: https://github.com/terraform-aws-modules/terraform-aws-eks/pull/720

**Comment by ryanooi** [comment]
Hi. Why want to disable it when worker security group exists? the worker security group will need to another step to whitelist cluster security group manually after EKS created.

**Comment by andjelx** [comment]
@ryanooi The idea is: if you have worker security groups already, you should add proper rules as well before provisioning EKS. If you don't have - all will be managed by terraform-aws-eks module.

**Comment by ryanooi** [comment]
> @ryanooi The idea is: if you have worker security groups already, you should add proper rules as well before provisioning EKS. If you don't have - all will be managed by terraform-aws-eks module.

@andjelx I got your idea. My question is how can you get the cluster's security group (to whitelist on worker node security group) before provision EKS? 

Your steps will be:
1) Create worker node security group
2) Provision cluster and cluster security group
3) Whitelist cluster's security group on worker node security group

Previous steps will be:
1) Create worker node security group
2) Provision cluster and the security group will get whitelisted after cluster created.

that's a security group rule resource which is quite standalone. The previous change was aim to reduce 1 step and it's cleaner(Will get clean up when you destroy the cluster). Unless you're saying this EKS module shouldn't touch security group created outside of the module as of Terraform best practice.

**Comment by andjelx** [comment]
@ryanooi 

Actually yes we can have cluster security group and pass it as **cluster_security_group_id**

> Unless you're saying this EKS module shouldn't touch security group created outside of the module as of Terraform best practice.

That was exactly my point.

**Comment by ryanooi** [comment]
> @ryanooi
> 
> Actually yes we can have cluster security group and pass it as **cluster_security_group_id**
> 
> > Unless you're saying this EKS module shouldn't touch security group created outside of the module as of Terraform best practice.
> 
> That was exactly my point.

That's was your assumption that someone/everyone will want the module to manage both security groups or let the module manage both. But OK. I'm fine with it.  Thanks

**Pull request merged**
