### PR TITLE
chore: Fix typo in `nodeadm` examples

### LINKED ISSUE #2985: Typo in Amazon Linux 2023 `nodeadm` examples
There's a typo in the Amazon Linux 2023 `nodeadm` examples that caused me a significant amount of confusion.
`v1alpha` is meant to be `v1alpha1`

---

## Original Description

Trying to create AL2023 EKS Managed Nodes.
Want to use the `nodeadm` to enable graceful shutdown as well as some node labels for workload scheduling.
The EC2 instance starts up, but then cloud-init prints a warning saying `unhandled unknown content-type (application/node.eks.aws` - very similar to #2954 and the node never joins the cluster.

- [x] ✋ I have searched the open/closed issues and my issue is not listed.
May be similar to #2954

## ⚠️ Note

Before you submit an issue, please perform the following first:

1. Remove the local `.terraform` directory (! ONLY if state is stored remotely, which hopefully you are following that best practice!): `rm -rf .terraform/`
2. Re-initialize the project root to pull down modules: `terraform init`
3. Re-attempt your terraform plan or apply and check if the issue still persists

## Versions

- Module version [Required]: `20.8.4`
- Terraform/Tofu and Provider/s version:
```
$ tofu providers --version
OpenTofu v1.6.2
on darwin_arm64
+ provider registry.opentofu.org/cyrilgdn/postgresql v1.22.0
+ provider registry.opentofu.org/datadog/datadog v3.37.0
+ provider registry.opentofu.org/hashicorp/aws v5.40.0
+ provider registry.opentofu.org/hashicorp/cloudinit v2.3.3
+ provider registry.opentofu.org/hashicorp/external v2.3.3
+ provider registry.opentofu.org/hashicorp/helm v2.12.1
+ provider registry.opentofu.org/hashicorp/http v3.4.2
+ provider registry.opentofu.org/hashicorp/kubernetes v2.27.0
+ provider registry.opentofu.org/hashicorp/local v2.4.1
+ provider registry.opentofu.org/hashicorp/null v3.2.2
+ provider registry.opentofu.org/hashicorp/random v3.6.0
+ provider registry.opentofu.org/hashicorp/time v0.10.0
+ provider registry.opentofu.org/hashicorp/tls v4.0.5
+ provider registry.opentofu.org/integrations/github v5.45.0
+ provider registry.opentofu.org/mongodb/mongodbatlas v1.15.1
+ provider registry.opentofu.org/tailscale/tailscale v0.15.0
```

## Reproduction Code [Required]

```terraform
eks_managed_node_group_defaults = {
  ami_type                       = "AL2023_x86_64_STANDARD"
  platform                       = "al2023"
  use_latest_ami_release_version = false

  metadata_options = {
    http_endpoint               = "enabled"
    http_tokens                 = "required"
    http_put_response_hop_limit = 2
  }

  update_config = {
    max_unavailable = 1
  }
}

eks_managed_node_groups = {
  spot = {
    name          = "eks-cluster-spot"
    ami_id        = "ami-04ba0d9025353715f"
    capacity_type = "SPOT"
    subnet_ids    = var.eks_subnet_ids
    min_size      = 0
    max_size      = 10
    desired_size  = 1

    instance_types = [
      "t3a.xlarge",
      "t3.xlarge",
      "t2.xlarge",
      "m3.xlarge",
      "m4.xlarge",
      "m5.xlarge",
      "m5a.xlarge"
    ]

    enable_bootstrap_user_data = true
    cloudinit_pre_nodeadm = [{
      content_type = "application/node.eks.aws"
      content           = <<-EOT
        ---
        apiVersion: node.eks.aws/v1alpha
        kind: NodeConfig
        spec:
          kubelet:
            config:
              shutdownGracePeriod: 5m
              shutdownGracePeriodCriticalPods: 2m
            flags:
              - "--node-labels=node.kubernetes.io/lifecycle=spot,role=spot"
      EOT
    }]
  }
}
```

## Expected behavior

Node should start up and join the EKS cluster with the desired Node Config.

## Actual behavior

Node never joins the EKS cluster

### PR DESCRIPTION
**Pull request by rblaine95**
## Description
* `apiVersion: node.eks.aws/v1alpha` -> `apiVersion: node.eks.aws/v1alpha1`

Closes #2985 

## Motivation and Context

The `nodeadm` examples have a typo (`v1alpha` is meant to be `v1alpha1`)

## Breaking Changes
None

## How Has This Been Tested?
- [x] I have updated at least one of the `examples/*` to demonstrate and validate my change(s)
- [x] I have tested and validated these changes using one or more of the provided `examples/*` projects

- [ ] I have executed `pre-commit run -a` on my pull request

### CODE REVIEW

**Comment by rblaine95** [comment]
The whitespace changes are due to the `trim_trailing_whitespace = true` in `.editorconfig`

**Comment by bryantbiggs** [comment]
> The whitespace changes are due to the trim_trailing_whitespace = true in .editorconfig

what does that mean? the files should be generated from simply running `terraform apply` in the user data example. I just want to minimize the amount of white space changes

**Comment by rblaine95** [comment]
Interesting 🤔 

I ran `tofu apply` in the `examples/user_data` directory to revert the whitespace changes.
Doing a `git diff` shows this:
image

Maybe the Terraform is generating Windows/DOS line ends (`\r\n`) instead of *nix (`\n`) as according to `end_of_line = lf` in the `.editorconfig` 🤔

**Comment by bryantbiggs** [comment]
I can't find whats causing the line ending issues but it seems to be upstream ["somewhere"](https://github.com/hashicorp/terraform/issues/32910). 

we've had this raised recently as well https://github.com/terraform-aws-modules/terraform-aws-eks/pull/2974

so based on the upstream issue linked and one solution, hopefully that will resolve it. I also updated the file extension for the purely MIME multi-part user data to `.txt` since having those as `.sh` doesn't make sense

**Review by bryantbiggs — APPROVED** [review]

**Comment by antonbabenko** [comment]
This PR is included in version 20.8.5 :tada:

**Pull request merged**
