### PR TITLE
feat: Add tags on network interfaces

### LINKED ISSUE #1361: Network interfaces are missing tags
Please add a network interface tag specificiton to inherit parent tags here 

```
tag_specifications {
         resource_type = "network-interface"
         tags =  var.tags merge with defaults
        }
```

https://github.com/terraform-aws-modules/terraform-aws-eks/blob/32f70afe602cc96e89f31e3562bf237d80482a4b/workers_launch_template.tf#L255

### PR DESCRIPTION
**Pull request by alexmnyc**
# PR o'clock

## Description

Resolves #1361

### Checklist

- [x] CI tests are passing
- [x] README.md has been updated after any changes to variables and outputs. See https://github.com/terraform-aws-modules/terraform-aws-eks/#doc-generation

### CODE REVIEW

**Comment by alexmnyc** [comment]
All resources created by the module must be tagged consistently. This PR addresses ENI lack of tags

**Review by barryib — APPROVED** [review]

**Comment by barryib** [comment]
Thanks @alexmnyc for your contribution.

**Comment by alexmnyc** [comment]
@barryib my pleasure

**Comment by jan-ludvik-deltatre** [comment]
Hi, I am getting this. Am I doing something wrong?
```
expected tag_specifications.2.resource_type to be one of [instance volume spot-instances-request elastic-gpu], got network-interface
```

**Comment by barryib** [comment]
> Hi @alexmnyc, I am getting this. Am I doing something wrong?
> 
> ```
> expected tag_specifications.2.resource_type to be one of [instance volume spot-instances-request elastic-gpu], got network-interface
> ```

It sounds like I merged this, and it's not supported 🤦‍♂️

https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_LaunchTemplateTagSpecificationRequest.html
> The type of resource to tag. Currently, the resource types that support tagging on creation are instance and volume.

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/launch_template#tag-specifications
> The type of resource to tag. Valid values are instance, volume, elastic-gpu and spot-instances-request.

**Comment by lisfo4ka** [comment]
But shouldn't CI fail on this before the merge?
```
  tag_specifications {
    resource_type = "network-interface"
```

**Comment by barryib** [comment]
> But shouldn't CI fail on this before the merge?
> 
> ```
>   tag_specifications {
>     resource_type = "network-interface"
> ```

The CI only terraform validate. I also thought that this kind of bug will be catched during that phase, but found that even `terraform plan` don't.

This is a ongoing feature in the terraform-provider-aws. Here the related PR https://github.com/hashicorp/terraform-provider-aws/pull/18033.

Until that PR get merged, I'm reverting this.

**Comment by alexmnyc** [comment]
I see, it seems like aws provider is out of date and doesn't support it. Is that the issue?

**Comment by barryib** [comment]
> I see, it seems like aws provider is out of date and doesn't support it. Is that the issue?

Yes. Please see my previous comment.

For the revert could you review https://github.com/terraform-aws-modules/terraform-aws-eks/pull/1407

**Comment by barryib** [comment]
Reverted in [v17.0.2](https://github.com/terraform-aws-modules/terraform-aws-eks/releases/tag/v17.0.2)

**Comment by barryib** [comment]
@alexmnyc can you please follow https://github.com/hashicorp/terraform-provider-aws/pull/18033 and re-open a PR as soon it get released in the provider ?

Thanks everyone for your help.

**Comment by alexmnyc** [comment]
Thanks @barryib Will do. My bad. One would think it would be a pass through value given the AWS spec

**Pull request merged**
