### PR TITLE
fix: Drop spot-instances-request from tag_specifications

### PR DESCRIPTION
**Pull request by pavlospt**
## Description
`spot-instances-request` is not supported in some regions, so we are dropping that from default `tag_specifications`.

## Motivation and Context
* https://github.com/terraform-aws-modules/terraform-aws-eks/pull/2360#issuecomment-1358168905
* https://github.com/terraform-aws-modules/terraform-aws-eks/pull/2360#issuecomment-1358488428

### CODE REVIEW

**Comment by bryantbiggs** [comment]
so far I have only heard one user report one region (Ireland) - so I am less inclined to drop this one since its not as problematic. do you know what other regions do not support this?

**Comment by lordspacehog** [comment]
It also causes issues if you try to launch node groups without using spot instances at all. much like the Elastic GPU instances it doesn't allow you to specify the tag if you're not launching spot instances.

**Comment by bryantbiggs** [comment]
yes I understand the behavior - that was a bit surprising when it was discovered with the tagging request for GPUs. However, this still appears to be isolated to one region so far (that I can tell - docs are not producing any additional results so far)

**Comment by pavlospt** [comment]
@bryantbiggs even if it is incosistency with just one region, why should it not be fixed? I mean AWS should be supposedly consistent, but since they are not IMO it feels wrong to enforce such a change and possibly be breaking even just this one region!

**Review by bryantbiggs — APPROVED** [review]

**Comment by bryantbiggs** [comment]
`Failed: You cannot specify tags for Spot instances requests if there are no Spot instances requests being created by the request. Launching EC2 instance failed.` - well this is some somewhat surprising behavior so yes, reverting this out and making it an opt in

**Comment by antonbabenko** [comment]
This PR is included in version 19.4.2 :tada:

**Pull request merged**
