### PR TITLE
changed to use a locals var rather then a input var for worker group count

### PR DESCRIPTION
**Pull request by simonmacklin**
# PR o'clock

## Description

This PR replaces the worker_group_count variable with a locals variable that takes the count from the worker group var using the length function.

### Checklist

- [x] `terraform fmt` and `terraform validate` both work from the root and `examples/eks_test_fixture` directories (look in CI for an example)
- [x] Tests for the changes have been added and passing (for bug fixes/features)
- [ ] Test results are pasted in this PR (in lieu of CI)
- [ ] Docs have been updated using `terraform-docs` per `README.md` instructions
- [ ] I've added my change to CHANGELOG.md
- [ ] Any breaking changes are highlighted above

### CODE REVIEW

**Comment by simonmacklin** [comment]
My pull request tests has failed because the tests are passing in the worker_group_count var when I have removed it in the replacement of the local variable.  

I can add in the variable back in with a default count of 0 to get the tests passing again?

I am not sure if there is a valid reason on why we pass in the count separately which will make this PR useless anyhow.  

Many thanks

**Comment by simonmacklin** [comment]
Sorry I had to dash after submitted the PR yesterday and didn't did a chance to look at the tests.  I have updated the test to not pass in the worker_group_count variable now.

**Comment by dpiddockcmp** [comment]
This is a revert of https://github.com/terraform-aws-modules/terraform-aws-eks/pull/75. See https://github.com/terraform-aws-modules/terraform-aws-eks/issues/73 for explanation of this variable.

**Comment by simonmacklin** [comment]
Thanks dpiddockcmp 

I have not had any issues using a local variable with this module.  Maybe what ever bug existed in terraform has been fixed.

I will remove the PR for now.  

Many thanks

**Comment by max-rocket-internet** [comment]
> I have not had any issues using a local variable with this module. Maybe what ever bug existed in terraform has been fixed.

It hasn't: https://github.com/hashicorp/terraform/issues/10857 https://github.com/hashicorp/terraform/issues/17421 https://github.com/hashicorp/terraform/issues/13980

I find I hit this `count` issue regularly but it's hard to reproduce. I think we wait until TF 0.12?

**Comment by max-rocket-internet** [comment]
> I will remove the PR for now.

I think you intended to close this PR so I will close it now.

Feel free to open it again if that's not correct.

**Pull request closed without merging**
