### PR TITLE
feat: Drop random pets from Managed Node Groups

### LINKED ISSUE #1109: Update a launch template of a managed node group without recreating that managed node group
# I have issues with updating a launch template of a Managed Node Group

## I'm submitting a...

* [X] bug report

## What is the current behavior?

Practically any change to a Launch Template will force recreation of a Managed Node Group.

## If this is a bug, how to reproduce? Please include a code sample if relevant.

* Use eg. the examples from https://github.com/terraform-aws-modules/terraform-aws-eks/tree/e4520d2c2e1b1a182d4abb8bdaf032534f5ed89f/examples/launch_templates_with_managed_node_groups

* See concrete examples at the bottom 

* Using node_group `name` instead of `name_prefix` to remove any traces of `random_pet` does not have an effect.

* Run `terraform apply` twice, so that the second run does not show any changes.

* Update any attribute in the Launch Template. For example, do a change in the userdata template or change `block_device_mappings > ebs > volume_size`. 

## What's the expected behavior?

* Changing the Launch Template happens in-place (as it currently does), this works and Launch Template gets a new version number.

* Existing Managed Node Group is updated to the new Launch Template version number:
```
      launch_template_id      = aws_launch_template.ceph_osd.id
      launch_template_version = aws_launch_template.ceph_osd.default_version
```

* Existing Managed Node Group is not replaced with a new resource. Instead the existing MNG is kept. 

* Something causes `ami_type` , `disk_size` and `node_group_name` to change and force a replacement. I have tried setting them explicitly in `node_groups_defaults`, or in the `node_group` but it does not have an effect. I have tried leaving them out - no effect, still trying to recreate the MNG. 

## Related

* https://github.com/terraform-aws-modules/terraform-aws-eks/issues/737 Forced Replacement of launch configurations without changes in code 

## Environment details

* Affected module version: 13.2.0
* OS: MacOS 
* Terraform version: 
```
Terraform v0.13.5
+ provider registry.terraform.io/hashicorp/aws v3.15.0
+ provider registry.terraform.io/hashicorp/kubernetes v1.13.3
+ provider registry.terraform.io/hashicorp/local v1.4.0
+ provider registry.terraform.io/hashicorp/null v2.1.2
+ provider registry.terraform.io/hashicorp/random v3.0.0
+ provider registry.terraform.io/hashicorp/template v2.2.0
```
## Any other relevant info

<details>
<summary>Terraform output</summary>

```

  # module.eks.module.node_groups.aws_eks_node_group.workers["example"] must be replaced
+/- resource "aws_eks_node_group" "workers" {
      ~ ami_type        = "AL2_x86_64" -> (known after apply) # forces replacement
      ~ arn             = "arn:aws:eks:eu-central-1:161325215566:nodegroup/aws-eu-central-1-2/aws-eu-central-1-2-example/62baf003-22ef-a6e1-a4bc-ee8e1eda4d27" -> (known after apply)
        cluster_name    = "aws-eu-central-1-2"
      ~ disk_size       = 0 -> (known after apply) # forces replacement
      ~ id              = "aws-eu-central-1-2:aws-eu-central-1-2-example" -> (known after apply)
        instance_types  = []
      ~ labels          = {} -> (known after apply)
      ~ node_group_name = "aws-eu-central-1-2-example" -> (known after apply) # forces replacement
        node_role_arn   = "arn:aws:iam::161325215566:role/aws-eu-central-1-22020111907234856210000000a"
      ~ release_version = "1.18.9-20201117" -> (known after apply)
      ~ resources       = [
          - {
              - autoscaling_groups              = [
                  - {
                      - name = "eks-62baf003-22ef-a6e1-a4bc-ee8e1eda4d27"
                    },
                ]
              - remote_access_security_group_id = ""
            },
        ] -> (known after apply)
      ~ status          = "ACTIVE" -> (known after apply)
        subnet_ids      = [
            "subnet-0a97ca5e61048b727",
        ]
      ~ tags            = {
          - "CephRole" = "mon"
          - "NodeRole" = "storage"
          - "az"       = "eu-central-1c"
        } -> (known after apply)
      ~ version         = "1.18" -> (known after apply)

      ~ launch_template {
            id      = "lt-0054877e118c06bfc"
          ~ name    = "aws-eu-central-1-2-example" -> (known after apply)
          ~ version = "2" -> (known after apply)
        }

        scaling_config {
            desired_size = 1
            max_size     = 1
            min_size     = 1
        }
    }

  # module.eks.module.node_groups.random_pet.node_groups["example"] must be replaced
+/- resource "random_pet" "node_groups" {
      ~ id        = "capable-serval" -> (known after apply)
      ~ keepers   = {
          - "ami_type"                  = "AL2_x86_64"
          - "disk_size"                 = "0"
          - "iam_role_arn"              = "arn:aws:iam::161325215566:role/aws-eu-central-1-22020111907234856210000000a"
          - "instance_type"             = "t3.large"
          - "key_name"                  = ""
          - "launch_template"           = "lt-0054877e118c06bfc"
          - "node_group_name"           = "aws-eu-central-1-2-example"
          - "source_security_group_ids" = ""
          - "subnet_ids"                = "subnet-0a97ca5e61048b727"
        } -> (known after apply) # forces replacement
        length    = 2
        separator = "-"
    }
```
</details>

<details>
<summary>Node Group</summary>

```
node_groups = {
  example = {
    name             = "${var.cluster_name}-example"
    subnets          = [module.vpc.private_subnets[2]]
    desired_capacity = 1
    max_capacity     = 1
    min_capacity     = 1

    launch_template_id      = aws_launch_template.example.id
    instance_type           = aws_launch_template.example.instance_type
    launch_template_version = aws_launch_template.example.default_version

    additional_tags = {
      NodeRole = "storage"
      az       = "eu-central-1c"
    }
  }
}
```
</details>

<details>
<summary>Launch Template</summary>

```
# https://github.com/terraform-aws-modules/terraform-aws-eks/blob/v13.2.0/examples/launch_templates_with_managed_node_groups/launchtemplate.tf

data "template_file" "launch_template_userdata_mon" {
  template = file("${path.module}/templates/userdata.sh.tpl")

  vars = {
    cluster_name        = var.cluster_name
    endpoint            = module.eks.cluster_endpoint
    cluster_auth_base64 = module.eks.cluster_certificate_authority_data
  }
}

resource "aws_launch_template" "example" {
  name                   = "${var.cluster_name}-example"
  description            = "Example Launch-Template"
  update_default_version = true

  user_data = base64encode(
    data.template_file.launch_template_userdata_mon.rendered
  )

  instance_type = "t3.large"

  block_device_mappings {
    device_name = "/dev/xvda"

    ebs {
      volume_size           = 25
      volume_type           = "gp2"
      delete_on_termination = true
    }
  }

  monitoring {
    enabled = true
  }

  network_interfaces {
    associate_public_ip_address = false
    delete_on_termination       = true
    security_groups             = [module.eks.worker_security_group_id]
  }

  tag_specifications {
    resource_type = "instance"

    tags = {
      NodeRole = "storage"
    }
  }

  tag_specifications {
    resource_type = "volume"

    tags = {
      NodeRole = "storage"
    }
  }

  tags = {
    NodeRole = "storage"
  }

  lifecycle {
    create_before_destroy = true
  }
}

```
</details>

### LINKED ISSUE #1152: EKS Node Group fails to recreate when using launch template, on minor template update
# I have issues (while true, that is separate from this bug report ;) )

## I'm submitting a...

* [ X ] bug report

## What is the current behavior?

After creating an EKS node group with a launch template, updating the template causes a node group already exists failure

## If this is a bug, how to reproduce? Please include a code sample if relevant.

Create an EKS node group with a custom launch template, using custom userdata
```
[...]
  node_groups = { 
    worker = { 
      desired_capacity = 2 
      max_capacity     = 6 
      min_capacity     = 1 
      instance_type    = "r5.xlarge"
      additional_tags  = local.common_tags
      launch_template_id = aws_launch_template.default.id
      launch_template_version = aws_launch_template.default.default_version
    }   
  }
[...]
resource "aws_launch_template" "default" {
  name_prefix            = "${var.cluster_name}"
  description            = "Default Launch-Template for clusters"
  update_default_version = true
  key_name               = data.aws_ssm_parameter.keypair.value
  user_data              = base64encode(replace(data.cloudinit_config.node_group.rendered, "MIMEBOUNDARY", "//"))
  ebs_optimized          = true
  instance_type          = "r5.xlarge"
[...]
```

Update the user data being consumed by the launch template.
On apply, terraform will instruct AWS to update the launch template in place, creating a new version of the template.

tf will also instruct AWS to create a new node_group using the updated launch template version, but will fail with this error:
```
Error: error creating EKS Node Group (uccdev-west:uccdev-west-worker-magnetic-puma): ResourceInUseException: NodeGroup already exists with name uccdev-west-worker-magnetic-puma and cluster name uccdev-west
```

This is caused by the configuration of the random_pet for the node_group, which currently does have the launch template *version* as one of its keepers.

## What's the expected behavior?
The random_pet name should be updated, then a new node group will be created, EKS will migrate all services to the new node group and shut down the old group

## Are you able to fix this problem and submit a PR? Link here if you have already.
In this file: https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/modules/node_groups/random.tf#L20
Add the following as line 21:
```
launch_template_version = lookup(each.value, "launch_template_version", null)
```

## Environment details

* Affected module version: 13.2.1
* OS: MacOS 10.15.7
* Terraform version: v0.14.0

### LINKED ISSUE #1188: Remove modules/node_groups/random.tf completely - it only causes issues
# I have issues

The `random_pet` resource is a nice helper for starting up a new environment quickly. 

However, in a live cluster it will only cause maintenance pain with bad side-effects. 

See https://github.com/terraform-aws-modules/terraform-aws-eks/issues/1109#issuecomment-763450622

## I'm submitting a...

* [X] bug report
* [ ] feature request
* [ ] support request - read the [FAQ](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/docs/faq.md) first!
* [ ] kudos, thank you, warm fuzzy

## What is the current behavior?

The `random_pet` for node_groups is only used for dynamic node_group name. 

However, the mere existence of modules/node_groups/random.tf causes a side-effect. The random_pet will create an unrelated resource `module.eks.module.node_groups.random_pet.node_groups["test-workers"]` which is bound to the node groups. 

As a result, changing any attribute in the Launch Template bound to a Managed Node Group will cause the whole Node Group being recreated. The correct behaviour would be to update the Launch Template in-place and then update Managed Node Group to use the new Launch Template version (which can be a separate action).

## If this is a bug, how to reproduce? Please include a code sample if relevant.

See issue https://github.com/terraform-aws-modules/terraform-aws-eks/issues/1109 for details.

## What's the expected behavior?

Updating a Launch Template must not recreate a Managed Node Group.

Only the Launch Template version should be bound to a Managed Node Group and the Managed Node Group must be updated in-place (not recreated).

## Environment details

* Affected module version: v13.2.1
* OS: Mac OS
* Terraform version: 0.13.x - 0.14.4.

## Any other relevant info

See issue https://github.com/terraform-aws-modules/terraform-aws-eks/issues/1109 for details.

### LINKED ISSUE #1318: Version 15.1.0 upgrade forces node group re-creation, causing production outages
## Description

Version 15.1.0 of this module introduced a breaking change to the configuration of node groups with the move from a single `instance_type` property to a list of `instance_types`.

I understand that being able to optionally pass in a list of `instance_types` is a great feature for some users, but forcing the change on everyone is really a problem. This change causes all existing node groups to be re-created which has the effect of causing a service outage for everyone using this module.

The ability to pass in multiple `instance_types` should be implemented in a way that doesn't force the re-creation of node groups. For example, by retaining the option to pass in a single `instance_type`.

## Versions
$ terraform -version
Terraform v0.15.0
on darwin_amd64
+ provider registry.terraform.io/gavinbunney/kubectl v1.10.0
+ provider registry.terraform.io/hashicorp/aws v3.37.0
+ provider registry.terraform.io/hashicorp/external v2.1.0
+ provider registry.terraform.io/hashicorp/kubernetes v2.1.0
+ provider registry.terraform.io/hashicorp/local v2.1.0
+ provider registry.terraform.io/hashicorp/null v3.1.0
+ provider registry.terraform.io/hashicorp/random v3.1.0
+ provider registry.terraform.io/hashicorp/template v2.2.0
+ provider tf.platforms.nike.com/platforms/cerberus v0.8.1

 - Module: 15.1.0

## Reproduction

1. Start with an existing EKS cluster deployed with this module on version 13.x
2. Upgrade to the latest version of this module.

### PR DESCRIPTION
**Pull request by barryib**
# PR o'clock

## Description

- Resolves #1152
- Resolves #1188 
- Resolves #1318 
- Resolves #1109

BREAKING CHANGES: We now decided to remove `random_pet` resources in Managed Node Groups (MNG). Those were used to recreate MNG if something changed and also simulate the new argument `node_group_name_prefix`. But they were causing a lot of issues. To upgrade the module without recreating your MNG, you will need to explicitly reuse their previous name and set them in your MNG `name` argument. Please see [upgrade docs](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/docs/upgrades.md#upgrade-module-to-v1700-for-managed-node-groups) for more details.

### Checklist

- [ ] CI tests are passing
- [ ] README.md has been updated after any changes to variables and outputs. See https://github.com/terraform-aws-modules/terraform-aws-eks/#doc-generation

### CODE REVIEW

**Comment by barryib** [comment]
cc @ArchiFleKs @daroga0002 could you review this please ?

**Comment by ArchiFleKs** [comment]
LGTM, I think this will prevent a lot of issues :)

**Comment by stevehipwell** [comment]
@daroga0002 I think this is only a change if you've not been providing `name` for the groups? To solve this I expect that you just need to set the `name` key to the dynamic name.

**Comment by daroga0002** [comment]
> @daroga0002 I think this is only a change if you've not been providing `name` for the groups? To solve this I expect that you just need to set the `name` key to the dynamic name.

after introducing this change I believe it will force all group to recreate (because `node_group_name_prefix` will force replacement), so this should be marked as Breaking change.

**Comment by stevehipwell** [comment]
@daroga0002 does the launch templates being re-created actually matter? I don't think that the ASGs will be re-created as we're using `name` there.

**Comment by daroga0002** [comment]
@stevehipwell we are recreating whole `aws_eks_node_group` as we moving from `node_group_name ` to `node_group_name_prefix`.

But let me test it just to ensure

**Comment by barryib** [comment]
> @stevehipwell we are recreating whole `aws_eks_node_group` as we moving from `node_group_name ` to `node_group_name_prefix`.
> 
> But let me test it just to ensure

Yes, I think the node group will be recreated. Should we let users to define a specific name like before ?

**Comment by stevehipwell** [comment]
I missed the move to prefix over name, how come we're doing this?

**Comment by stevehipwell** [comment]
@barryib I'd like to see the ability to specify a name directly.

**Comment by daroga0002** [comment]
> But let me test it just to ensure

Just giving here test result:
```
Terraform will perform the following actions:

  # module.eks.module.node_groups.aws_eks_node_group.workers["example"] must be replaced
+/- resource "aws_eks_node_group" "workers" {
      ~ arn                    = "arn:aws:eks:us-west-2:*******:nodegroup/test-eks-u8D6IkXR/test-eks-u8D6IkXR-example-grand-kitten/12bcc295-5e10-ba79-5b8a-4d1b61bae030" -> (known after apply)
      ~ id                     = "test-eks-u8D6IkXR:test-eks-u8D6IkXR-example-grand-kitten" -> (known after apply)
      ~ node_group_name        = "test-eks-u8D6IkXR-example-grand-kitten" -> (known after apply)
      + node_group_name_prefix = "test-eks-u8D6IkXR-example-" # forces replacement
      ~ release_version        = "1.17.12-20210512" -> (known after apply)
      ~ resources              = [
          - {
              - autoscaling_groups              = [
                  - {
                      - name = "eks-12bcc295-5e10-ba79-5b8a-4d1b61bae030"
                    },
                ]
              - remote_access_security_group_id = ""
            },
        ] -> (known after apply)
      ~ status                 = "ACTIVE" -> (known after apply)
        tags                   = {
            "Environment" = "test"
            "ExtraTag"    = "example"
            "GithubOrg"   = "terraform-aws-modules"
            "GithubRepo"  = "terraform-aws-eks"
        }
      ~ version                = "1.17" -> (known after apply)
        # (9 unchanged attributes hidden)

        # (1 unchanged block hidden)
    }

  # module.eks.module.node_groups.random_pet.node_groups["example"] will be destroyed
  - resource "random_pet" "node_groups" {
      - id        = "grand-kitten" -> null
      - keepers   = {
          - "ami_type"                  = "AL2_x86_64"
          - "capacity_type"             = "SPOT"
          - "disk_size"                 = "50"
          - "iam_role_arn"              = "arn:aws:iam::*******:role/test-eks-u8D6IkXR20210519143621640500000009"
          - "instance_types"            = "m5.large"
          - "key_name"                  = ""
          - "node_group_name"           = "test-eks-u8D6IkXR-example"
          - "source_security_group_ids" = ""
          - "subnet_ids"                = "subnet-0f4e1d832b0b777b8|subnet-024a5e4004c12cf31|subnet-07223e6126567f61c"
        } -> null
      - length    = 2 -> null
      - separator = "-" -> null
    }

Plan: 1 to add, 0 to change, 2 to destroy.
```

**Comment by daroga0002** [comment]
yes, this is original PR, those changes proposed by @barryib will solve this issue and give additional possibility to switch to prefixed names (which from my side is desired feature)

**Comment by jack1902** [comment]
is there a way to extend this so that a `launch_template` is always created? since https://github.com/terraform-aws-modules/terraform-aws-eks/issues/1348 resulted in two node groups not being able to communicate with one another because one used a launch-template defined as part of the module and one didn't (i know EKS created a copy under the hood)

**Comment by barryib** [comment]
@daroga0002 @ArchiFleKs @stevehipwell just updated my PR according to your reviews.

> is there a way to extend this so that a launch_template is always created? since #1348 resulted in two node groups not being able to communicate with one another because one used a launch-template defined as part of the module and one didn't (i know EKS created a copy under the hood)

@jack1902 good point. We can't always create LT, because some users don't need it. But maybe we should create the LT if LT is needed and stop supporting external LT ?

**Comment by jack1902** [comment]
@barryib maybe, (the worker_sg piece really caught me off guard, since by default, the worker_sg is not attached to nodes created unless a launch template is defined)

Might be worth updating the description on the Security Group to reflect this caveat OR like you say, allow people to extend a pre-defined launch template? [Happy to move this to thread since the change in this PR is a decent one, to swap nodes out without having to go through the process of creating a new managed node group through the petname piece]

**Comment by barryib** [comment]
@daroga0002 is this docs enough https://github.com/terraform-aws-modules/terraform-aws-eks/pull/1372/files#diff-2b35cda5da63a0dd7e1834e0063af64826711909facdb8a56fafece345fa24fe ?

**Comment by ArchiFleKs** [comment]
> @barryib maybe, (the worker_sg piece really caught me off guard, since by default, the worker_sg is not attached to nodes created unless a launch template is defined)
> 
> Might be worth updating the description on the Security Group to reflect this caveat OR like you say, allow people to extend a pre-defined launch template? [Happy to move this to thread since the change in this PR is a decent one, to swap nodes out without having to go through the process of creating a new managed node group through the petname piece]

What about https://github.com/terraform-aws-modules/terraform-aws-eks#input_worker_create_cluster_primary_security_group_rules ? I personally always set it and this allow all the different type to worker to communicate together ?

**Comment by fractos-test** [comment]
One thing I noted around this issue is that if you had supplied a name for the node group then the `create_before_destroy=true` lifecycle rule meant the Terraform apply failed if you did something like changing an EC2 instance type. I just wanted to highlight this as I can see that this is potentially an issue here as well.

**Comment by fractos** [comment]
Heh, turned out I was logged in as my test user for the above comment.

**Comment by barryib** [comment]
> One thing I noted around this issue is that, in the previous version, if you had supplied a name for the node group then the `create_before_destroy=true` lifecycle rule meant the Terraform apply failed if you did something like changing an EC2 instance type. I just wanted to highlight this as I can see that this is potentially an issue here as well.

I'm don't use MNG, so don't test this intensively. So if changing something like ami_id will re-create the node group, then we should stick with the name_prefix to avoir node group name collision because of create_before_destroy.

**Comment by fractos** [comment]
> Edit: Just noticed that almost every change in node group will force it's re-creatiom. See https://github.com/hashicorp/terraform-provider-aws/blob/main/aws/resource_aws_eks_node_group.go#L43 :)

yep, exactly. I've had to vend this module and drop the lifecycle rule in my current project because of this.

**Comment by barryib** [comment]
What is the best upgrade path when you're using Managed Node Groups with Terrarform ?

**Comment by stevehipwell** [comment]
@barryib AMI ID is in the launch template and doesn't force node group re-creation but enough arguments that might be changed regularly do so I'm thinking that `name_prefix` with `create_before_destroy=true` would be a better fit. This would also be clearer when names are duplicated which is entirely possible (unlike map keys).

**Comment by stevehipwell** [comment]
@barryib any progress on this?

**Comment by barryib** [comment]
> @barryib any progress on this?

@stevehipwell still working on it. Just wanted to test it more.

**Comment by barryib** [comment]
@ArchiFleKs @daroga0002 @stevehipwell a final review please.

**Review by ArchiFleKs — APPROVED** [review]

**Comment by barryib** [comment]
Thanks everyone for your help on this.

**Comment by philicious** [comment]
for what its worth: I can report TF lets me upgrade from <=14.0.0 to 17.0, w/o having to recreate node-groups ! 
which is why we got stuck below 14 ... and I didnt yet dare to manually patch TF state around...gladly

so thanks for this change ! 

steps to reproduce, might help someone coming here:
- first pin to `version = "<=16.2.0"` and run a "plan", according to https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/docs/upgrades.md#upgrade-module-to-v1700-for-managed-node-groups
- as I was using a custom LT and in there set instance_type, I also had to set `set_instance_types_on_lt = true` on my node_group, so it wouldnt want to recreate
- also add `name = var.node_group_name` and set to the name of existing node-group, as explained in the upgrade doc
- finally set version to 17.0 and plan should NOT want to recreate the node-groups anymore

**Pull request merged**
