### PR TITLE
feat: Manage worker groups launch template as a map

### PR DESCRIPTION
**Pull request by stevehipwell**
# PR o'clock

## Description

This is an idea for a stop-gap until the worker groups are refactored to the sub-module providing state management and a migration path without functional changes.

@barryib is this something that you're interested in or should I close this and wait for the refactor?

### Checklist

- [ ] CI tests are passing
- [ ] README.md has been updated after any changes to variables and outputs. See https://github.com/terraform-aws-modules/terraform-aws-eks/#doc-generation

### CODE REVIEW

**Comment by stevehipwell** [comment]
@barryib if you've got thoughts on a different direction for this please let me know? Being able to maintain the state for un-managed workers in this module is something that'd save me a lot of engineering effort.

My other idea was to suggest adding a `node_groups_unmanaged` (`node_groups` could be renamed to `node_groups_managed`) and implement the `worker_groups_launch_template` behaviour in a module patterned like the node groups module.

**Comment by paulbsch** [comment]
Just throwing in my two cents.  This would be highly beneficial to some of us that often need to add/remove worker groups.

**Comment by stevehipwell** [comment]
@barryib I'm happy to rebase this otherwise feel free to close it if it's not needed/wanted. It would be useful to know what the timeframe for un-managed workers managed by a map is likely to be.

**Comment by stevehipwell** [comment]
I'm closing this due to no maintainer feedback but I'd be happy to help get this capability added into the module.

**Pull request closed without merging**
