### PR TITLE
docs: Update KMS Key Default Policy Description

### LINKED ISSUE #2169: kms_key_enable_default_policy does not default to true
## Description

`var.kms_key_enable_default_policy` in the description and README says it defaults to `true` but it is set to `false`. It's an easy PR fix but wasn't sure which way is the intended desire. Should it be false and fix the documentation or fix the default value?

- [X] ✋ I have searched the open/closed issues and my issue is not listed.

### PR DESCRIPTION
**Pull request by pen-pal**
## Description

Fixes a description of kms_key_enable_default_policy with the default value of false

Closes #2169

### CODE REVIEW

**Comment by bryantbiggs** [comment]
@pen-pal are you able to fix the CI checks? (run `pre-commit run -a`)

**Comment by pen-pal** [comment]
> @pen-pal are you able to fix the CI checks? (run `pre-commit run -a`)

no
can you guide me on that @bryantbiggs

**Comment by MRostanski** [comment]
@pen-pal That's because you only changed the README.md, not the actual variable description (https://github.com/pen-pal/terraform-aws-eks/blob/patch-1/variables.tf#L148) . 
Automatic terraform-docs check is failing because of that.

**Comment by pen-pal** [comment]
pre-commit run -a

**Comment by pen-pal** [comment]
run `pre-commit run -a`

**Comment by pen-pal** [comment]
@bryantbiggs it's ready now.

**Comment by pen-pal** [comment]
> @pen-pal That's because you only changed the README.md, not the actual variable description (https://github.com/pen-pal/terraform-aws-eks/blob/patch-1/variables.tf#L148) . Automatic terraform-docs check is failing because of that.

thank you very much @MRostanski 👍🏽

**Review by bryantbiggs — APPROVED** [review]
Thank you!

**Comment by antonbabenko** [comment]
This PR is included in version 18.27.0 :tada:

**Pull request merged**
