### PR TITLE
fix: Disable "random_pet" when not using "asg_recreate_on_change"

### PR DESCRIPTION
**Pull request by svaranasi-traderev**
# PR o'clock

## Description

Currently, the "random_pet" resource is created regardless of whether the variable 'asg_recreate_on_change' is True or False. It is truly only useful when the `asg_recreate_on_change` flag is set to True. What this does is it unnecessarily recreates this resource whenever a LT is updated. Which is still alright.

The _major issue_ is when LTs are updated - outside of Terraform - the 'random_pet' resource freaks out as the LT version it detects during 'plan' is different from when it applies. 

Example:
```
Error: Provider produced inconsistent final plan

When expanding the plan for module.eks.random_pet.workers_launch_template[3]
to include new values learned so far during apply, provider
"registry.terraform.io/-/random" produced an invalid new value for
.keepers["lt_name"]: was
cty.StringVal("msb-apps-eks-cluster-ZXia-spot20210121180516478100000004-5"),
but now
cty.StringVal("msb-apps-eks-cluster-ZXia-spot20210121180516478100000004-6").

This is a bug in the provider, which should be reported in the provider's own
issue tracker.
```

Since the 'random_pet' resource isn't being used anywhere else but to create the ASGs name when `asg_recreate_on_change` is True, it makes sense to not trigger a new pet if `asg_recreate_on_change` is False.

**Why do we update Launch-Templates behind the scenes (out of Terraform) ?** 
We (will soon) have Lambdas that detect new EKS AMIs, pin them to an environment, update the LTs and refresh the ASG instances on a staggered basis (sandbox first, prod last) over the week. 

### Checklist

- [] CI tests are passing
- [X] README.md has been updated after any changes to variables and outputs. See https://github.com/terraform-aws-modules/terraform-aws-eks/#doc-generation

### CODE REVIEW

**Comment by svaranasi-traderev** [comment]
Unsure what to do about failing "Lint / Docs" check.

**Comment by svaranasi-traderev** [comment]
> Unsure what to do about failing "Lint / Docs" check.

Definitely works locally after bumping pre-commit version to 1.48.0 (latest as of this writing).

`$ pre-commit run --show-diff-on-failure --all-files terraform_docs
Terraform docs...........................................................Passed`

**Comment by svaranasi-traderev** [comment]
What this
```
  keepers = {
    lt_name = lookup(var.worker_groups_launch_template[count.index], "asg_recreate_on_change", local.workers_group_defaults["asg_recreate_on_change"]) ? join(
      "-",
      compact(
        [
          aws_launch_template.workers_launch_template[count.index].name,
          aws_launch_template.workers_launch_template[count.index].latest_version
        ]
      )
    ) : aws_launch_template.workers_launch_template[count.index].name
  }
```
does is:
Check if `asg_recreate_on_change` is set to `True` in either `var.worker_groups_launch_template` or `local.local.workers_group_defaults`. If it is, then the `random_pet` resource also takes the `latest_version` of the LT into account to trigger the `keeper`. 

However, if `asg_recreate_on_change` is `False` or not set, then the `random_pet` resource's keeper will only get triggered when the LT's name is changed. It doesn't care for the LT's version.

Therefore, one can now make changes outside of Terraform to the LTs without having to deploy the entire module, while also being able to run TF against the module without it freaking out.

**Comment by svaranasi-traderev** [comment]
Anyone?

**Comment by svaranasi-traderev** [comment]
Surely, somebody?

**Comment by tr-srij** [comment]
@barryib @brandonjbjelland @max-rocket-internet 👀

**Comment by svaranasi-traderev** [comment]
Still hoping for a review.

**Comment by svaranasi-traderev** [comment]
Continuing to wait..

**Comment by soloradish** [comment]
Cloud Anyone review this PR? It's also provide a workaroud for https://github.com/terraform-aws-modules/terraform-aws-eks/issues/1318

**Comment by barryib** [comment]
We are now introducing instance refresh to address the recreate on change behavior https://github.com/terraform-aws-modules/terraform-aws-eks/pull/1224. What do you think about removing random pets for workers (LC and LT) https://github.com/terraform-aws-modules/terraform-aws-eks/pull/1224#issuecomment-833345950 ?

**Comment by barryib** [comment]
Please see https://github.com/terraform-aws-modules/terraform-aws-eks/pull/1360

**Comment by barryib** [comment]
closing this since, we'll remove random pets to encourage the usage of ASG Instance Refresh. Follow https://github.com/terraform-aws-modules/terraform-aws-eks/pull/1360 for updates.

**Pull request closed without merging**
