### PR TITLE
Fix issue where ConfigMap isn't applied to new cluster

### PR DESCRIPTION
**Pull request by elatt**
If you are trying to recover a cluster that was deleted, the current
code will not re-apply the ConfigMap because it is already rendered so
kubectl command won't get triggered.

This change adds the cluster endpoint (which should be different when
spinning up a new cluster even with the same name) so we will force a
re-render and cause the kubectl command to run.

# PR o'clock

## Description

This should be a simple way to work around the issue that we saw in https://github.com/terraform-aws-modules/terraform-aws-eks/issues/234.

### Checklist

- [x] `terraform fmt` and `terraform validate` both work from the root and `examples/eks_test_fixture` directories (look in CI for an example)
- [ ] Tests for the changes have been added and passing (for bug fixes/features)
- [ ] Test results are pasted in this PR (in lieu of CI)
- [x] I've added my change to CHANGELOG.md
- [ ] ~~Any breaking changes are highlighted above~~

### CODE REVIEW

**Comment by elatt** [comment]
I'm not exactly sure how to write tests for this. The real goal would be to write a test that can detect that when the endpoint of an EKS cluster changes, the config-map will still get applied because this likely means that a new cluster has been created.

**Comment by max-rocket-internet** [comment]
Hi @elatt !
But a change in endpoint means the whole EKS cluster would have to be destroyed and recreated, right? When else does an endpoint change? Am I missing something?

To be clear, you are solving these 2 issues?
https://github.com/terraform-aws-modules/terraform-aws-eks/pull/231
https://github.com/terraform-aws-modules/terraform-aws-eks/issues/199

**Comment by elatt** [comment]
Ah, I also wasn't familiar with the `null_resource` and it seems the more terraform-y way would be to just add another trigger on the endpoint rather than having it be part of the ConfigMap template, I think?

**Comment by max-rocket-internet** [comment]
> it seems the more terraform-y way would be to just add another trigger on the endpoint 

Correct!

Quite an edge case indeed because I think you would have had to delete your cluster outside of TF and then rerun TF to hit this?

Either way, all good! Fix your conflict and we can merge 🙂

**Comment by elatt** [comment]
Yes, the cluster was deleted outside of TF and it was nice to have all our infrastructure checked into git but this bug took as a bit to understand why the new cluster wasn’t coming up correctly. The merge conflicts should be resolved.

**Pull request merged**
