### PR TITLE
feat: Add additional IAM policy to allow cluster role to use KMS key provided for cluster encryption

### LINKED ISSUE #1894: eks_managed_node_groups with irsa enabled fails
## Description

Hi Team, try to create eks cluster based on example with irsa enabling. 
But faced with issue that aws-node didn't starts.

Maybe it is bug, or maybe i did something wrong or missed, could you please look on this?

## Versions

 - Terraform:
1.15
 - Provider(s):
"hashicorp/aws"  >= 4.1.0
"gavinbunney/kubectl" >= 1.13.1
 - Module:
terraform-aws-modules/eks/aws
version = "18.7.2"

### Code Snippet to Reproduce
```
locals {
  oidc_url = replace(module.eks_cluster.cluster_oidc_issuer_url, "https://", "")
}

module "eks_cluster" {
  source  = "terraform-aws-modules/eks/aws"
  version = "18.7.2"

  cluster_name    = var.rancher_cluster_name
  cluster_version = "1.21"

  vpc_id     = module.vpc.vpc_id
  subnet_ids = module.vpc.private_subnets

  cluster_addons = {
    coredns = {
      resolve_conflicts = "OVERWRITE"
    }
    kube-proxy = {}
    vpc-cni = {
      resolve_conflicts        = "OVERWRITE"
      service_account_role_arn = module.vpc_cni_irsa.iam_role_arn
    }
  }

  # Extend cluster security group rules
  cluster_security_group_additional_rules = {
    egress_nodes_ephemeral_ports_tcp = {
      description                = "To node 1025-65535"
      protocol                   = "tcp"
      from_port                  = 1025
      to_port                    = 65535
      type                       = "egress"
      source_node_security_group = true
    }
  }

  # Extend node-to-node security group rules
  node_security_group_additional_rules = {
    ingress_self_all = {
      description = "Node to node all ports/protocols"
      protocol    = "-1"
      from_port   = 0
      to_port     = 0
      type        = "ingress"
      self        = true
    }
    egress_all = {
      description      = "Node all egress"
      protocol         = "-1"
      from_port        = 0
      to_port          = 0
      type             = "egress"
      cidr_blocks      = ["0.0.0.0/0"]
    }
  }

  eks_managed_node_group_defaults = {
    ami_type       = "AL2_x86_64"
    disk_size      = 50
    instance_types = var.asg_instance_types

    # We are using the IRSA created below for permissions
    iam_role_attach_cni_policy = false
  }
  eks_managed_node_groups = {
    default_node_group = {
      create_launch_template = false
      launch_template_name   = ""
    }
  }
}
module "vpc_cni_irsa" {
  source  = "terraform-aws-modules/iam/aws//modules/iam-role-for-service-accounts-eks"
  version = "4.13.0"

  role_name             = join("-", [var.iac_environment_tag, var.rancher_cluster_name, "vpc-cni"])
  attach_vpc_cni_policy = true
  vpc_cni_enable_ipv4   = true

  oidc_providers = {
    main = {
      provider_arn               = module.eks_cluster.oidc_provider_arn
      namespace_service_accounts = ["kube-system:aws-node"]
    }
  }

  tags = {
    Name = "vpc-cni"
  }
}
```

## Expected behavior
All cluster nodes Up and running

## Actual behavior
Cluster nodes in **Not ready** state
```
Warning | Unhealthy | 24 minutes | kubelet | Readiness probe failed: {"level":"info","ts":"2022-02-22T14:43:46.341Z","caller":"/usr/local/go/src/runtime/proc.go:225","msg":"timeout: failed to connect service \":50051\" within 5s"}
-- | -- | -- | -- | --
Warning | Unhealthy | 23 minutes | kubelet | Readiness probe failed: {"level":"info","ts":"2022-02-22T14:43:56.337Z","caller":"/usr/local/go/src/runtime/proc.go:225","msg":"timeout: failed to connect service \":50051\" within 5s"}
Warning | Unhealthy | 23 minutes | kubelet | Readiness probe failed: {"level":"info","ts":"2022-02-22T14:44:06.341Z","caller":"/usr/local/go/src/runtime/proc.go:225","msg":"timeout: failed to connect service \":50051\" within 5s"}
Warning | Unhealthy | 23 minutes | kubelet | Liveness probe failed: {"level":"info","ts":"2022-02-22T14:44:14.728Z","caller":"/usr/local/go/src/runtime/proc.go:225","msg":"timeout: failed to connect service \":50051\" within 5s"}
Warning | Unhealthy | 23 minutes | kubelet | Readiness probe failed: {"level":"info","ts":"2022-02-22T14:44:16.336Z","caller":"/usr/local/go/src/runtime/proc.go:225","msg":"timeout: failed to connect service \":50051\" within 5s"}
Warning | Unhealthy | 23 minutes | kubelet | (combined from similar events): Readiness probe failed: {"level":"info","ts":"2022-02-22T14:58:06.333Z","caller":"/usr/local/go/src/runtime/proc.go:225","msg":"timeout: failed to connect service \":50051\" within 5s"}
Normal | Killing | 23 minutes | kubelet | Container aws-node failed liveness probe, will be restarted
Normal | Pulled | 23 minutes | kubelet | Container image "602401143452.dkr.ecr.us-west-2.amazonaws.com/amazon-k8s-cni:v1.10.1-eksbuild.1" already present on machine
Warning | BackOff | 13 minutes | kubelet | Back-off restarting failed container
```

### LINKED ISSUE #1913: IAM Role missing kms:ListGrants permission
## Description

I noticed that we are getting a huge amount of CloudWatch alarms for AccessDenied, it seems there is a missing permission or perhaps a component is doing something it should not trying to perform kms:ListGrants.

## Versions
 - Terraform: Terraform v0.13.7
 - Module: 17.7.0

## Expected behavior
No more access denied errors

## Actual behavior
Lot's of access denied errors

## Additional context
```
{
  "eventVersion": "1.08",
  "userIdentity": {
    "type": "AssumedRole",
    "principalId": "GROAV5MWD4DMOKAMGZMAU:health-check-session",
    "arn": "arn:aws:sts::111111111111:assumed-role/cluster-production20210330204212700000000002/health-check-session",
    "accountId": "111111111111",
    "accessKeyId": "ASIAV5M2D4DMNQ111111",
    "sessionContext": {
      "sessionIssuer": {
        "type": "Role",
        "principalId": "GROAV5MWD4DMOKAMGZMAU",
        "arn": "arn:aws:iam::111111111111:role/cluster-production20210330204212700000000002",
        "accountId": "111111111111",
        "userName": "cluster-production20210330204212700000000002"
      },
      "webIdFederationData": {},
      "attributes": {
        "creationDate": "2022-03-02T11:43:47Z",
        "mfaAuthenticated": "false"
      }
    },
    "invokedBy": "eks.amazonaws.com"
  },
  "eventTime": "2022-03-02T11:43:47Z",
  "eventSource": "kms.amazonaws.com",
  "eventName": "ListGrants",
  "awsRegion": "sa-east-1",
  "sourceIPAddress": "eks.amazonaws.com",
  "userAgent": "eks.amazonaws.com",
  "errorCode": "AccessDenied",
  "errorMessage": "User: arn:aws:sts::111111111111:assumed-role/cluster-production20210330204212700000000002/health-check-session is not authorized to perform: kms:ListGrants on resource: arn:aws:kms:sa-east-1:111111111111:key/11111111-1111-1111-1111-111111111111 because no resource-based policy allows the kms:ListGrants action",
  "requestParameters": null,
  "responseElements": null,
  "requestID": "e69b0cde-45ec-4978-bcfd-4756da111111",
  "eventID": "b53be6f5-08b0-414e-97ee-7fdb9a111111",
  "readOnly": true,
  "eventType": "AwsApiCall",
  "managementEvent": true,
  "recipientAccountId": "111111111111",
  "eventCategory": "Management"
}

```

### PR DESCRIPTION
**Pull request by bryantbiggs**
## Description
- Add additional IAM policy to allow cluster role to use KMS key provided for cluster encryption
- Fix bug in EKS managed node group example where the IPv6 permissions need to be created on new cluster creation despite the use of IRSA for VPC CNI addon

## Motivation and Context
- Closes #1894
- Closes #1913 

## Breaking Changes
- No

## How Has This Been Tested?
- [x] I have tested and validated these changes using one or more of the provided `examples/*` projects
	- ✅ `complete` example
	- ✅ `eks_managed_node_group` example
	- ✅ `irsa_autoscale_refresh` example

### CODE REVIEW

**Comment by antonbabenko** [comment]
This PR is included in version 18.8.0 :tada:

**Comment by bryantbiggs** [comment]
> Why does eks_addons depend on node groups? [#1915 (files)](https://github.com/terraform-aws-modules/terraform-aws-eks/pull/1915/files#diff-dc46acf24afd63ef8c556b77c126ccc6e578bc87e3aa09a931f33d9bf2532fbbR255)
> 
> It seems like, when using VPC CNI, the addon should be created/setup before node pools are created. Not sure about the other add-ons but seems to make more sense for node pools to depend on addons than the other way around (although I didn't dig in deep enough to see why the dependencies are setup like that in the first place)

@mariadb-nickvenenga - see here https://github.com/terraform-aws-modules/terraform-aws-eks/pull/1840#issuecomment-1030833327

**Comment by youwalther65** [comment]
@antonbabenko @bryantbiggs I have just upgrade a working Terraform eks cluster to 18.8.0 and get this:
╷
│ Error: Invalid index
│
│   on .terraform/modules/eks/main.tf line 226, in resource "aws_iam_role_policy_attachment" "cluster_encryption":
│  226:   role       = aws_iam_role.this[0].name
│     ├────────────────
│     │ aws_iam_role.this is empty tuple
│
│ The given key does not identify an element in this collection value: the collection has no elements.

Any thoughts? Thanks!

**Comment by bryantbiggs** [comment]
@youwalther65 do you have a reproduction of your configs that we can take a look at?

**Comment by bryantbiggs** [comment]
ah, I think I know actually - you are providing your own IAM role for the cluster, you're not using the IAM role created by the module - is that correct @youwalther65 ?

**Comment by youwalther65** [comment]
Yes, exactly

**Comment by darrenfurr** [comment]
@bryantbiggs - same issue here...
```
  create_iam_role                 = false
  iam_role_arn                    = data.aws_iam_role.eks_admin.arn
  iam_role_name                   = data.aws_iam_role.eks_admin.name
```

**Comment by darrenfurr** [comment]
@bryantbiggs - I reverted to 18.7.3 & the plan runs successfully

**Comment by bryantbiggs** [comment]
@youwalther65 / @darrenfurr please let me know if v18.8.1 resolves the issue for you if you get a chance, thank you 🙏🏽

**Comment by darrenfurr** [comment]
@bryantbiggs - 18.8.1 worked successfully. Thanks for the quick fix.

**Comment by youwalther65** [comment]
Same here @bryantbiggs - 18.8.1 worked successfully. Thanks for the quick fix..

**Pull request merged**
