### PR TITLE
fix: worker LT lifecycle problem

### PR DESCRIPTION
**Pull request by jurgenweber**
# PR o'clock

## Description

Fix for https://github.com/terraform-aws-modules/terraform-aws-eks/issues/939

Add the lifecycle to the random_pet resource.

### Checklist

- [x] CI tests are passing
- [ ] README.md has been updated after any changes to variables and outputs. See https://github.com/terraform-aws-modules/terraform-aws-eks/#doc-generation

### CODE REVIEW

**Comment by barryib** [comment]
Is @dpiddockcmp comment ok for you https://github.com/terraform-aws-modules/terraform-aws-eks/issues/939#issuecomment-657247292 ?

**Comment by gauravachatrath** [comment]
May i know the issue is fixed  and help on it ? I removed the plugins and eks provider 12.2.0 and init again and still i am getting the same bug error .

When expanding the plan for module.eks.random_pet.workers_launch_template[0]
to include new values learned so far during apply, provider
"registry.terraform.io/hashicorp/random" changed the planned action from
CreateThenDelete to DeleteThenCreate.

This is a bug in the provider, which should be reported in the provider's own
issue tracker.

**Comment by dpiddockcmp** [comment]
This fix will be released in version 13.0.0 of the module.

**Comment by gauravachatrath** [comment]
Thank you

**Comment by shankar96** [comment]
> This fix will be released in version 13.0.0 of the module.

Can you share timeline around this?
or any particular fix as of now

**Comment by shankar96** [comment]
> This fix will be released in version 13.0.0 of the module.

Whoever is looking for the fix can follow below steps
Fixed by updating terraform version to v13.4
$terraform version # to get the version of current terraform version
# download the latest version of terraform from https://www.terraform.io/downloads.html
$which terraform #to get the place of terraform
/usr/bin/terraform 
# unzip and move the terraform to the above place

**Comment by shankar96** [comment]
> This fix will be released in version 13.0.0 of the module.

for steps you can follow below steps
Fixed by updating terraform version to v13.4
$terraform version # to get the version of current terraform version
 #download the latest version of terraform from https://www.terraform.io/downloads.html
$which terraform #to get the place of terraform
/usr/bin/terraform 
 #unzip and move the terraform to the above place

**Comment by jurgenweber** [comment]
yeah, it seems this was a work around for a tf bug.

**Pull request merged**
