### PR TITLE
feat: Add `node_iam_role_arns` local variable to check for Windows platform on EKS managed nodegroups

### PR DESCRIPTION
**Pull request by aamoctz**
## Description

This change adds additional checks for `platform == "windows"` on both `local.node_iam_role_arns_non_windows` and `local.node_iam_role_arns_windows`.

The additional validation in `local.node_iam_role_arns_windows` ensures that the correct configurations are added to `aws-auth`.

The additiional validation in `local.node_iam_role_arns_non_windows` ensures that terraform does not also create an extra incorrect entry in `aws-auth` for the node group.

To support this change, the eks_managed_node_group module has a new output (`platform`)

## Motivation and Context

Resolves the issue described in this [comment](https://github.com/terraform-aws-modules/terraform-aws-eks/issues/2350#issuecomment-1428624704) from #2350 
## Breaking Changes

No breaking changes found during my testing.

## How Has This Been Tested?
- [] I have updated at least one of the `examples/*` to demonstrate and validate my change(s)
- [x] I have tested and validated these changes using one or more of the provided `examples/*` projects

- [x] I have executed `pre-commit run -a` on my pull request

### CODE REVIEW

**Comment by hp197** [comment]
👍

**Comment by noamgreen** [comment]
can someone approve this :-)

**Comment by hp197** [comment]
bump

**Comment by aamoctz** [comment]
bump

**Comment by mcmagi** [comment]
I would also greatly appreciate a review of this. Thanks!

**Comment by jxn** [comment]
I've nearly submitted this exact same code in a different PR today.  Even with today's master, the changes are the same.  It would be great to get this reviewed and pulled in so managed windows node groups can be functional instances.

**Comment by saedx1** [comment]
Can we please get this reviewed and merged? It's really needed!

**Comment by bryantbiggs** [comment]
how has this been tested and validated?

**Comment by mlschindler** [comment]
+1 this PR would benefit us greatly

**Comment by aamoctz** [comment]
> how has this been tested and validated?

PR was tested using the `eks_managed_node_group` example module, with some modifications to use existing VPC related resources since those are managed elsewhere within my org. I do not have access to a sandbox account so that's the closest I can get.

**Comment by sean-redmond** [comment]
This looks good in some limited testing, given the problems this is currently causing I think it should be pulled in.

**Comment by sankalpkale88** [comment]
+1 Can we please get this merged ?

**Comment by sean-redmond** [comment]
Would be really nice to see this merged.

**Comment by kirillowen** [comment]
+1 Would be great to see this merged.

**Review by bryantbiggs — APPROVED** [review]
To be clear, this won't function the same as AL2 and Bottlerocket nodes (custom launch template and injection of user data) but hopefully it unblocks some folks

**Comment by antonbabenko** [comment]
This PR is included in version 19.16.0 :tada:

**Pull request merged**
