### PR TITLE
feat: Support addon resolve_conflicts on_create/on_update

### PR DESCRIPTION
**Pull request by johanneswuerbach**
## Description

Support the new `resolve_conflicts_on_create` and `resolve_conflicts_on_update` addon properties in addition to keep `resolve_conflicts` support.

The implemented logic:
* If nothing is set, set `resolve_conflicts_on_create=OVERWRITE ` and `resolve_conflicts_on_update=OVERWRITE` (removes the deprecation warning).
* If `resolve_conflicts` is set, forward it to the resource and don't set the `OVERWRITE` defaults (to prevent the property conflict).
* If `resolve_conflicts_on_create` is set forward to the resource
* If `resolve_conflicts_on_update` is set forward to the resource
* If `resolve_conflicts` and `resolve_conflicts_on_*` is set, forward to the resource, but this would result in an error from the aws provider as setting those properties at the same time conflicts.

## Motivation and Context

Fixes https://github.com/terraform-aws-modules/terraform-aws-eks/issues/2635

## Breaking Changes

No, it shouldn't.

## How Has This Been Tested?
- [x] I have updated at least one of the `examples/*` to demonstrate and validate my change(s)
- [x] I have tested and validated these changes using one or more of the provided `examples/*` projects

I've tested different property combinations in `examples/eks_managed_node_group` and check the resulting terraform plan.
- [x] I have executed `pre-commit run -a` on my pull request

### CODE REVIEW

**Comment by bryantbiggs** [comment]
please see https://github.com/terraform-aws-modules/terraform-aws-eks/issues/2635#issuecomment-1572070213

**Comment by johanneswuerbach** [comment]
Thanks for the review @bryantbiggs, but I'm not sure I understand.

This implementation shouldn't be breaking any configuration (everything works as before), but avoids the warning if nothing is configured and allows users to gradually adopt the new properties.

**Comment by bryantbiggs** [comment]
`resolve_conflicts_on_create` and `resolve_conflicts_on_update` are only available starting on v5.0 of the AWS provider - which upgrading to require this minimum is a breaking change for users

**Comment by bryantbiggs** [comment]
apologies - wrong button 😅

**Comment by johanneswuerbach** [comment]
Sorry, I totally missed that this module still supports AWS v4 :-/

**Comment by bryantbiggs** [comment]
we will have v20 coming end of next month, early Dec and this will be resolved then

**Pull request closed without merging**
