### PR TITLE
feat: Add support for tracking latest AMI release version on managed nodegroups

### LINKED ISSUE #2589: Retrieve the latest ami_release_version for managed node groups
## Is your request related to a new offering from AWS?
Is this functionality available in the [AWS provider for Terraform](https://registry.terraform.io/providers/hashicorp/aws/latest/docs)? See [CHANGELOG.md](https://github.com/hashicorp/terraform-provider-aws/blob/main/CHANGELOG.md), too.
  - No 🛑: please wait to file a request until the functionality is avaialble in the AWS provider
  - Yes ✅: please list the AWS provider version which introduced this functionality

Not really.

## Is your request related to a problem? Please describe.
As described in https://github.com/terraform-aws-modules/terraform-aws-eks/issues/2434 , it appears that we can't really managed the version for the AMIs in EKS managed node group. At least, we can't update them from terraform.

While there might be a workaround by using the `ami_id`, this would be considered as custom template.

## Describe the solution you'd like.
Following the closed issue above led me to an other issue opened by @bryantbiggs here -> https://github.com/aws/containers-roadmap/issues/1945.

One of the comment proposed to work around this issue by getting the release_version as a data from SSM: https://github.com/aws/containers-roadmap/issues/1945#issuecomment-1464681858 

Which seems to give the expected value.

## Describe alternatives you've considered.
Update the managed node group through the AWS Console.

### PR DESCRIPTION
**Pull request by bryantbiggs**
## Description
- Add support for tracking latest AMI release version on managed nodegroups

## Motivation and Context
- Resolves #2589
- Reference https://github.com/awslabs/amazon-eks-ami/issues/1597#issuecomment-1973512095

## Breaking Changes
- No

## How Has This Been Tested?
- [x] I have updated at least one of the `examples/*` to demonstrate and validate my change(s)
- [x] I have tested and validated these changes using one or more of the provided `examples/*` projects
- [x] I have executed `pre-commit run -a` on my pull request

### CODE REVIEW

**Comment by bryantbiggs** [comment]
using the logic added here, these are the values returned for the different AMI types supported and K8s versions (for reference):

```json
[
    {
        "ami_type": "AL2023_ARM_64_STANDARD",
        "cluster_version": "1.24",
        "release_version": "1.24.17-20240227"
    },
    {
        "ami_type": "AL2023_ARM_64_STANDARD",
        "cluster_version": "1.25",
        "release_version": "1.25.16-20240227"
    },
    {
        "ami_type": "AL2023_ARM_64_STANDARD",
        "cluster_version": "1.26",
        "release_version": "1.26.12-20240227"
    },
    {
        "ami_type": "AL2023_ARM_64_STANDARD",
        "cluster_version": "1.27",
        "release_version": "1.27.9-20240227"
    },
    {
        "ami_type": "AL2023_ARM_64_STANDARD",
        "cluster_version": "1.28",
        "release_version": "1.28.5-20240227"
    },
    {
        "ami_type": "AL2023_ARM_64_STANDARD",
        "cluster_version": "1.29",
        "release_version": "1.29.0-20240227"
    },
    {
        "ami_type": "AL2023_x86_64_STANDARD",
        "cluster_version": "1.24",
        "release_version": "1.24.17-20240227"
    },
    {
        "ami_type": "AL2023_x86_64_STANDARD",
        "cluster_version": "1.25",
        "release_version": "1.25.16-20240227"
    },
    {
        "ami_type": "AL2023_x86_64_STANDARD",
        "cluster_version": "1.26",
        "release_version": "1.26.12-20240227"
    },
    {
        "ami_type": "AL2023_x86_64_STANDARD",
        "cluster_version": "1.27",
        "release_version": "1.27.9-20240227"
    },
    {
        "ami_type": "AL2023_x86_64_STANDARD",
        "cluster_version": "1.28",
        "release_version": "1.28.5-20240227"
    },
    {
        "ami_type": "AL2023_x86_64_STANDARD",
        "cluster_version": "1.29",
        "release_version": "1.29.0-20240227"
    },
    {
        "ami_type": "AL2_ARM_64",
        "cluster_version": "1.24",
        "release_version": "1.24.17-20240227"
    },
    {
        "ami_type": "AL2_ARM_64",
        "cluster_version": "1.25",
        "release_version": "1.25.16-20240227"
    },
    {
        "ami_type": "AL2_ARM_64",
        "cluster_version": "1.26",
        "release_version": "1.26.12-20240227"
    },
    {
        "ami_type": "AL2_ARM_64",
        "cluster_version": "1.27",
        "release_version": "1.27.9-20240227"
    },
    {
        "ami_type": "AL2_ARM_64",
        "cluster_version": "1.28",
        "release_version": "1.28.5-20240227"
    },
    {
        "ami_type": "AL2_ARM_64",
        "cluster_version": "1.29",
        "release_version": "1.29.0-20240227"
    },
    {
        "ami_type": "AL2_x86_64",
        "cluster_version": "1.24",
        "release_version": "1.24.17-20240227"
    },
    {
        "ami_type": "AL2_x86_64",
        "cluster_version": "1.25",
        "release_version": "1.25.16-20240227"
    },
    {
        "ami_type": "AL2_x86_64",
        "cluster_version": "1.26",
        "release_version": "1.26.12-20240227"
    },
    {
        "ami_type": "AL2_x86_64",
        "cluster_version": "1.27",
        "release_version": "1.27.9-20240227"
    },
    {
        "ami_type": "AL2_x86_64",
        "cluster_version": "1.28",
        "release_version": "1.28.5-20240227"
    },
    {
        "ami_type": "AL2_x86_64",
        "cluster_version": "1.29",
        "release_version": "1.29.0-20240227"
    },
    {
        "ami_type": "AL2_x86_64_GPU",
        "cluster_version": "1.24",
        "release_version": "1.24.17-20240227"
    },
    {
        "ami_type": "AL2_x86_64_GPU",
        "cluster_version": "1.25",
        "release_version": "1.25.16-20240227"
    },
    {
        "ami_type": "AL2_x86_64_GPU",
        "cluster_version": "1.26",
        "release_version": "1.26.12-20240227"
    },
    {
        "ami_type": "AL2_x86_64_GPU",
        "cluster_version": "1.27",
        "release_version": "1.27.9-20240227"
    },
    {
        "ami_type": "AL2_x86_64_GPU",
        "cluster_version": "1.28",
        "release_version": "1.28.5-20240227"
    },
    {
        "ami_type": "AL2_x86_64_GPU",
        "cluster_version": "1.29",
        "release_version": "1.29.0-20240227"
    },
    {
        "ami_type": "BOTTLEROCKET_ARM_64",
        "cluster_version": "1.24",
        "release_version": "1.19.2-29cc92cc"
    },
    {
        "ami_type": "BOTTLEROCKET_ARM_64",
        "cluster_version": "1.25",
        "release_version": "1.19.2-29cc92cc"
    },
    {
        "ami_type": "BOTTLEROCKET_ARM_64",
        "cluster_version": "1.26",
        "release_version": "1.19.2-29cc92cc"
    },
    {
        "ami_type": "BOTTLEROCKET_ARM_64",
        "cluster_version": "1.27",
        "release_version": "1.19.2-29cc92cc"
    },
    {
        "ami_type": "BOTTLEROCKET_ARM_64",
        "cluster_version": "1.28",
        "release_version": "1.19.2-29cc92cc"
    },
    {
        "ami_type": "BOTTLEROCKET_ARM_64",
        "cluster_version": "1.29",
        "release_version": "1.19.2-29cc92cc"
    },
    {
        "ami_type": "BOTTLEROCKET_ARM_64_NVIDIA",
        "cluster_version": "1.24",
        "release_version": "1.19.2-29cc92cc"
    },
    {
        "ami_type": "BOTTLEROCKET_ARM_64_NVIDIA",
        "cluster_version": "1.25",
        "release_version": "1.19.2-29cc92cc"
    },
    {
        "ami_type": "BOTTLEROCKET_ARM_64_NVIDIA",
        "cluster_version": "1.26",
        "release_version": "1.19.2-29cc92cc"
    },
    {
        "ami_type": "BOTTLEROCKET_ARM_64_NVIDIA",
        "cluster_version": "1.27",
        "release_version": "1.19.2-29cc92cc"
    },
    {
        "ami_type": "BOTTLEROCKET_ARM_64_NVIDIA",
        "cluster_version": "1.28",
        "release_version": "1.19.2-29cc92cc"
    },
    {
        "ami_type": "BOTTLEROCKET_ARM_64_NVIDIA",
        "cluster_version": "1.29",
        "release_version": "1.19.2-29cc92cc"
    },
    {
        "ami_type": "BOTTLEROCKET_x86_64",
        "cluster_version": "1.24",
        "release_version": "1.19.2-29cc92cc"
    },
    {
        "ami_type": "BOTTLEROCKET_x86_64",
        "cluster_version": "1.25",
        "release_version": "1.19.2-29cc92cc"
    },
    {
        "ami_type": "BOTTLEROCKET_x86_64",
        "cluster_version": "1.26",
        "release_version": "1.19.2-29cc92cc"
    },
    {
        "ami_type": "BOTTLEROCKET_x86_64",
        "cluster_version": "1.27",
        "release_version": "1.19.2-29cc92cc"
    },
    {
        "ami_type": "BOTTLEROCKET_x86_64",
        "cluster_version": "1.28",
        "release_version": "1.19.2-29cc92cc"
    },
    {
        "ami_type": "BOTTLEROCKET_x86_64",
        "cluster_version": "1.29",
        "release_version": "1.19.2-29cc92cc"
    },
    {
        "ami_type": "BOTTLEROCKET_x86_64_NVIDIA",
        "cluster_version": "1.24",
        "release_version": "1.19.2-29cc92cc"
    },
    {
        "ami_type": "BOTTLEROCKET_x86_64_NVIDIA",
        "cluster_version": "1.25",
        "release_version": "1.19.2-29cc92cc"
    },
    {
        "ami_type": "BOTTLEROCKET_x86_64_NVIDIA",
        "cluster_version": "1.26",
        "release_version": "1.19.2-29cc92cc"
    },
    {
        "ami_type": "BOTTLEROCKET_x86_64_NVIDIA",
        "cluster_version": "1.27",
        "release_version": "1.19.2-29cc92cc"
    },
    {
        "ami_type": "BOTTLEROCKET_x86_64_NVIDIA",
        "cluster_version": "1.28",
        "release_version": "1.19.2-29cc92cc"
    },
    {
        "ami_type": "BOTTLEROCKET_x86_64_NVIDIA",
        "cluster_version": "1.29",
        "release_version": "1.19.2-29cc92cc"
    },
    {
        "ami_type": "WINDOWS_CORE_2019_x86_64",
        "cluster_version": "1.24",
        "release_version": "1.24-2024.02.13"
    },
    {
        "ami_type": "WINDOWS_CORE_2019_x86_64",
        "cluster_version": "1.25",
        "release_version": "1.25-2024.02.13"
    },
    {
        "ami_type": "WINDOWS_CORE_2019_x86_64",
        "cluster_version": "1.26",
        "release_version": "1.26-2024.02.13"
    },
    {
        "ami_type": "WINDOWS_CORE_2019_x86_64",
        "cluster_version": "1.27",
        "release_version": "1.27-2024.02.13"
    },
    {
        "ami_type": "WINDOWS_CORE_2019_x86_64",
        "cluster_version": "1.28",
        "release_version": "1.28-2024.02.13"
    },
    {
        "ami_type": "WINDOWS_CORE_2019_x86_64",
        "cluster_version": "1.29",
        "release_version": "1.29-2024.02.13"
    },
    {
        "ami_type": "WINDOWS_CORE_2022_x86_64",
        "cluster_version": "1.24",
        "release_version": "1.24-2024.02.13"
    },
    {
        "ami_type": "WINDOWS_CORE_2022_x86_64",
        "cluster_version": "1.25",
        "release_version": "1.25-2024.02.13"
    },
    {
        "ami_type": "WINDOWS_CORE_2022_x86_64",
        "cluster_version": "1.26",
        "release_version": "1.26-2024.02.13"
    },
    {
        "ami_type": "WINDOWS_CORE_2022_x86_64",
        "cluster_version": "1.27",
        "release_version": "1.27-2024.02.13"
    },
    {
        "ami_type": "WINDOWS_CORE_2022_x86_64",
        "cluster_version": "1.28",
        "release_version": "1.28-2024.02.13"
    },
    {
        "ami_type": "WINDOWS_CORE_2022_x86_64",
        "cluster_version": "1.29",
        "release_version": "1.29-2024.02.13"
    },
    {
        "ami_type": "WINDOWS_FULL_2019_x86_64",
        "cluster_version": "1.24",
        "release_version": "1.24-2024.02.13"
    },
    {
        "ami_type": "WINDOWS_FULL_2019_x86_64",
        "cluster_version": "1.25",
        "release_version": "1.25-2024.02.13"
    },
    {
        "ami_type": "WINDOWS_FULL_2019_x86_64",
        "cluster_version": "1.26",
        "release_version": "1.26-2024.02.13"
    },
    {
        "ami_type": "WINDOWS_FULL_2019_x86_64",
        "cluster_version": "1.27",
        "release_version": "1.27-2024.02.13"
    },
    {
        "ami_type": "WINDOWS_FULL_2019_x86_64",
        "cluster_version": "1.28",
        "release_version": "1.28-2024.02.13"
    },
    {
        "ami_type": "WINDOWS_FULL_2019_x86_64",
        "cluster_version": "1.29",
        "release_version": "1.29-2024.02.13"
    },
    {
        "ami_type": "WINDOWS_FULL_2022_x86_64",
        "cluster_version": "1.24",
        "release_version": "1.24-2024.02.13"
    },
    {
        "ami_type": "WINDOWS_FULL_2022_x86_64",
        "cluster_version": "1.25",
        "release_version": "1.25-2024.02.13"
    },
    {
        "ami_type": "WINDOWS_FULL_2022_x86_64",
        "cluster_version": "1.26",
        "release_version": "1.26-2024.02.13"
    },
    {
        "ami_type": "WINDOWS_FULL_2022_x86_64",
        "cluster_version": "1.27",
        "release_version": "1.27-2024.02.13"
    },
    {
        "ami_type": "WINDOWS_FULL_2022_x86_64",
        "cluster_version": "1.28",
        "release_version": "1.28-2024.02.13"
    },
    {
        "ami_type": "WINDOWS_FULL_2022_x86_64",
        "cluster_version": "1.29",
        "release_version": "1.29-2024.02.13"
    }
]
```

**Comment by FernandoMiguel** [comment]
is the idea here that by default, AMIs are pinned?
will this be considered a breaking change, since right now the default is to pick the most recent AMI?

**Comment by bryantbiggs** [comment]
No - there is no change to the current default behavior

**Review by antonbabenko — APPROVED** [review]

**Comment by antonbabenko** [comment]
This PR is included in version 20.6.0 :tada:

**Pull request merged**
