### PR TITLE
feat: Search for Windows or Linux AMIs only if they are needed

### LINKED ISSUE #582: how to disable windows support
# I have issues

when i run 'terraform plan' its poping up error message below. I am just thinking how can we simple disable windows support?
Error: Your query returned no results. Please change your search criteria and try again.

  on .terraform/modules/my-cluster/terraform-aws-modules-terraform-aws-eks-55ff38c/data.tf line 32, in data "aws_ami" "eks_worker_windows":
  32: data "aws_ami" "eks_worker_windows" {

## I'm submitting a...

* [x] bug report
* [ ] feature request
* [ ] support request - read the [FAQ](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/docs/faq.md) first!
* [ ] kudos, thank you, warm fuzzy

## Environment details

* Affected module version:
* OS:
* Terraform version:

### LINKED ISSUE #1100: Prevent creation of windows ami datasource when we don't define windows worker nodes
# I have issues

## I'm submitting a...

* [ ] bug report
* [x] feature request
* [ ] support request - read the [FAQ](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/docs/faq.md) first!
* [ ] kudos, thank you, warm fuzzy

## What is the current behavior?
I've just created an EKS cluster and I saw that the module is creating eks_worker_windows automatically.

Is there a way to prevent eks_worker_windows creation? I would like to keep my state as clean as possible.

Thanks.

### LINKED ISSUE #1141: module returns "query returned no results" when using a non existent cluster_version
# I have issues

## I'm submitting a...

* [x] bug report
* [ ] feature request
* [ ] support request - read the [FAQ](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/docs/faq.md) first!
* [ ] kudos, thank you, warm fuzzy

## What is the current behavior?
Get "Error: Your query returned no results. Please change your search criteria and try again." if the cluster_version specified is incorrect.

## If this is a bug, how to reproduce? Please include a code sample if relevant.
```
module "eks-cluster" {
  source          = "terraform-aws-modules/eks/aws"
  cluster_name    = var.cluster_name
  cluster_version = var.cluster_version //set this to "1.19" currently AWS latest v 1.18
  subnets         = var.subnets
  vpc_id          = var.vpc_id

  worker_groups = [
    {
      instance_type         = var.instance_type
      asg_max_size          = var.asg_max_size
      asg_desired_capacity  = var.asg_desired_capacity
      additional_userdata   = var.additional_userdata
    }
  ]
  tags = var.tags
}
```

## What's the expected behavior?
I would expect it to fail with a bit more friendly message but I get below error, it is confusing and doesn't lead to specific field.
Error: Your query returned no results. Please change your search criteria and try again.

Error: Your query returned no results. Please change your search criteria and try again.

## Environment details

* Affected module version: 13.2.1+
* OS: macOS
* Terraform version: 0.14

### LINKED ISSUE #1246: Upgrade cluster version is not supported
# I have issues

## I'm submitting a...

* [x] bug report
* [ ] feature request
* [ ] support request - read the [FAQ](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/docs/faq.md) first!
* [ ] kudos, thank you, warm fuzzy

## What is the current behavior?
I have provisioned an EKS cluster with Kubernetes version 1.18 successfully then I tried to update the Kubernetes version to 1.19 but when I am trying to run 
```terraform plan``` 
I got the following error: **Error: Your query returned no results. Please change your search criteria and try again.**

## What's the expected behavior?
It should update the cluster kubernetes version same as updating it from the GUI

## Environment details

* Affected module version: v14.0.0
* OS: Linux, Mac
* Terraform version: v0.14.3

### LINKED ISSUE #1247: EKS version 1.19 unable to find ami
# I have issues

## I'm submitting a...

* [X] bug report
* [ ] feature request
* [ ] support request - read the [FAQ](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/docs/faq.md) first!
* [ ] kudos, thank you, warm fuzzy

## What is the current behavior?

When trying to deploy an EKS cluster, version 1.19, I get the following error: 
`Error: Your query returned no results. Please change your search criteria and try again.` 
It seems as if the module is unable to find a passing ami for the nodes.

## If this is a bug, how to reproduce? Please include a code sample if relevant.

Deploy a version 1.19 EKS cluster
```
module "eks" {
  source                          = "terraform-aws-modules/eks/aws"
  version                         = "14.0.0"
  cluster_name                    = "${var.name}-${var.environment}-cluster"
  cluster_version                 = "1.19"
  subnets                         = var.private-subnets
  vpc_id                          = var.vpc_id
  cluster_endpoint_private_access = true
  cluster_endpoint_public_access  = false
  enable_irsa                     = true
  write_kubeconfig                = false

  node_groups = {
    default = {
      name             = "${var.name}-${var.environment}-node-group"
      min_capacity     = 1
      desired_capacity = var.eks_node_group.desired_capacity
      max_capacity     = var.eks_node_group.max_capacity
      instance_types   = [var.eks_node_group.instance_type]
      key_name         = var.keypair_name
      tags = [
        {
          "key"                 = "k8s.io/cluster-autoscaler/enabled"
          "propagate_at_launch" = "false"
          "value"               = "true"
        },
        {
          "key"                 = "k8s.io/cluster-autoscaler/${local.cluster_name}"
          "propagate_at_launch" = "false"
          "value"               = "true"
        }
      ]
    }
  }
  map_roles = local.roles
  map_users = local.users
  tags      = local.common_tags
}
```

## What's the expected behavior?

Terraform should be able to find a suitable ami for this cluster version.

## Are you able to fix this problem and submit a PR? Link here if you have already.

No

## Environment details

* Affected module version: 14.0.0
* OS: Ubuntu
* Terraform version: 0.14.6

## Any other relevant info

None

### PR DESCRIPTION
**Pull request by barryib**
# PR o'clock

## Description

This will add support to search for Windows (or Linux) AMI only if they are needed.

- Resolves #1100
- Resolves #1141
- Resolves #1246
- Resolves #1247
- Resolves #582

### Checklist

- [ ] CI tests are passing
- [ ] README.md has been updated after any changes to variables and outputs. See https://github.com/terraform-aws-modules/terraform-aws-eks/#doc-generation

### CODE REVIEW

**Review by dbirks — APPROVED** [review]
Nice, thank you! Just ran a plan with this branch, and it doesn't error out, even though there's not a 1.20 windows ami yet. 🎉

**Comment by barryib** [comment]
[v16.1.0](https://github.com/terraform-aws-modules/terraform-aws-eks/releases/tag/v16.1.0) is released.

**Comment by brettcave** [comment]
This PR introduced a bug that breaks if Windows nodes are used: 

https://github.com/terraform-aws-modules/terraform-aws-eks/commit/06e9078bf4baedba362f07dcfa0f3fb65e943899#diff-2fdb488192d2afd49fb090fcc8bd32fd3af72bcb789420915e78d6406ef9e2e4R19

``` 
worker_has_linux_ami   = length([for x in concat(var.worker_groups, var.worker_groups_launch_template) : x if lookup(x, "platform", "linux") == "linux"]) > 0
  worker_has_windows_ami = length([for x in concat(var.worker_groups, var.worker_groups_launch_template) : x if lookup(x, "platform", "linux") == "windows"]) > 0
```

**Comment by brettcave** [comment]
> 
> 
> > This PR introduced a bug that breaks if Windows nodes are used
> 
> @brettcave What do you mean by "it brakes" ? Can you please share your error and configuration ?

https://github.com/terraform-aws-modules/terraform-aws-eks/issues/1410

**Pull request merged**
