### PR TITLE
Revert #631. Add back manage security group flag

### PR DESCRIPTION
**Pull request by ryanooi**
# PR o'clock

## Description
Revert #631 
Fix https://github.com/terraform-aws-modules/terraform-aws-eks/issues/675

### Checklist

- [x] Change added to CHANGELOG.md. All changes must be added and breaking changes and highlighted
- [x] CI tests are passing
- [x] README.md has been updated after any changes to variables and outputs. See https://github.com/terraform-aws-modules/terraform-aws-eks/#doc-generation

### CODE REVIEW

**Comment by russki** [comment]
yes please ❤️this makes it possible to provide network access lists to private endpoints again

**Comment by barryib** [comment]
@rayanooi I'm going to test this to boostrap a fresh new cluster this week.

**Comment by russki** [comment]
@barryib how did the test go?

**Comment by dfredell** [comment]
I ran into this issue two weeks ago and found a workaround by using @ryanooi 's branch via
`source = "github.com/ryanooi/terraform-aws-eks?ref=857a8dec23884e5c9a16fd7dec7e04b627652784"`
in my `module elk` terraform.

Today I had spun up two clusters from a blank slate with the master branch of ryanooi/terraform-aws-eks successfully.

**Comment by pab1it0** [comment]
Got the same issue while creating my own worker security group. @ryanooi's master branch with: 
```
worker_security_group_id     = aws_security_group.worker_node_sg.id
worker_create_security_group = false
```
Seems to works

**Pull request merged**
