### PR TITLE
fix: Add ebs kms alias

### PR DESCRIPTION
**Pull request by aliartiza75**
## Description

I have updated the self-managed node group example manifest by adding a new resource [aws_kms_alias](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/kms_alias). It will create an alias for the EBS volume KMS encryption on AWS console.

## Motivation and Context

Alias for node group's EBS volume KMS encryption key doesn't appear on AWS console. 

## Breaking Changes

It is not a breaking change.

## How Has This Been Tested?
- [x] I have updated at least one of the `examples/*` to demonstrate and validate my change(s)
- [x] I have tested and validated these changes using one or more of the provided `examples/*` projects

- [x] I have executed `pre-commit run -a` on my pull request

### CODE REVIEW

**Comment by aliartiza75** [comment]
Hi @antonbabenko, please review this PR

**Comment by aliartiza75** [comment]
@bryantbiggs terraform docs check is failing. Please let me know how to fix it.

**Comment by antonbabenko** [comment]
You should run `pre-commit run -a` locally in this repository dir and commit the changes.

**Comment by aliartiza75** [comment]
@antonbabenko @bryantbiggs, issues are fixed please review

**Comment by bryantbiggs** [comment]
hi @aliartiza75 - since these are just examples that show how the module can be customized/configured to create an EKS cluster, I'm not sure I see the benefit of adding a KMS key alias. Could you elaborate on what problem you are trying to solve with this change?

**Comment by aliartiza75** [comment]
@bryantbiggs, when a [KMS key for EBS](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/5815d17cd2330286250ea4f81fcad3ac9bf19776/examples/self_managed_node_group/main.tf#L401) is created, it doesn't show any alias on AWS console. 

In my case, I have a lot of KMS keys for different purposes, and having a key with no **alias** is causing confusion.

**Comment by aliartiza75** [comment]
I agree but at least the resources that are being created should be created properly.

**Pull request closed without merging**
