### PR TITLE
fix: Update access entries `kubernetes_groups` default value to `null`

### LINKED ISSUE #2896: Entities: EC2_LINUX + similar causes repeat drift and apply failures
## Description

Using an EC2_LINUX (or similar) type causes this module to attempt to reset the kuberentes_groups to [] - attempting to remove a system group. This is incompatible as the EKS creates the system:nodes group connection when type = EC2_LINUX or similar. 

If your request is for a new feature, please use the `Feature request` template.

- [X] ✋ I have searched the open/closed issues and my issue is not listed.

## Versions

- Module version: 20.0.1

- Terraform version: 1.5.5

- Provider version(s): AWS: 5.35

## Reproduction Code [Required]

use something similar for the access_entities map:

```HCL
  access_entries = {
    # One access entry with a policy associated
    ex-ec2 = {
      type = "EC2_LINUX"
      principal_arn     = aws_iam_role.this["single"].arn
    }
  }
```

1) Apply as normal
2) Plan/apply again - it detects drift with the kubernetes groups

## Expected behavior

1 apply creating the entity and no drift detected on groups

## Actual behavior

Repeated plans and applies causes the resource to attempt to remove the kubernetes groups added by EKS. 

```HCL 
  # module.eks.aws_eks_access_entry.this["ex-ec2"] will be updated in-place
  ~ resource "aws_eks_access_entry" "this" {
        id                = "ex-eks-managed-node-group:arn:aws:iam::1234567890:role/ex-single"
      ~ kubernetes_groups = [
          - "system:nodes",
        ]
        tags              = {
            "Example"    = "ex-eks-managed-node-group"
            "GithubOrg"  = "terraform-aws-modules"
            "GithubRepo" = "terraform-aws-eks"
        }
        # (8 unchanged attributes hidden)
    }

```

```HCL
╷
│ Error: updating EKS Access Entry (ex-eks-managed-node-group:arn:aws:iam::1234567890:role/ex-single): operation error EKS: UpdateAccessEntry, https response error StatusCode: 400, RequestID: e3d3c468-7667-46a0-aa7a-e7d0d48e5202, InvalidParameterException: This operation can only be performed on Access Entries with a type of "STANDARD".
│ 
│   with module.eks.aws_eks_access_entry.this["ex-ec2"],
│   on ../../main.tf line 185, in resource "aws_eks_access_entry" "this":
│  185: resource "aws_eks_access_entry" "this" {
│ 
╵

```

## Additional context

I'll throw a recommended PR up shortly for this issue.

### PR DESCRIPTION
**Pull request by Bourne-ID**
## Description
Change the default kubernetes group from [] to null - it's possible that EKS will manage this attribute by adding in groups like system:nodes when specifying a type of EC2_LINUX or similar. This attribute should be unspecified if STANDARD is not defined. 

## Motivation and Context
Resolves the module attempting to change EC2_LINUX from removing the kubernetes groups set by EKS and EC2_LINUX types. 

- Resolves #2896

## Breaking Changes
No

## How Has This Been Tested?
- [X] I have updated at least one of the `examples/*` to demonstrate and validate my change(s)
- [X] I have tested and validated these changes using one or more of the provided `examples/*` projects

Tested on eks_managed_node_group by modifying the access_entities to use a EC2_LINUX type. 
- [X] I have executed `pre-commit run -a` on my pull request

### CODE REVIEW

**Comment by bryantbiggs** [comment]
I don't think this is valid. We use empty list to clear values if users remove them. I don't think anything else is modifying this and if it did it would show up in a diff

**Comment by Bourne-ID** [comment]
Would you accept a check if type is non standard, and if so null, otherwise [] ?

**Comment by Bourne-ID** [comment]
I'll refer to the issue specified - if the type is EC2_LINUX or similar then EKS will add the group which is detected by terraform if this attribute is defined opposed to null. Terraform attempts to remove the group (set to []) which is not possible when the type is non-standard.

**Comment by bryantbiggs** [comment]
What is going to use this role and what are you ultimately trying to do

**Comment by Bourne-ID** [comment]
We have legacy Auto Scaling Groups IAM roles which we want to move from aws-auth config map to EKS API. This requires the role to have the system:nodes group, as such is required to be registered as an EC2_LINUX type. 

The same for Karpenter as I have a workspace dedicated to karpenter roles; the role used for Karpenter is created outside of this module, therefore I'm passing the node role into the map for access_entities as a EC2_LINUX. 

This bug impacts anyone using this version with the EC2_LINUX and EC2_WINDOWS types - EKS will set a group to the access entity, and having the default groups set to [] will cause continous drift + a failure to apply, so once the initial apply is done, the plan+apply will begin to fail. 

Whilst this PR is the simplest solution I do respect it changes default behavour. However if someone creates an entity with groups, I would assume the average user would set this to [] instead of deleting the key to remove the groups from the entity, for example:
```HCL
ex-single = {
      kubernetes_groups = ["group1", "group2"]
      principal_arn     = aws_iam_role.this["single"].arn

      policy_associations = {
        single = {
          policy_arn = "arn:aws:eks::aws:cluster-access-policy/AmazonEKSViewPolicy"
          access_scope = {
            namespaces = ["default"]
            type       = "namespace"
          }
        }
      }
```
I would explicitly set `kubernetes_groups` to an empty array to disassociate those groups, opposed to implicit assumptions by removing the `kubernetes_group` key. 

It's possible to change  https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/main.tf#L189C1-L189C60 to something like:

```HCL 
kubernetes_groups = try(each.value.kubernetes_groups, !contains(["EC2_LINUX", "EC2_WINDOWS", "FARGATE_LINUX"], lookup(each.value, "type", "STANDARD")) ? [] : null)
```

However I feel this impacts the readability of the code, therefore was not included as part of this PR's suggestion - but this keeps the implicit behavour whilst catering for non-standard types.

**Comment by sidewinder12s** [comment]
I also just ran into this with a raw aws_eks_access_entry resource (So not what the module manages)

If you set anything on `kubernetes_groups` when using not STANDARD type, Terraform will try and remove the EKS Service added groups, which you can't.

```
  # module.cluster.aws_eks_access_entry.node will be updated in-place
  ~ resource "aws_eks_access_entry" "node" {
        id                = "use1-test01:arn:aws:iam::<omit>:role/use1-test01-self-mng"
      ~ kubernetes_groups = [
          - "system:nodes",
        ]
        tags              = {}
        # (8 unchanged attributes hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

module.cluster.aws_eks_access_entry.node: Modifying... [id=use1-test01:arn:aws:iam::<omit>:role/use1-test01-self-mng]
╷
│ Error: updating EKS Access Entry (use1-test01:arn:aws:iam::<omit>:role/use1-test01-self-mng): operation error EKS: UpdateAccessEntry, https response error StatusCode: 400, RequestID: 3fe6fbb4-8251-465a-a438-00a539d736e5, InvalidParameterException: This operation can only be performed on Access Entries with a type of "STANDARD".
```

Once I removed setting `kubernetes_groups = []` in my resource the diff went away.

**Review by bryantbiggs — APPROVED** [review]
lets give this a try - thank you!

**Comment by antonbabenko** [comment]
This PR is included in version 20.1.1 :tada:

**Pull request merged**
