### PR TITLE
feat: Added support for client.authentication.k8s.io/v1beta1

### PR DESCRIPTION
**Pull request by vsamidurai**
# PR o'clock

## Description
* Make kubeconfig_api_version configurable in templates kubeconfig.tpl

#### Please explain the changes you made here and link to any relevant issues.

Recently aws-cli switched to  client.authentication.k8s.io/v1beta from v1alpha1 and reverted back to v1alpha1. So this PR makes kubeconfig API version configurable to support Kubernetes v1.22.  

https://github.com/aws/aws-cli/pull/6309

https://github.com/terraform-aws-modules/terraform-aws-eks/issues/1526

### Checklist

- [ &#x2611;] README.md has been updated after any changes to variables and outputs. See https://github.com/terraform-aws-modules/terraform-aws-eks/#doc-generation

### CODE REVIEW

**Comment by daroga0002** [comment]
closes #1526

**Comment by daroga0002** [comment]
resolves #1526

**Comment by daroga0002** [comment]
resolves #1526

**Comment by antonbabenko** [comment]
@daroga0002 Should we merge this one? If yes, we need to fix the formatting and rebase it.

**Comment by vsamidurai** [comment]
> @vsamidurai do you think this should be variable? I have a mixed feeling here as most probably this variable will be never customised and is increasing a module inputs complexity. I would rather opt to change this permanently in template and not use variable for this.
> 
> With k8s 1.22 variable will need to be always changed to beta api so we will not avoid a `impacting` change which will happen sooner or later.
> 
> I think as of now this can be just parked for a while and merged when there will be other change modifying a launch configuration to release together.

I thought this change may block, incase if anyone wants to use the earlier version of k8s with the old version of aws-cli.  If you think the new version terraform-eks only supports cluster above 1.22 we can use hardcoded value than optional parameter.

**Comment by daroga0002** [comment]
I will review this PR and test soon 

Some usefull link to understand also issue is https://github.com/kubernetes-sigs/aws-iam-authenticator/commit/0221afb8e2a5d14a20a93473edc4c2aa7676ce95#diff-b03d5162238d36a569ac0c110484bf356f617e22967aeb1af853b02993da60b8

**Review by daroga0002 — APPROVED** [review]
@vsamidurai  thank you for contribution 🎉 

I have tested and this is working:
```
$ diff kubeconfig_lt_with_mng-xunVNPIS kubeconfig_lt_with_mng-xunVNPIS_test
23c23
<       apiVersion: client.authentication.k8s.io/v1beta1
---
>       apiVersion: client.authentication.k8s.io/v1alpha1
```

so we can merge this.

**Comment by daroga0002** [comment]
@antonbabenko  lets merge this to master

**Comment by antonbabenko** [comment]
@vsamidurai Please fix the failing checks before the merge.

**Comment by antonbabenko** [comment]
Here we go! 🎉 

[v17.23.0](https://github.com/terraform-aws-modules/terraform-aws-eks/releases/v17.23.0) has been just released.

**Pull request merged**
