### PR TITLE
Allow for specifying a custom AMI for the worker nodes.

### LINKED ISSUE #540: Support for specifying worker AMIs other than the defaults
# I have issues

## I'm submitting a...

* [ ] bug report
* [ x ] feature request
* [ ] support request - read the [FAQ](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/docs/faq.md) first!
* [ ~ ] kudos, thank you, warm fuzzy <<<<<<*Thank You!*

## What is the current behavior?
At the moment, the ami can be customised using the `worker_ami_name_filter_prefix` and `worker_ami_name_filter` vars. However the template is limited to the `owner = 602401143452`, and with a name format of `prefix-version-name`:
```
data "aws_ami" "eks_worker" {
  filter {
    name   = "name"
    values = ["${var.worker_ami_name_filter_prefix}-${var.cluster_version}-${var.worker_ami_name_filter}"]
  }

  most_recent = true

  # Owner ID of AWS EKS team
  owners = ["602401143452"]
}
```

I'd like to experiment with the ubuntu EKS images (https://cloud-images.ubuntu.com/aws-eks/) and so need to be able to override this. Happy to raise a PR, but not sure on policy on backwards compatibility. Would the easiest thing be to have a `var.worker_ami_id` that if specified overrides the existing options?

The ubuntu images are owned by `099720109477`, and have the format `ubuntu-eks/k8s_1.13/images/hvm-ssd/ubuntu-bionic-18.04-amd64-server-20190823.1`...

### PR DESCRIPTION
**Pull request by bmcstdio**
# PR o'clock

## Description

In some environments one may be required to customise the AMI used by the worker nodes.
This PR allows for specifying a custom AMI to use for the worker nodes in a backwards-compatible way (and I think it closes #540).

### Checklist

- [x] `terraform fmt` and `terraform validate` both work from the root and `examples/*` directories
- [x] CI tests are passing
- [x] I've added my change to CHANGELOG.md and highlighted any breaking changes
- [x] README.md has been updated after any changes to variables and outputs. See https://github.com/terraform-aws-modules/terraform-aws-eks/#doc-generation

### CODE REVIEW

**Comment by max-rocket-internet** [comment]
Do you think it's perhaps too complicated having 4 variables just for filtering the AMI? As opposed to users just define the data resource outside the module?

**Comment by bmcstdio** [comment]
I think so, yes, but I guess it's pretty much the only way to keep backwards-compatibility (isn't it?). If we were to break that, I'd prefer repurposing `worker_ami_name_filter` and getting rid of the `worker_ami_name_filter_prefix` one, leaving only two as we currently have. I think that defining the data source outside of the module makes things less user-friendly TBH.

**Comment by bmcstdio** [comment]
@max-rocket-internet I've rebased against `master` and fixed conflicts 🙂 Please let me know what additional changes you'd like me to make.

**Comment by max-rocket-internet** [comment]
Hey @bmcstdio! Thanks for the PR!

I think with this PR it's simply too complicated now. 4 different variables, all with quite complicated descriptions, just to set 2 attributes on the `data.aws_ami.eks_worker` resource.

I know it might seem like a minor gripe but we are always fighting to keep complexity low with this module otherwise it's kind of like "death by a thousand cuts" if you know what I mean 🙂

> pretty much the only way to keep backwards-compatibility

Don't worry about that. If it's a breaking change, just make sure you note it clearly in the changelog. When we next do a release we'll have to make sure it's a major one.

So, how about we try this:
1. Keep the `worker_ami_owner_id` variable as this will solve https://github.com/terraform-aws-modules/terraform-aws-eks/issues/480
2. Make a single variable called `worker_ami_name_filter` that defaults to `""`
3. Set the filter to default to a local that is `"amazon-eks-node-${var.cluster_version}-v*"` unless `worker_ami_name_filter` is set, in which case use that.

How does that sound?

**Comment by bmcstdio** [comment]
@max-rocket-internet sure thing, I've updated the code to reflect that. 🙂

**Comment by apatap** [comment]
How about removing/deprecating _worker_ami_name_filter_ and _worker_ami_name_filter_prefix_ by introducing _worker_node_ami_?

The documentation could be extended by an example how to write a filter. This solution would reduce the number of variables and give more flexibility.

Here an completely **untested DRAFT** of the needed code changes. Maybe the naming should be aligned with _workers_default_ami_id_ in output.tf.

#### Code changes:
local.tf

```
locals {
  ...
  workers_group_defaults_defaults = {
      ...
        ami_id = var.worker_node_ami = "" ?  data.aws_ami.eks_worker.id  : var.worker_node_ami.id
      ...
  }
  ...
}
```

variables.tf

```
variable "worker_node_ami" {
  description = "AMI for the default eks worker nodes. If none is provided, the latest version of Amazon EKS-Optimized Linux AMI is used."
  type        = any
  default     = ""
}
```


#### Code snippet for documentation:

```
data "aws_ami" "my_custom_eks_ami" {
  owners           = ["self"]
  most_recent      = true
  name_regex       = "^mycustomeksworkernodeami"
}

module "my-cluster" {
  source       = "terraform-aws-modules/eks/aws"
  ...
  worker_node_ami= data.aws_ami_id.my_custom_eks_ami.id
  ...
}
```

**Comment by max-rocket-internet** [comment]
> How about removing/deprecating worker_ami_name_filter and worker_ami_name_filter_prefix by introducing worker_node_ami

Also possible. Basically you just mean the user must pass in an AMI ID, always? I think most users, myself included, are only interested in the using the official AMIs. But maybe I'm wrong?

**Pull request merged**
