### PR TITLE
feat: Propagate managed node group labels and taints to ASG as tags

### PR DESCRIPTION
**Pull request by wcarlsen**
## Description
Propagate managed node group labels and taints to ASG as tags with configurable prefixes.

## Motivation and Context
This is super relevant usage with cluster-autoscaler, when scaling from zero. Should address following issues #2448, #2128 and #1558.

## Breaking Changes
I have disabled this feature by default, so we wont have any propagation of labels nor taints unless specified explicit.

## How Has This Been Tested?
- [x] I have updated at least one of the `examples/*` to demonstrate and validate my change(s)
- [x] I have tested and validated these changes using one or more of the provided `examples/*` projects
- [x] I have executed `pre-commit run -a` on my pull request

I had a lot of issues actually getting example for eks-managed-node-groups to work, but finally managed.

I've tested this by changing examples/eks-manage-node-group. I've tested the following settings and changes:
* Applied with default settings an saw no new added tags on ASG's
* Added new node groups and saw labels and taints being propagated with the correct applied prefix
* Disabled label and taint propagation on existing node group and saw tags being removed

Thanks to you guys for the effort and a great module and thanks to @abstrask for helping out.

### CODE REVIEW

**Comment by bryantbiggs** [comment]
I am getting 
`│ Error: error waiting for EKS Node Group (ex-eks-managed-node-group:complete-eks-mng-20230208163733128000000043) to create: unexpected state 'CREATE_FAILED', wanted target 'ACTIVE'. last error: 2 errors occurred:` on the example with these changes

**Comment by wcarlsen** [comment]
If examples actually worked out of the box, which it didn't, it would probably be easier to contribute. Instead of not looking at the actually contribution, could we discuss if the approach is viable and different from what you previously tried, since you haven't commented on it yet ✌️ Where to go from here, any hints

**Comment by bryantbiggs** [comment]
I'm sorry but you lost me - are you saying the example on `main` today does not work or you are looking for hints on making your solution work, something else?

**Comment by wcarlsen** [comment]
Both

**Comment by wcarlsen** [comment]
Yeah examples/eks_managed_node_group/ is broken alright.

So reverting back my commits and running on commit id 4b7fe4637a048a52422ee04d6146136f48900695 I initially get this error related to subnets and IPv6:

`Error: setting EC2 Subnet (subnet-0e66ca5dcc8d25e73) AssignIpv6AddressOnCreation: InvalidParameterValue: Invalid value 'true' for assign-ipv6-address-on-creation. Cannot set assign-ipv6-address-on-creation to true unless the subnet (subnet-0e66ca5dcc8d25e73) has an IPv6 CIDR block associated with it.
│       status code: 400, request id: 35801c5c-747b-45bf-88e5-168c3546df1c
│
│   with module.vpc.aws_subnet.intra[0],
│   on .terraform/modules/vpc/main.tf line 569, in resource "aws_subnet" "intra":
│  569: resource "aws_subnet" "intra" {
`

Fixing this by adding `intra_subnet_ipv6_prefixes = [6, 7, 8]` to vpc module fixes the issue.

Then running into this error:
`Error: "block_device_mappings.0.ebs.0.kms_key_id" (2fcb3f5e-d474-4820-8dc1-ac6a5b283d39) is an invalid ARN: arn: invalid prefix
│
│   with module.eks.module.eks_managed_node_group["complete"].aws_launch_template.this[0],
│   on ../../modules/eks-managed-node-group/main.tf line 36, in resource "aws_launch_template" "this":
│   36: resource "aws_launch_template" "this" {
`

Fixing it by changing `kms_key_id = module.ebs_kms_key.key_id` to `kms_key_id = module.ebs_kms_key.key_arn`

Then running into conflicting CIDR for subnets because a previous failed run:

` Error: creating EC2 Subnet: InvalidSubnet.Conflict: The CIDR '10.9.53.0/24' conflicts with another subnet
│       status code: 400, request id: 71d6e4cb-38d3-449e-b94a-3f4e7e180921
│
│   with module.vpc.aws_subnet.intra[1],
│   on .terraform/modules/vpc/main.tf line 569, in resource "aws_subnet" "intra":
│  569: resource "aws_subnet" "intra" {
`
Fixing it by deleting the conflicting subnets via management console.

And I haven't event gotten close to spawning a cluster yet, nor tested my change.

**Comment by wcarlsen** [comment]
I think fixing that last error is completely out of scope and asking too much for a fix that just adds tags to asg's. I would suggest commenting out the `complete = {...}` node group section since it is broken in master i.e. 4b7fe4637a048a52422ee04d6146136f48900695 and then have someone else fix that for a later time.

**Comment by abstrask** [comment]
> `Error: setting EC2 Subnet (subnet-0e66ca5dcc8d25e73) AssignIpv6AddressOnCreation: InvalidParameterValue: Invalid value 'true' for assign-ipv6-address-on-creation. Cannot set assign-ipv6-address-on-creation to true unless the subnet (subnet-0e66ca5dcc8d25e73) has an IPv6 CIDR block associated with it. │ status code: 400, request id: 35801c5c-747b-45bf-88e5-168c3546df1c │ │ with module.vpc.aws_subnet.intra[0], │ on .terraform/modules/vpc/main.tf line 569, in resource "aws_subnet" "intra": │ 569: resource "aws_subnet" "intra" { `
> 
> Fixing this by adding `intra_subnet_ipv6_prefixes = [6, 7, 8]` to vpc module fixes the issue.

I suspect this problem was with the example was introduced with [release 3.16.0 of the VPC module](https://github.com/terraform-aws-modules/terraform-aws-vpc/releases/tag/v3.16.0), which introduces a lot of changes regarding IPv6.

The [version constraint on the VPC module](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/4b7fe4637a048a52422ee04d6146136f48900695/examples/eks_managed_node_group/main.tf#L300-L302) referenced in the example allows for minor version upgrades. Is this intentional or should it be more specific and only allow patch upgrades?

As for the problem with `kms_key_id`, I think it stems from the fact that the input in the `ebs` block to `aws_launch_template` resource [expects the ARN of the KMS key](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/launch_template#kms_key_id) and not the ID, as the name suggests.

Changing the reference to the KMS key ARN, as @wcarlsen suggested, seems to fix it.

I haven't dived into the subnet conflict issue 🤷.

**Comment by bryantbiggs** [comment]
thanks for the call out - not sure why some of those examples stopped working but I have just updated to ensure they are functioning as intended

**Comment by wcarlsen** [comment]
Just did another from scratch apply on the example pulling in your fixes and the asg tagging propagation still works as intended.

**Comment by wcarlsen** [comment]
So @bryantbiggs any chance you had the time to look at the actual changes intended by this PR  (node group taint and label propagation to asg) or is stuck because of something else I'm missing?

**Comment by wcarlsen** [comment]
Just wanted to add that my team and I are quite happy with having implemented automatic propagation of node group labels and taints as tags for the ASGs, when using cluster-autoscaler. This propagation can both be implemented outside the module as show in this issue [#2448](https://github.com/terraform-aws-modules/terraform-aws-eks/issues/2448#issuecomment-1420914467). But it can also be implemented from inside the module as well as shown with this PR, even though I think it is mostly an AWS responsibility, since we never really configure the ASGs. I hope I can convince someone to have a second look at this PR and give it an actual chance.

**Comment by wcarlsen** [comment]
I fully respect the explicit choice not to include an ASG tagging feature into the module. Once that is out of the way it is not like this topic is not showing up multiple times in the this projects issues and the statement made here (https://github.com/terraform-aws-modules/terraform-aws-eks/issues/2448#issuecomment-1420977558) about this not being possible, from the module perspective, is simply not true.

**Pull request closed without merging**
