### PR TITLE
feat: Add autoscaling_group_tag to node_groups

### PR DESCRIPTION
**Pull request by wgj**
Initial commit for ci tests

# PR o'clock

## Description

Please explain the changes you made here and link to any relevant issues.

### Checklist

- [ ] README.md has been updated after any changes to variables and outputs. See https://github.com/terraform-aws-modules/terraform-aws-eks/#doc-generation

### CODE REVIEW

**Comment by wgj** [comment]
@bryantbiggs Could I get CI tests on this?

**Comment by bryantbiggs** [comment]
unfortunately, I don't have access on this repo - @antonbabenko should be able to help when he gets a chance

**Comment by daroga0002** [comment]
> Could I get CI tests on this?

they will run as part of `pre-commit` config.

Just run `pre-commit run -a`

**Comment by jaimehrubiks** [comment]
What does it mean that only one tag? Autoscaler may need more (label, taint, cpu...) in some cases. Or am I understanding it wrong?

**Comment by antonbabenko** [comment]
@wgj I don't understand what this PR is for in the first place because there is just a comment in the code, but please fill in the PR template when you make a PR.

Mark it not draft if you are ready for the review, run `pre-commit run -a` (as @daroga0002 said).

**Comment by antonbabenko** [comment]
This issue has been resolved in version 18.0.0 :tada:

**Pull request closed without merging**
