### PR TITLE
Use static not computed worker group count

### PR DESCRIPTION
**Pull request by laverya**
# PR o'clock

## Description

`length(var.worker_groups)` has been replaced by a top-level variable `worker_group_length` as `length` of a computed value cannot be used. This fixes https://github.com/terraform-aws-modules/terraform-aws-eks/issues/73

Breaking Changes:
`worker_group_length` must be specified to use more than one worker group.

### Checklist

- [x] `terraform fmt` and `terraform validate` both work from the root and `examples/eks_test_fixture` directories (look in CI for an example)
- [x] Tests for the changes have been added and passing (for bug fixes/features)
- [ ] Test results are pasted in this PR (in lieu of CI)
- [x] Docs have been updated using `terraform-docs` per `README.md` instructions
- [x] I've added my change to CHANGELOG.md
- [x] Any breaking changes are highlighted above

### CODE REVIEW

**Comment by brandoconnor** [comment]
Looking good. Let me know when this is ready for review.

**Comment by laverya** [comment]
@brandoconnor I think the code itself is done, if this is the solution to go with - I'm just not sure what version to mark this as being part of (and thus what to put in the changelog). `1.4.0` or `2.0.0`?

**Comment by laverya** [comment]
I've added this to the `1.4.0` changelog.

**Comment by laverya** [comment]
I've added this to the `1.4.0` changelog.

**Comment by brandoconnor** [comment]
Thanks again for this and apologies on the review delay. I had a super busy week of preparing for my wedding! 👰 🤵 

Reviewing now

**Pull request merged**
