### PR TITLE
Replace Travis with GitHub Actions

### PR DESCRIPTION
**Pull request by nauxliu**
It will be looks like https://github.com/nauxliu/terraform-aws-eks/commit/24e565ef3c6d8e07af8236e4980046e1f570b2b3/checks

### CODE REVIEW

**Comment by max-rocket-internet** [comment]
What do you guys think? @antonbabenko @brandoconnor

**Comment by barryib** [comment]
Can we take avantage of this PR to test if docs is updated correctly ? By running manually pre-commit hooks for exemple `pre-commit run -a`. This should fail if something get wrong (doc or format not updated).

**Comment by nauxliu** [comment]
@barryib Sounds great, I'll make another PR for that after this one gets merged.

**Comment by brandoconnor** [comment]
Though I haven't reviewed the code change, overall I'm all 👍 for migrating to github actions. Thanks for the contribution @nauxliu ! 👏

**Pull request merged**
