### PR TITLE
feat: Support access_config

### PR DESCRIPTION
**Pull request by dtscssap**
## Description
New input to module to support EKS cluster [access_config](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/eks_cluster#access_config)

## Motivation and Context
Cannot use the new [eks_access_policy_associations](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/eks_access_policy_association) or [eks_access_entry](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/eks_access_entry) resources without modifying the cluster config to support them.

## Breaking Changes
Module will now require `aws` provider version `>= 5.34`

## Open Issue
Resolves https://github.com/terraform-aws-modules/terraform-aws-eks/issues/2881

## How Has This Been Tested?
- [X] I have updated at least one of the `examples/*` to demonstrate and validate my change(s)
- [X] I have tested and validated these changes using one or more of the provided `examples/*` projects

- [X] I have executed `pre-commit run -a` on my pull request

### CODE REVIEW

**Comment by bryantbiggs** [comment]
thank you! however, its a bit more involved than this as you can see here https://github.com/terraform-aws-modules/terraform-aws-eks/pull/2858/commits/4f3be36ff0c2d060a0352a03ea3e23236c07f932

this will be available in the next few days when v20.0 is released on #2858

**Comment by paalkr** [comment]
Looking forward to the access entries and policies support. Any update on the ETA for the v20.0 release?

**Comment by bryantbiggs** [comment]
working on final testing/validating as we speak and the upgrade guide - hopefully tomorrow

**Comment by paalkr** [comment]
Thank you so much for the status update!

**Pull request closed without merging**
