### PR TITLE
fix: Regression broken MNG with LT, introduced in 14.0

### LINKED ISSUE #1211: LaunchTemplate support for MNG broken with v14.0.0
# I have issues

## I'm submitting a...

* [x] bug report

## What is the current behavior?

https://github.com/terraform-aws-modules/terraform-aws-eks/pull/1129 that got released with `v14.0.0` breaks the LT-support for MNG that got added by me with #997 and 13.1 !

when using an LT, you cannot set instance-type on the MNG itself ! however this commit breaks the logic

https://github.com/terraform-aws-modules/terraform-aws-eks/commit/8978997bb1d5a769f03eac764d4da3caddfb9c76#diff-7a3fc6c7df17fda0c341e61255461bf1f149256a9ddf14d4a18ab6f020d08136

using v14.0.0, TF wrongly wants to add the instance_type to existing MNG with LT but then also fails while trying so. 

>InvalidRequestException: Cannot specify instance types in launch template and API request

## If this is a bug, how to reproduce? Please include a code sample if relevant.

try to create or run on existing MNG with LT

## What's the expected behavior?

no regression. behavior <14.0 is expected

## Environment details

* Affected module version: v14.0.0
* OS: macOS 11.0.1
* Terraform version: 0.14.5

## Any other relevant info

### PR DESCRIPTION
**Pull request by philicious**
# PR o'clock

## Description

fixes #1211 , introduced in #1129 

### Checklist

- [x] CI tests are passing
- [x] README.md has been updated after any changes to variables and outputs. See https://github.com/terraform-aws-modules/terraform-aws-eks/#doc-generation

### CODE REVIEW

**Comment by philicious** [comment]
cc @ArchiFleKs

**Comment by philicious** [comment]
@barryib could have a look at this ? Cannot request reviews

**Comment by ArchiFleKs** [comment]
Do you want me to include this in my PR @philicious or wait until this is merge to rebase ?

**Comment by dusansusic** [comment]
I tested this but it still wants to recreate my existing node groups with launch templates. Have you tested this, @philicious ? I will have more time during the weekend.

**Comment by philicious** [comment]
@dusansusic its not a fix to prevent the recreation of MNGs. that might still happen because the addition of the `capacity_type` will cause them to be recreated. (but can be fixed up manually in TF-state if you feel lucky)

this PR fixes the situation where you are unable to either create or update MNGs **at all** , as the instance-type is set on the MNG by default, no matter if an LT is present, but you can only set it in either one of both

**Comment by philicious** [comment]
@ArchiFleKs uhm, I guess your PR will take longer to be finished and eventually merged. so I would prefer my PR/fix to be standalone and with a higher chance of getting merged earlier. but of course feel free to use the fix already

**Comment by thehar** [comment]
This regression is painful. Is there an ETA on shipping a patch?

**Comment by jcam** [comment]
+1 what thehar said. I guess I'll force my systems to use the v13 module for now, though i'm building new clusters this week and it'd be nice to not have to recreate everything a zillion times

**Comment by ArchiFleKs** [comment]
@philicious actually I forgot that it was already here https://github.com/terraform-aws-modules/terraform-aws-eks/pull/1138/files#diff-7a3fc6c7df17fda0c341e61255461bf1f149256a9ddf14d4a18ab6f020d08136R17

**Comment by barryib** [comment]
@philicious is this PR still needed ? If yes, can you please update your branch ?

**Comment by philicious** [comment]
@barryib nope, fixed by #1138

**Pull request closed without merging**
