### PR TITLE
New release 10.0.0

### PR DESCRIPTION
**Pull request by barryib**
# PR o'clock

## Description

Prepare for new release.

@max-rocket-internet I added enhancements and bug fixes section for new release. Furthermore I propose to use git PR id with link `(GH-xxxx)` instead of `(by @you)`. I think that PR reference is more is more usefull than the author name. I'll add a kind of script from [hashicorp/terraform](https://github.com/hashicorp/terraform/blob/master/scripts/changelog-links.sh) to update link before a new release.

What do you think ?

### Checklist

- [x] Change added to CHANGELOG.md. All changes must be added and breaking changes and highlighted
- [x] CI tests are passing
- [x] README.md has been updated after any changes to variables and outputs. See https://github.com/terraform-aws-modules/terraform-aws-eks/#doc-generation

### CODE REVIEW

**Comment by max-rocket-internet** [comment]
@antonbabenko is this file even used? https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/version

**Comment by max-rocket-internet** [comment]
> What do you think ?

All sounds great 👍

Unrelated but I just create this issue: https://github.com/terraform-aws-modules/terraform-aws-eks/issues/781

**Comment by antonbabenko** [comment]
I don't think the `version` file is used for anything good.

**Comment by max-rocket-internet** [comment]
Aight then, @barryib let's just delete that file 🙂

**Comment by barryib** [comment]
> Aight then, @barryib let's just delete that file 🙂

Done.

**Comment by sc250024** [comment]
Wicked! Thank you @max-rocket-internet @barryib

**Pull request merged**
