### PR TITLE
fix: Compact result of cluster security group to avoid disruptive updates when no security groups are supplied

### LINKED ISSUE #1892: eks module tries to force cluster recreation if no cluster_security_group_id specified
## Description

There seems to be a regression of a very old issue https://github.com/terraform-aws-modules/terraform-aws-eks/pull/798 where if 
`cluster_security_group_id` is not specified and creation is disabled, the EKS module will try and replace the cluster every time.

Technically, the EKS module documentation does indicate `cluster_security_group_id` is a required parameter if `create_cluster_security_group` is set to `false`, however it is an optional parameter in the dependent `aws_eks_cluster` module and it should not be required since EKS creates a baseline cluster security group on cluster creation no matter what.

I think this should be as simple as wrapping this line in `compact()` -- 
https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/main.tf#L16 to restore the previous behavior of removing any empty string values

## Versions
- Terraform:
   - Terraform v1.1.4 on darwin_amd64
 - Provider(s):
   + provider registry.terraform.io/hashicorp/aws v3.74.3
   + provider registry.terraform.io/hashicorp/cloudinit v2.2.0
   + provider registry.terraform.io/hashicorp/tls v3.1.0
 - Module: 
   - 18.2.7

## Reproduction

- Run terraform plan/terraform apply
- After first apply, re-run terraform plan

```
      ~ vpc_config {
          ~ cluster_security_group_id = "sg-XXXXXX" -> (known after apply)
          ~ security_group_ids        = [ # forces replacement
              + "",
            ]
          ~ vpc_id                    = "vpc-YYYYY" -> (known after apply)
            # (4 unchanged attributes hidden)
        }
```

### Code Snippet to Reproduce
```
module "eks" {
  source  = "terraform-aws-modules/eks/aws"
  version = "18.7.2"

  cluster_name                    = "test-cluster"
...

  create_cluster_security_group = false
  create_node_security_group    = false
...
}
```

## Expected behavior

Modules should not detect any changes

## Actual behavior

Module thinks something has changed and tries to destroy

### PR DESCRIPTION
**Pull request by bryantbiggs**
## Description
- Compact result of cluster security group to avoid disruptive updates when no security groups are supplied

## Motivation and Context
- Closes #1892
- Relates to #1911
- Closes #1921
- Relates to #1933

## Breaking Changes
- No

## How Has This Been Tested?
- [x] I have tested and validated these changes using one or more of the provided `examples/*` projects

### CODE REVIEW

**Comment by drunkirishcoder** [comment]
waiting on this fix, can this be merged and released soon?

**Comment by bryantbiggs** [comment]
@antonbabenko if you get a chance - this should be good to go

**Comment by antonbabenko** [comment]
This PR is included in version 18.10.1 :tada:

**Comment by renato0307** [comment]
@bryantbiggs @antonbabenko Thanks for the fix and release!

**Comment by drunkirishcoder** [comment]
thank you for the release!

**Pull request merged**
